### ISSUE TITLE
Consider doing preflight requests to not require CORS headers

### ISSUE THREAD

**Issue by MTRNord** [ajbura/cinny#1]
**Is your feature request related to a problem? Please describe.**
The client currently requires CORS headers instead of sending an OPTION request before the actual request. This can (and does) break some of the current matrix server setups as other clients instead do preflight requests.

**Describe the solution you'd like**
An implementation of https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request though it seems like there might be another problem with the current well known request as the browser doesnt auto issue the request as expected.

**Additional context**
![image](https://user-images.githubusercontent.com/1374914/127350996-5ff57b8e-3c49-467c-b144-424cd201c58d.png)

**Comment by ajbura** [comment]
Temporarily https://github.com/ajbura/cinny/commit/d9e27bfaf1a13f92220362edb7fe2f896e08aac9 fixes this but gonna let it open so that I can look on it properly.

**Comment by ajbura** [comment]
Should be fixed with a83aecaa69529dbe610712f7eaed5deb272e5fdd
