### ISSUE TITLE
Group DMs with people that share a space into the space

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1012]
### Describe the problem

Cinny currently only shows DMs in the People area, other Clients like Element and FluffyChat allow DMs to be grouped into Spaces that you share with your conversation partners.

### Describe the solution you'd like

It would be nice for Cinny to have an option that shows DMs with conversation partners in the Space that one shares with them.

**Comment by kfiven** [comment]
We have no plans to do this as we would like to show what's actually part of the space. 

Since we want to treat spaces as community spaces, showing someone personal rooms confuse the user and create inconsistent spaces experience for different users.
