### ISSUE TITLE
Use small size thumbnails instead of full image until user clicks image

### ISSUE THREAD

**Issue by e00E** [ajbura/cinny#1016]
### Describe the problem

With Element I see using my browser's network console that only image thumbnails are fetched until I click on the image at which point the full size image is fetched.

With Cinny I see that the full size image is always fetched.

This is problem on slow internet connections. Many chats contains large images that saturate connections for a long time. Thumbnails are much smaller so they aren't a problem.

### Describe the solution you'd like

Cinny to fetch thumbnails like Element.

**Comment by kfiven** [comment]
We have added a low-bandwidth mode in settings.
