### ISSUE TITLE
Message context menu doesn't work on desktop Firefox with touchscreen

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1021]
### Describe the bug

It's not possible to e.g. reply to a message as the context menu is unresponsive on mobile.
**expected:**

### Reproduction

1. tap on message: opens context menu
2. tap on context menu button: closes context menu without doing anything

### Expected behavior

1. tap on message: opens context menu
2. tap on context menu button: does what the button does

### Platform and versions

```shell
dev.cinny.in
Firefox ESR
postmarketOS
PinePhone
```

**Comment by LinuxinaBit** [comment]
It works fine for me on Chrome/iPad, and on Fennec(Firefox)/Android
It could be a bug with Firefox on the PinePhone, or postmarketOS not handling touches properly.
Have you tried Chromium or Gnome Web (which uses Webkit)?

**Comment by notramo** [comment]
@RageGamerBoi, Firefox on the PinePhone is actually desktop Firefox, which uses a different touch handler mechanism.

**Comment by LinuxinaBit** [comment]
Ah, so that could be the problem… I’d change the title of the issue to something like, “Message Context Menu Doesn’t Work on Touchscreen Desktop Firefox” then. Makes it a little bit easier to understand the issue for the other people who know what they’re doing more than me…
