### ISSUE TITLE
Emoji search in emoji and reaction picker should also search for custom emoji

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1024]
### Describe the bug

This is related to #121 

While the inline search with `:<search_term>` now correctly shows any emoji matching <search_term> anywhere in the shortcode the search bar in the emoji and reaction picker only show matches for unicode emoji, ignoring custom emoji.

### Reproduction

1. add at least one custome emoji
2. click the emoji button next to the message field
3. search for (part of) the custom emojis shortcode
4. no results

### Expected behavior

The search matches custom emoji as well as the default ones.

### Platform and versions

```shell
Cinny version 2.2.2
```

**Comment by kfiven** [comment]
duplicate of #836
