### ISSUE TITLE
Make the matrix url of media accessible

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1025]
### Describe the problem

When opening media in a new tab / using copy image link a `blob:` url is shown.

### Describe the solution you'd like

It should be possible to get the actual URL in the https://<matrix_fqdn>/matrix/_media/[...]` format, either with a new button on the media viewer or always using that url format instead of blob:

### Additional context

It is not possible to share image links from Cinny, one has to use a different client like Element to get the actual url.

**Comment by viasux** [comment]
I think that, since the media is already being accessed in this way when on an unencrypted room, it should open the url by default. Of course this isn't possible in encrypted rooms, so it should still use the `blob:` format in those.
