### ISSUE TITLE
emoji "eye_in_speech_bubble" shows incorrectly

### ISSUE THREAD

**Issue by kok42** [ajbura/cinny#1028]
### Describe the bug

Emoji "eye_in_speech_bubble" shows incorrectly. It appears as two separate images of speech abubble and eye. In the selection menu another empty line appears.

### Reproduction

1. Use this emoji in any context or oprn a selection menu

### Expected behavior

Expected it to be shown as 👁️‍🗨️ 

### Platform and versions

```shell
1. Windows 10
2. Opera GX
3. app.cinny.in
4. martix.org
```

### Additional context

![image](https://user-images.githubusercontent.com/35006146/208456689-1b17b4f1-3c49-406a-8db3-e3da613fd773.png)
![image](https://user-images.githubusercontent.com/35006146/208456849-bb9e136b-0f1e-4a62-9177-9419ede16361.png)

**Comment by kfiven** [comment]
Upstream issue https://github.com/twitter/twemoji/issues/405
