### ISSUE TITLE
Can’t open Cinny when spaces nesting has a loop

### ISSUE THREAD

**Issue by zarp-dev** [ajbura/cinny#103]
#### Describe the bug
When I try to open Cinny it says ‘Heating up’ and won’t load.

#### Desktop (please complete the following information):
- OS: MacOS Catalina 10.15.7
- Browser: Brave 1.23.71 Chromium: 90.0.4430.72

**Comment by zarp-dev** [comment]
I tried to open it on Brave Browser (which is based on chromium) and it doesn't load.
Here's log from dev console:

main.2d096f91f54b9fe41f1a.bundle.js:2 IndexedDBStore.startup: connecting to backend
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend.connect: connecting...
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend.connect: awaiting connection...
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend.connect: upgrading from 0
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend.connect: connected
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend: loading account data...
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend: loading sync data...
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend: loaded account data
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend: loaded sync data
main.2d096f91f54b9fe41f1a.bundle.js:2 LocalIndexedDBStoreBackend: loaded initial data
main.2d096f91f54b9fe41f1a.bundle.js:2 IndexedDBStore.startup: loading presence events
main.2d096f91f54b9fe41f1a.bundle.js:2 IndexedDBStore.startup: processing presence events
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: Starting up crypto store...
main.2d096f91f54b9fe41f1a.bundle.js:2 connecting to indexeddb crypto-store
main.2d096f91f54b9fe41f1a.bundle.js:2 Upgrading IndexedDBCryptoStore from version 0 to 10
main.2d096f91f54b9fe41f1a.bundle.js:2 connected to indexeddb crypto-store
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: initialising roomlist...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: initialising crypto object...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: initialising Olm...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: initialising Olm device...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: loading device list...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: fetching own devices...
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: adding this device to the store...
main.2d096f91f54b9fe41f1a.bundle.js:2 Now tracking device list for @jabaduba:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 Crypto: checking for key backup...
main.2d096f91f54b9fe41f1a.bundle.js:2 Checking key backup status...
main.2d096f91f54b9fe41f1a.bundle.js:2 Fetching new TURN credentials
main.2d096f91f54b9fe41f1a.bundle.js:2 Getting saved sync token...
main.2d096f91f54b9fe41f1a.bundle.js:2 Getting push rules...
main.2d096f91f54b9fe41f1a.bundle.js:2 Got saved sync token
main.2d096f91f54b9fe41f1a.bundle.js:2 Getting saved sync...
main.2d096f91f54b9fe41f1a.bundle.js:2 Got reply from saved sync, exists? false
main.2d096f91f54b9fe41f1a.bundle.js:2 Got TURN URIs: turn:turn.matrix.org:3478?transport=udp,turn:turn.matrix.org:3478?transport=tcp,turns:turn.matrix.org:443?transport=tcp refresh in 86400 secs
main.2d096f91f54b9fe41f1a.bundle.js:2 Key backup is absent or missing required data
main.2d096f91f54b9fe41f1a.bundle.js:2 No usable key backup: not enabling key backup
main.2d096f91f54b9fe41f1a.bundle.js:2 Got push rules
main.2d096f91f54b9fe41f1a.bundle.js:2 Checking lazy load status...
main.2d096f91f54b9fe41f1a.bundle.js:2 Checking server lazy load support...
main.2d096f91f54b9fe41f1a.bundle.js:2 Enabling lazy load on sync filter...
main.2d096f91f54b9fe41f1a.bundle.js:2 Checking whether lazy loading has changed in store...
main.2d096f91f54b9fe41f1a.bundle.js:2 Storing client options...
main.2d096f91f54b9fe41f1a.bundle.js:2 Saving device tracking data null
main.2d096f91f54b9fe41f1a.bundle.js:2 Stored client options
main.2d096f91f54b9fe41f1a.bundle.js:2 Getting filter...
main.2d096f91f54b9fe41f1a.bundle.js:2 Sending first sync request...
main.2d096f91f54b9fe41f1a.bundle.js:2 Waiting for saved sync before starting sync processing...
main.2d096f91f54b9fe41f1a.bundle.js:2 Initial sync performed - resetting device tracking state
main.2d096f91f54b9fe41f1a.bundle.js:2 Now tracking device list for @jabaduba:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 Enabling encryption in !YMSpHZNxQCLyqyVuOE:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 Enabling encryption in !ZAnUDQOxwlkRQFxeUM:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 Enabling encryption in !pMlTYAJVOGlfvdhaIg:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 Error decrypting event (id=$ODOsA927vJM896o2jQxiiqpQFddVKk6i0gCd82KkbaI): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: tjSBFh4BjXDoXMOT7JfVqtYdzujTl91R/XCF+VIgDwk|kr1IMI8Zlrwo7oN2iJman2s6wT526LjKVrtYcVgreD4]
(anonymous) @ main.2d096f91f54b9fe41f1a.bundle.js:2
main.2d096f91f54b9fe41f1a.bundle.js:2 Enabling encryption in !mlrZfiUifZOlaHpnDw:matrix.org
main.2d096f91f54b9fe41f1a.bundle.js:2 PREPARED state
main.2d096f91f54b9fe41f1a.bundle.js:2 previous state:  null
main.2d096f91f54b9fe41f1a.bundle.js:2 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at a.value (main.2d096f91f54b9fe41f1a.bundle.js:2)
    at main.2d096f91f54b9fe41f1a.bundle.js:2
    at Array.forEach (<anonymous>)
    at a.value (main.2d096f91f54b9fe41f1a.bundle.js:2)
    at main.2d096f91f54b9fe41f1a.bundle.js:2
    at Array.forEach (<anonymous>)
    at a.value (main.2d096f91f54b9fe41f1a.bundle.js:2)
    at main.2d096f91f54b9fe41f1a.bundle.js:2
    at Array.forEach (<anonymous>)
    at a.value (main.2d096f91f54b9fe41f1a.bundle.js:2)
main.2d096f91f54b9fe41f1a.bundle.js:2 enqueueing key request for !ZAnUDQOxwlkRQFxeUM:matrix.org / kr1IMI8Zlrwo7oN2iJman2s6wT526LjKVrtYcVgreD4
main.2d096f91f54b9fe41f1a.bundle.js:2 Error decrypting event (id=$E-MvYJW5kzP4ei-LPeWnVtEWzAqPb7ZQrZdnhSwp3H0): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: tjSBFh4BjXDoXMOT7JfVqtYdzujTl91R/XCF+VIgDwk|09kXEECkkrsrKoQQ3yTH6As84QGVCXJ78mxeYX/fAMQ]
(anonymous) @ main.2d096f91f54b9fe41f1a.bundle.js:2
main.2d096f91f54b9fe41f1a.bundle.js:2 Error decrypting event (id=$0wjL8ZMlyJy_Ybyftk5T8Y_x-C1nEedg5-bpHlAb72M): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: LkIijhFMgLWEF9iAqaPXuZFMqgg9nCy/su55osxFUWQ|uWBZVjLdk02kwb7V+rDs2uQkzEw4Uy9bLfF7dJzPGlY]
(anonymous) @ main.2d096f91f54b9fe41f1a.bundle.js:2
main.2d096f91f54b9fe41f1a.bundle.js:2 enqueueing key request for !ZAnUDQOxwlkRQFxeUM:matrix.org / 09kXEECkkrsrKoQQ3yTH6As84QGVCXJ78mxeYX/fAMQ
main.2d096f91f54b9fe41f1a.bundle.js:2 enqueueing key request for !ZAnUDQOxwlkRQFxeUM:matrix.org / uWBZVjLdk02kwb7V+rDs2uQkzEw4Uy9bLfF7dJzPGlY

**Comment by kfiven** [comment]
Hi, could you possibly run a development version locally and then provide console log. app.cinny.in is minified so it's almost impossible to catch it's origin.

**Comment by kfiven** [comment]
To run development version, clone the repository locally, run `npm install` and then `npm start`

**Comment by zarp-dev** [comment]
I ran development version and opened the developer console in my browser and saved the log, here it is:
```
VM6276 index.js:53 [WDS] Live Reloading enabled.
react-dom.development.js:26239 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
logger.js:59 IndexedDBStore.startup: connecting to backend
logger.js:59 LocalIndexedDBStoreBackend.connect: connecting...
logger.js:59 LocalIndexedDBStoreBackend.connect: awaiting connection...
logger.js:59 LocalIndexedDBStoreBackend.connect: connected
logger.js:59 LocalIndexedDBStoreBackend: loading account data...
logger.js:59 LocalIndexedDBStoreBackend: loading sync data...
logger.js:59 LocalIndexedDBStoreBackend: loaded account data
logger.js:59 LocalIndexedDBStoreBackend: loaded sync data
logger.js:59 LocalIndexedDBStoreBackend: loaded initial data
logger.js:59 IndexedDBStore.startup: loading presence events
logger.js:59 IndexedDBStore.startup: processing presence events
logger.js:59 Crypto: Starting up crypto store...
logger.js:59 connecting to indexeddb crypto-store
logger.js:59 connected to indexeddb crypto-store
logger.js:59 Crypto: initialising roomlist...
logger.js:57 [WDS] Live Reloading enabled.
logger.js:59 Crypto: initialising crypto object...
logger.js:59 Crypto: initialising Olm...
logger.js:59 Crypto: initialising Olm device...
logger.js:59 Crypto: loading device list...
logger.js:59 Crypto: fetching own devices...
logger.js:59 Crypto: checking for key backup...
logger.js:59 Checking key backup status...
logger.js:59 Fetching new TURN credentials
logger.js:59 Getting saved sync token...
logger.js:59 Getting push rules...
logger.js:59 Got saved sync token
logger.js:59 Getting saved sync...
logger.js:59 Got reply from saved sync, exists? false
logger.js:59 Got push rules
logger.js:59 Checking lazy load status...
logger.js:59 Checking server lazy load support...
logger.js:59 Got TURN URIs: turn:turn.matrix.org:3478?transport=udp,turn:turn.matrix.org:3478?transport=tcp,turns:turn.matrix.org:443?transport=tcp refresh in 86400 secs
logger.js:57 Key backup is absent or missing required data
logger.js:59 No usable key backup: not enabling key backup
logger.js:59 Enabling lazy load on sync filter...
logger.js:59 Checking whether lazy loading has changed in store...
logger.js:59 Storing client options...
logger.js:59 Stored client options
logger.js:59 Getting filter...
logger.js:59 Sending first sync request...
logger.js:59 Waiting for saved sync before starting sync processing...
logger.js:59 Initial sync performed - resetting device tracking state
logger.js:59 Now tracking device list for @jabaduba:matrix.org
logger.js:59 Enabling encryption in !ZAnUDQOxwlkRQFxeUM:matrix.org
logger.js:59 Enabling encryption in !YMSpHZNxQCLyqyVuOE:matrix.org
logger.js:59 Enabling encryption in !clKXNOSooYOJUgMKuX:matrix.org
logger.js:59 Enabling encryption in !gKVTDcNwgbKNZBbWxC:matrix.org
logger.js:59 Enabling encryption in !jIaYpprsmHacvkADrK:matrix.org
logger.js:59 Enabling encryption in !mlrZfiUifZOlaHpnDw:matrix.org
logger.js:59 Enabling encryption in !pMlTYAJVOGlfvdhaIg:matrix.org
initMatrix.js:153 PREPARED state
initMatrix.js:154 previous state:  null
Notifications.js:115 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Map.get (<anonymous>)
    at Notifications.getNoti (webpack://cinny/./src/client/state/Notifications.js?:115)
    at Notifications._setNoti (webpack://cinny/./src/client/state/Notifications.js?:158)
    at eval (webpack://cinny/./src/client/state/Notifications.js?:173)
    at Array.forEach (<anonymous>)
    at Notifications._setNoti (webpack://cinny/./src/client/state/Notifications.js?:172)
    at eval (webpack://cinny/./src/client/state/Notifications.js?:173)
    at Array.forEach (<anonymous>)
    at Notifications._setNoti (webpack://cinny/./src/client/state/Notifications.js?:172)
    at eval (webpack://cinny/./src/client/state/Notifications.js?:173)
logger.js:57 Error decrypting event (id=$wCtJm1QA52Y4jaCYdsRbcjtFSb0weyroYQQ_Cu7iP8M): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: Hz9URH/5xoulbuam2w6n0n7fLf50W7XzCQ680ci3ewQ|mVYCJM8OcnGIkBgtootuIjcmJ4VCtm6xHgpYJLEX0qk]
eval @ logger.js:57
logger.js:57 Error decrypting event (id=$ODOsA927vJM896o2jQxiiqpQFddVKk6i0gCd82KkbaI): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: tjSBFh4BjXDoXMOT7JfVqtYdzujTl91R/XCF+VIgDwk|kr1IMI8Zlrwo7oN2iJman2s6wT526LjKVrtYcVgreD4]
eval @ logger.js:57
logger.js:57 Error decrypting event (id=$E-MvYJW5kzP4ei-LPeWnVtEWzAqPb7ZQrZdnhSwp3H0): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: tjSBFh4BjXDoXMOT7JfVqtYdzujTl91R/XCF+VIgDwk|09kXEECkkrsrKoQQ3yTH6As84QGVCXJ78mxeYX/fAMQ]
eval @ logger.js:57
logger.js:57 Error decrypting event (id=$0wjL8ZMlyJy_Ybyftk5T8Y_x-C1nEedg5-bpHlAb72M): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: LkIijhFMgLWEF9iAqaPXuZFMqgg9nCy/su55osxFUWQ|uWBZVjLdk02kwb7V+rDs2uQkzEw4Uy9bLfF7dJzPGlY]
eval @ logger.js:57
logger.js:57 Error decrypting event (id=$BjGkwNKh2JRdMD0iAz6go6EpZx-mKrcpr2CtQSE_5mA): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: Hz9URH/5xoulbuam2w6n0n7fLf50W7XzCQ680ci3ewQ|2dS62FN0NvRM6oCyMtYTuCoWQm88pioenMTnQBnHvNs]
eval @ logger.js:57
logger.js:57 Error decrypting event (id=$aZEB0PRhpGbZUK9XrVxoZEYrrjvcmWROuWY6GQUL9fs): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: aWXcpNW6NG7v51mjcnvM4Z/4kwZCU+ZbJugxW0Hduzw|7deX/EGMzHSYrtLX9l07Zbqx9F3zTk1PONfQNwp3Gj4]
eval @ logger.js:57
logger.js:59 TURN creds are valid for another 85800100 ms: not fetching new ones.
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/sockjs-client/dist/sockjs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/react-router-dom/esm/react-router-dom.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/react-router/esm/react-router.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/@tippyjs/react/dist/tippy-react.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/tippy.js/dist/tippy.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://cinny/node_modules/sockjs-client/dist/sockjs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
