### ISSUE TITLE
'Pin to sidebar' option for rooms and DMs

### ISSUE THREAD

**Issue by zarp-dev** [ajbura/cinny#106]
#### Is your feature request related to a problem? Please describe.
The way you have implemented spaces is wonderful! 
I have an idea. What if the user can add rooms and DMs to the sidebar.
It would be very nice.
#### Describe the solution you'd like
Add 'Pin to sidebar' option to Rooms and DMs in the Options menu.
![Screenshot 2021-09-19 at 12 28 432](https://user-images.githubusercontent.com/65812041/133922513-6c8c5b0e-6a29-403f-8079-d71add290b78.png)

The selected room or DM will look like this.
![Screenshot 2021-09-19 at 12 40 512](https://user-images.githubusercontent.com/65812041/133922889-1deff051-cab7-41d4-8234-5afabc155f4c.png)

#### Describe alternatives you've considered
Add 'Pin to sidebar' button near 'Options' button
![Screenshot 2021-09-19 at 12 05 442](https://user-images.githubusercontent.com/65812041/133921844-82b5f3fc-35bd-4525-b4a1-8d2f8e7ed4b7.png)

**Comment by vwkd** [comment]
This is essentially pinning favorites. A problem with pinning favorites is that you would need to change them if your favorites change.

Another problem is that it will mix up spaces, rooms, and DMs. You can’t know anymore what you click on just by the location in the UI. Also with just a few spaces and rooms the sidebar is already filled. Adding yet more favorites won’t help. It's all more clutter.

I sense this issue arises out of the wish to navigate faster to your preferred space / room / DM. Why not solve that problem directly? How could we navigate directly where we want to go?

A search modal! See #132.

**Comment by kfiven** [comment]
Sidebar is for spaces only so I am afraid that there's no chance DMs or Rooms will go there. 

Also if it's a problem with navigation, better go with vwkd's alternative.

**Comment by kfiven** [comment]
Closing as it's unlikely to get added.

**Comment by Freeplayg** [comment]
> Another problem is that it will mix up spaces, rooms, and DMs. You can’t know anymore what you click on just by the location in the UI. Also with just a few spaces and rooms the sidebar is already filled. Adding yet more favorites won’t help. It's all more clutter.

That shouldn't be a problem if you're the one that pinning the whatever to the side anyways right? You should know what rooms & spaces you've pinned
