### ISSUE TITLE
Emoji verification can fail to load an display pictures

### ISSUE THREAD

**Issue by Porkepix** [ajbura/cinny#1074]
### Describe the bug

See the joined screenshot, Cinny can be in a situation where the emoji fails to load for the emoji verification.
This may be due to a missing build dependency, though I don't see how that would happen to be the case seeing how it's done.

![Screenshot from 2023-01-13 21-20-12](https://user-images.githubusercontent.com/709500/212413088-210ddacf-af40-451d-aae2-40c9dac7a32d.png)

### Reproduction

Try to do a session verification.

### Expected behavior

The emojis should be displayed

### Platform and versions

```shell
ArchLinux, latest stable release installed from https://aur.archlinux.org/packages/cinny-desktop
```

**Comment by Porkepix** [comment]
The emoji looked like pictures (instead of showing the usual � for a character not found) so I thought about pictures not loading.
However, seeing how emojis are missing in conversations too (with reactions), displaying a white square instead (not the one visible in the screenshot here).
The system do have `noto-fonts-emoji` installed, so I'm guessing this isn't what it's looking for, so maybe some additional dependencies should be requested/checked somewhere?

**Comment by kfiven** [comment]
This is because of twemoji maxcdn going offline. https://github.com/cinnyapp/cinny/pull/1070 is aimed to fix it. So closing as dup.

**Comment by Porkepix** [comment]
@kfiven Naive question though: why not rely onto fonts when those are present?

(And after reading the messages in the PR you linked, I'm quite surprised that until it's merged, every single use of emojis was requesting assets onto a CDN rather relying on local resources…)
