### ISSUE TITLE
Can't install on subdirectory

### ISSUE THREAD

**Issue by Salamandar** [ajbura/cinny#1085]
### Describe the bug

The generated index.html contains absolute paths to `/assets/`, thus breaking installations that are not on the root.

We need `./assets/` instead, just like the versionned index.html.

### Reproduction

Install on a subdir (via a reverse proxy), try to access, and see that the browsers try to access ` https://mydomain.tld/assets/index-144c3825.js` instead of ` https://mydomain.tld/cinny/assets/index-144c3825.js`.

### Expected behavior

relative paths.

### Platform and versions

```shell
Any
```

**Comment by JeiSir** [comment]
https://mydomain.tld/assets/index-144c3825.js

**Comment by Salamandar** [comment]
?
