### ISSUE TITLE
Generate Keys doesn't work

### ISSUE THREAD

**Issue by Vap0r1ze** [ajbura/cinny#1086]
### Describe the bug

I'm using https://app.cinny.in/, when I try to make a cross-signing key (phrased or unphrased) I get an infinite spinner.

The create key method throws "Buffer is not defined", from here: https://github.com/matrix-org/matrix-js-sdk/blob/83563c7a01bbeaf7f83f4b7feccc03647b536e7c/src/crypto/recoverykey.ts#L24

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: chrome 109
3. Cinny version: 2.2.3 (app.cinny.in)
4. Matrix homeserver: catvibers.me
```

**Comment by ghost** [comment]
Exact same problem, but in my case with desktop app.

**Platform and versions**
```
1. OS: Manjaro (Gnome)
2.  Cinny version: 2.2.3-1 (http://aur.archlinux.org/packages/cinny-desktop-bin)
3.  Matrix homeserver: matrix.org and I have tried other ones also.
```
