### ISSUE TITLE
Cinny thinks the security key is incorrect

### ISSUE THREAD

**Issue by q234rty** [ajbura/cinny#1087]
### Describe the bug

After v2.2.3, using the key backup doesn't seem to be possible at all. 

### Reproduction

1. Try to download the key backup in cinny.
2. Paste the security key which is working in all other clients.
3. Observe that cinny reports "Incorrect security key"

### Expected behavior

The keys are downloaded successfully.

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Firefox 109.0
3. Cinny version: 2.2.3
4. Homeserver: envs.net, also tested with matrix.org
```

### Additional context

2.2.2 seems to work perfectly fine.

**Comment by ConnorJC3** [comment]
This also happened to me. Not only does it break verifying from security key, but it also breaks cross-verifying from v2.2.3 (it will ask for your security key and get stuck). I was able to workaround this by running v2.2.2 in Docker locally, and using that to cross-sign my app.cinny.im sessions.

**Comment by Salamandar** [comment]
Hah, i'm not alone !

**Comment by ekallevig** [comment]
same issue here -- used the same security key successfully on other clients but cinny doesn't like it.
