### ISSUE TITLE
Show a picture of the opened space to the left of the header title, if available

### ISSUE THREAD

**Issue by zarp-dev** [ajbura/cinny#109]
#### Is your feature request related to a problem? Please describe.
I suggest showing a picture of the opened space to the left of the title header, if available.

#### Describe the solution you'd like
If the space has a picture, show it:
![Screenshot 2021-09-19 at 15 14 39](https://user-images.githubusercontent.com/65812041/133927405-9222d5fe-f511-443f-82c6-2ff047059c5d.png)

If not, show the default space icon:
![Screenshot 2021-09-19 at 15 16 08](https://user-images.githubusercontent.com/65812041/133927414-1cd954e7-b226-495f-ac52-86c6263d7cee.png)

Also, the house icon should be in the "Home" tab:
![Screenshot 2021-09-19 at 14 20 13](https://user-images.githubusercontent.com/65812041/133927891-7a3901b6-91bf-4f02-bd04-0d379bd18604.png)
:

**Comment by kfiven** [comment]
Closing as it's unlikely to get added.
