### ISSUE TITLE
Show a picture of the opened space in the breadcrumb menu, if available

### ISSUE THREAD

**Issue by zarp-dev** [ajbura/cinny#110]
#### Is your feature request related to a problem? Please describe.
I suggest showing a picture of the opened space in the breadcrumb menu, if available.

#### Describe the solution you'd like
If the space has a picture, show it:
![Screenshot 2021-09-19 at 14 26 022](https://user-images.githubusercontent.com/65812041/133928301-6d744ba3-607e-405a-8b76-a1ea194e160e.png)
If not, show the default space icon:
![Screenshot 2021-09-19 at 14 47 252](https://user-images.githubusercontent.com/65812041/133928416-9626b900-8ede-432a-834c-62898d165ed5.png)
Also, the house icon should be shown if the "Home" tab is shown in the breadcrumb menu

**Comment by kfiven** [comment]
IMO it's not a good idea, breadcrumb menu already have very limited space and adding an icon will make it more congested.

**Comment by kfiven** [comment]
Closing as it's unlikely to get added.
