### ISSUE TITLE
I wonder if it is possible to add a translation function

### ISSUE THREAD

**Issue by Bannyfelt13** [ajbura/cinny#1100]
### Describe the problem

For my group, there are tons of people who need translation to help them understand my post

### Describe the solution you'd like

Add a translation function, it can help users translate

**Comment by kfiven** [comment]
They can use google translate or something like that.

**Comment by williamkray** [comment]
[this sounds like a better usecase for a bot](https://github.com/maubot/translate)

**Comment by LinuxinaBit** [comment]
As well as there being a bot already implemented, a translate function would require sending messages to a 3rd party translation service which is just adding unnecessary dependencies. Not to mention the privacy and security concerns…

**Comment by kfiven** [comment]
Closing as this is out of scope and better alternative such as using a bot exist.
