### ISSUE TITLE
Typing outside of an input box should focus the message field

### ISSUE THREAD

**Issue by blattersturm** [ajbura/cinny#112]
#### Is your feature request related to a problem? Please describe.
As a user, I may navigate between pages using my mouse, and want to start typing immediately.

#### Describe the solution you'd like
Typing without any input box focused should focus the message field and take my input.

#### Describe alternatives you've considered
This is common behavior across IM apps. The alternative would be to automatically focus the input, but this seems to hit #71.

#### Additional context
Other applications behave similarly: even if the message input box is not focused, I can still type messages.

**Comment by kfiven** [comment]
@blattersturm What are your device specifications? OS, touch/non-touch, browser.
