### ISSUE TITLE
Client-side unsubscribe or drop events from chat rooms

### ISSUE THREAD

**Issue by SethFalco** [ajbura/cinny#1131]
### Describe the problem

I use Cinny on my PinePhone which is a weak device. Launching the app takes a very long time and in some instances even stalls/crashes.

My last launch took around 4-5 minutes.

I don't believe this is a bug in Cinny, just a performance issue.

### Describe the solution you'd like

On launch the app has a "warming up" process.

I always get to the "Looks like you have a lot of stuff to heat up!" screen while it continues loading.

I use Matrix extensively and so am in many chat rooms across many spaces. Around 54~ group rooms, and 24~ private rooms. However, on my mobile device I only care about 3-4 private rooms, the rest can be entirely scrapped. I don't need these messages processed, stored, indexed, nor to be notified of them. However, these rooms are important to me on my desktop device!

Is it feasible to get a client-side feature where events from specified chat rooms can be unsubscribed or dropped? Would this improve start-up times and performance of the app for weaker devices?

### Alternatives considered

People in this situation could just have a separate Matrix account to use on for their weaker devices, this would achieve the same thing with much less complexity.

However, this feels a little messy. I think it'd be a bit shoddy to have to negotiate with contacts when to use which account. (Especially as matrix.org has online presence disabled.)

### Additional context

I have not looked at the source code of this project and so don't know how the internals look. I only made the assumption that it would be feasible to have a client-setting to ignore syncing certain chat rooms, even if that setting can't stop the network activity and instead only stops the local processing of those events.

**Comment by tezlm** [comment]
[sliding sync](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) (sync v3) should fix this

**Comment by solarkraft** [comment]
See #1436

**Comment by kfiven** [comment]
Closing as duplicate.
