### ISSUE TITLE
High CPU usages

### ISSUE THREAD

**Issue by ajbura** [ajbura/cinny#115]
**Yin Zhu**
Does anyone else suffer from high cpu use when just idling in a room? I'm on Linux and the WebKit process is using 140% of cpu.

**Salamandar**
Someone talked about CPU usage on Chrome, i can see the same thing in firefox
![CPU1-2021-09-18 22-40-44](https://user-images.githubusercontent.com/32841439/133986152-b85ee712-143f-41bb-a4ea-97ddcca0fc15.png)

**Salamandar**
Like, here I have an Element tab open
and it's like cinny in background
![CPU2-2021-09-18 22-40-44](https://user-images.githubusercontent.com/32841439/133986313-02dc7d7d-8114-425d-9bff-b3b2308ccd1f.png)
Here you can see the CPU usage going up when I open Element, but then it goes back to normal

**Comment by blattersturm** [comment]
A quick Chrome profile shows a few of these while idling (and not seeing any activity in the room I'm idling in) taking 1-3 milliseconds each 'frame':

![image](https://user-images.githubusercontent.com/24576130/133990893-dcb6ec86-393d-4722-86de-aac529a33235.png)

I'm not sure what's triggering these, however, since the room itself hasn't moved noticeably.

The 'Layers' tab in dev tools also shows the main `.room-view` element is a 'slow scroll rect', though I'm not sure if this is related.

**Comment by blattersturm** [comment]
Adding `will-change: transform;` to the `.scrollbar` class (in devtools) seems to improve these slow frames by a lot and removes all 'Slow scroll rects' in the Layers tab at least, but I still see a ~5% CPU usage in Chrome's task manager, and a number of weird slow frames without clear cause anyway.

**Comment by blattersturm** [comment]
Enabling devtools experiments in Chrome found a likely cause:

![image](https://user-images.githubusercontent.com/24576130/133993198-1a7dd059-73c2-4617-848d-07633a27f16e.png)

**Comment by blattersturm** [comment]
Forcibly adding `display: none;` to the .bouncingLoader indeed resolves the high CPU usage for the tab and constant style recalculation.

Interesting to see it be so slow, though (especially when not being drawn at all).

**Comment by ajbura** [comment]
> Forcibly adding `display: none;` to the .bouncingLoader indeed resolves the high CPU usage for the tab, continuous style recalculation as well as rendering frames despite nothing changing.
> 
> Interesting to see it be so slow, though (especially when not being drawn at all, but even when it is).

Thanks for solving the problem. :)

Will include it in next hotfix.
