### ISSUE TITLE
Go to offers upgraded/tombstoned rooms

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#118]
#### Describe the bug
Go to command keeps offering old tombstoned versions of rooms causing duplicates and confusion.

#### To Reproduce
1. Upgrade a #room
2. `>#room`
3. See both #rooms

#### Expected behavior
Hide tombstoned rooms from go to.

#### Additional context
It's practically impossible to even distinguish between old and upgraded rooms so the only solution would be to leave from them. That isn't always ideal if you want to refer to the history of an older room and want to keep it around. They don't seem to be visible in the room listing though so this is a go to specific issue.

**Comment by kfiven** [comment]
It also offers left room until the app is refreshed.

**Comment by kfiven** [comment]
There's no go to command now, so closing this one. Ctrl + k replaced the go to feature.
