### ISSUE TITLE
matrix.to alternative, with user onboarding

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#1188]
### Describe the problem

When I send a matrix.to link, it's super long (matrix.to/#/#blahblahxyz:urllolthisissuperlongfornoreason.zxy) and recommends element by default, and even when element is installed, clicking open in element never works. Cinny is much better for new users.

### Describe the solution you'd like

It would be nice if there was a configurable linking system with a custom page, where you can create a simple invite link that will default to using the cinny instance you host (of course with a little button that says "open in another app" or something).

ex:
#funnysuperduperlonglink:xyzabc123xd.org -> cinny.in/<3/`custom name`/ (this url would be created by a user on the instance), which brings you to a page that lets you get started using cinny, or join if you're logged in on the instance.

### Alternatives considered

matrix.to (lol)

### Additional context

💀💀

**Comment by vijfhoek** [comment]
> Cinny is much better for new users.

While I think I agree, I don't think that's a valid reason to introduce more fragmentation into the Matrix ecosystem. After all, it's just an opinion - some people will prefer other clients. That's the beauty of Matrix, after all

**Comment by viasux** [comment]
> > Cinny is much better for new users.
> 
> While I think I agree, I don't think that's a valid reason to introduce more fragmentation into the Matrix ecosystem. After all, it's just an opinion - some people will prefer other clients. That's the beauty of Matrix, after all

fragmentation isn't a problem if ux is good

**Comment by HonbraDev** [comment]
`matrix.to` links are defined in [the spec](https://spec.matrix.org/v1.6/appendices/#matrixto-navigation), alongside `matrix:`. Issue #778 is about making them work in-app.

**Comment by viasux** [comment]
> `matrix.to` links are defined in [the spec](https://spec.matrix.org/v1.6/appendices/#matrixto-navigation), alongside `matrix:`. Issue #778 is about making them work in-app.

why would a decentralized system create a specification for including a centralized one lol

**Comment by HonbraDev** [comment]
It's not a centralized system? The spec clearly says that clients shouldn't rely on the webserver behind it.

**Comment by kfiven** [comment]
Since the support of URL navigation you can now achieve this like mentioned and we also have options to open the matrix.to link in Cinny in much better shape now. Closing as completed.
