### ISSUE TITLE
Go to should do a wildcard search instead of prefix search

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#119]
#### Is your feature request related to a problem? Please describe.
Sometimes I may write a room name starting from some other word than the first if it's more unique that way (think rooms starting with "The" for one). Cinny currently does not work like that and only does prefix matching.

#### Describe the solution you'd like
Do wildcard matching but order the list of suggestions based on matching criteria.

1. Prefix matches
2. Wildcard matches

This doesn't break the current behavior but instead offers more options.

**Comment by kfiven** [comment]
Similar issue: #121

**Comment by ajbura** [comment]
new search modal (ctrl+k) now do wildcard search. so this also has been implemented
