### ISSUE TITLE
Opening a link directly to https://app.cinny.in/register doesn't work

### ISSUE THREAD

**Issue by aaronraimist** [ajbura/cinny#12]
I get a 404 error. It only seems to work if you click on the Register link from the login page.

<img width="588" src="https://user-images.githubusercontent.com/5855073/127407640-800f57ab-199e-49ee-ad6d-5bf4f75aeb61.png">

**Comment by lukesmurray** [comment]
https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/ might solve your problem

**Comment by ajbura** [comment]
Fixed
