### ISSUE TITLE
Go to could rank up frequently accessed rooms

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#120]
#### Describe the solution you'd like
Go to could like browsers do rank frequently accessed rooms in the suggestion list. This could work with what #119 suggests to have a ranking system to order the results when there are multiple matches based on prefix/wildcard matching and frequency to jump between rooms more efficiently.

**Comment by vwkd** [comment]
This could be part of search. #132

**Comment by ajbura** [comment]
Frequent rooms now appear in search modal (ctrl+k) and we have removed goto cmds from input so technically this is implemented.
