### ISSUE TITLE
Code block isn't styled

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1217]
### Describe the problem

Talking about programming in Cinny is painful.
The code block is "implemented" using a monospace font, and a slightly different background color. There is no "copy to clipboard", or syntax highlighting.

### Describe the solution you'd like

Better looking codeblocks and inline code tags.
Syntax highlighting.

### Alternatives considered

Using Element. It has the proper design for this. It could be copied to Cinny.

**I can try to contribute it, but I'm new to this project. How should I get started?**

**Comment by ajbura** [comment]
duplicate #324
