### ISSUE TITLE
Messages arrive in wrong order

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1218]
### Describe the bug

Messages arrive in wrong order when page first loads.

### Reproduction

1. Open Cinny in browser (maybe on slow connection, but may not be correlated)
2. If you got many new messages in a conversation, they are displayed in wrong order when the conversation is first opened.
3. Switching to another conversation, then back, rearranges them in the correct order.

### Expected behavior

Messages arriving in correct order even on first load.

### Platform and versions

```shell
browser
```

**Comment by notramo** [comment]
@kfiven How did you check that the timeline rewrite solves this issue?

**Comment by kfiven** [comment]
@notramo With your reproduction steps.
