### ISSUE TITLE
Automatically pin top-level spaces

### ISSUE THREAD

**Issue by thibaultamartin** [ajbura/cinny#1223]
### Describe the problem

It can be difficult to see all the communities I joined by glancing at the Spaces bar.

### Describe the solution you'd like

I would like Cinny to show me all the top-level spaces I joined (for example https://matrix.to/#/#community:gnome.org, https://matrix.to/#/#kde-community:kde.org and https://matrix.to/#/#fedora-space:fedoraproject.org) in the Spaces bar.

**Comment by ajbura** [comment]
this has been added in v4.0.0
