### ISSUE TITLE
Placeholders not disappearing in newly upgraded room

### ISSUE THREAD

**Issue by Empty2k12** [ajbura/cinny#124]
#### Describe the bug
![Screen Shot 2021-09-29 at 16 41 41](https://user-images.githubusercontent.com/6954968/135291795-0c302247-cab0-461a-975d-0cbb6c9ff69f.png)

#### To Reproduce
1. Upgrade a room from version 1 to version 6 and then join the new room as a new member. The loading placeholders will never disappear and there's a `Uncaught (in promise) TypeError: res.chunk is undefined` in the console.

#### Expected behavior
Cinny recognizes that the end of the timeline has been reached and stops showing the placeholders.

#### Code

Relevant code-block is https://github.com/ajbura/cinny/blob/2ed4fc9fbfb59e06209397216bac4524f7e41a2e/src/app/organisms/room/RoomViewContent.jsx#L564

#### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: Firefox 92.0 (64-bit)

**Comment by kfiven** [comment]
Hi, I tried to reproduce it, but for me placeholders disappeared after reaching on the top of timeline.

The room I tested on is #hydrogen:matrix.org which recently got upgraded to v9.

**Comment by Empty2k12** [comment]
The room this is happening in is #netcup:msrd0.de. Feel free to reproduce.

**Comment by ajbura** [comment]
Tried to reproduce with account on conduit.rs homeserver and it looks like error is popping up only on conduit based servers.

Tested in room: `#netcup:msrd0.de`

Error in Cinny:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')`

Error in Element:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')`

**Comment by kfiven** [comment]
@ajbura So is it a Cinny issue or Conduit?

**Comment by ajbura** [comment]
It's a conduit issue. @kfiven

**Comment by kfiven** [comment]
Ah, thanks! For reference: https://gitlab.com/famedly/conduit/-/issues/44
