### ISSUE TITLE
"Unable to connect. Please check your input." when connecting to my privare Dendrite instance

### ISSUE THREAD

**Issue by marty1885** [ajbura/cinny#1270]
### Describe the bug

I'm unable to connect to Cinny to my private Dendrite instance. Which I know works with Element and Fluffy Chat. 

Prove that I'm able to use my server with element:
![圖片](https://github.com/cinnyapp/cinny/assets/8792393/95ba178b-9403-44b5-910a-939383a85d7f)

### Reproduction

To reproduce

1. Open Cinny (I tried both Firefox and the desktop app)
2. point the home server to `matrix.clehaxze.tw`
3. Observe the error "Unable to connect. Please check your input."

The following screenshot shows that my matrix server is indeed running.
![圖片](https://github.com/cinnyapp/cinny/assets/8792393/e8440ace-71e0-4a16-88e0-8407fed66bfe)

After some debugging on my own. I find that my server does reply a 200 to Cinny. I don't get why Cinny thinks it's not able to connect.
![圖片](https://github.com/cinnyapp/cinny/assets/8792393/147e0e7f-61ba-448e-8e9d-dfc8d2a96a8d)

Nor I'm able to find any error logs on my dendrite log
![圖片](https://github.com/cinnyapp/cinny/assets/8792393/2cc97695-0fd7-42bd-ab74-77d9dbf1c6da)

### Expected behavior

Cinny able to connect to my private server

### Platform and versions

```shell
OS: Windows 11
Browser: Firefox 114.0.1
Server: dendrite 0.12.0
```

**Comment by ajbura** [comment]
Your homeserver doesn't returns valid base_url.
What it returns:
```
{
  "m.homeserver": {
    "base_url":"matrix.clehaxze.tw:443"
  }
}
```
What it suppose to return:
```
{
  "m.homeserver": {
    "base_url":"https://matrix.clehaxze.tw:443"
  }
}
```
Note: `https://`

In Spec: https://spec.matrix.org/v1.6/client-server-api/#well-known-uri  3.5.1 says if it's not url fail prompt

**Comment by marty1885** [comment]
@ajbura Thanks! I didn't realize Element accepted that ill formed URI. It is fixed after I changed the configuration
