### ISSUE TITLE
Links through spoilers

### ISSUE THREAD

**Issue by edgess73** [ajbura/cinny#1282]
### Describe the bug

I have spoiler, made with markdown. Spoiler has link inside. When I click on spoiler and I have link under my cursor, link opens.

### Reproduction

1. Make spoiler with link. Example: `||https://example.com||`
2. Move cursor to spoiler with link
3. Click

### Platform and versions

```shell
1. OS: Any/Any
2. Firefox (Fennec on android), Vivaldi (both platforms)
3. Cinny version: 2.2.6
4. Homeserver: matrix.vector1.dev
5. Link client (I don't think you need it, but it might help): https://cinny.vector1.dev/
```

**Comment by kfiven** [comment]
This was fixed in #1199 

It will be included in next release. You can test it at https://dev.cinny.in
