### ISSUE TITLE
Override the right click on message context menu

### ISSUE THREAD

**Issue by mdnwvn** [ajbura/cinny#1287]
### Describe the problem

It becomes a bit tedious to need to hover over a message, navigate to the right side of the window, and then select options to open up the menu to delete or view more detailed message information. In addition, because the hover menu appears above a preceding message, it's not difficult to accidentally move the cursor too far and switch the hover context to the wrong message.

### Describe the solution you'd like

Ideally, when right clicking on a message, it should bring up a menu that contains both the quick options we already get when hovering:

* react
* reply
* edit

as well as the options hidden in the *options* menu

* read receipts
* view source
* delete

It could look something like this:
![image](https://github.com/cinnyapp/cinny/assets/130047559/8b3421f1-8f47-4397-8bf4-f7fdf352d06d)

But with the right icons for the given action.

### Alternatives considered

Leave the current right click behavior on messages alone and instead make it more difficult to accidentally hover off of the quick menu for messages.

### Additional context

None required.

**Comment by ajbura** [comment]
duplicate #849
