### ISSUE TITLE
Error logging in: Cannot read property 'm.homeserver' of undefined

### ISSUE THREAD

**Issue by ajayyy** [ajbura/cinny#13]
![image](https://user-images.githubusercontent.com/12688112/127427555-9f8e5f7f-14ba-408b-80c1-a913a1a13eec.png)

When logging on to my homeserver `ajay.app`, it fails and returns the following error:

```
TypeError: Cannot read property 'm.homeserver' of undefined
```

![image](https://user-images.githubusercontent.com/12688112/127427405-1f6c9d59-1529-4ffe-a0b1-29a191c1f05b.png)

Both the client and login requests return 200, and it does successfully determine to poll `matrix.ajay.app` instead of `ajay.app`, so I'm not exactly sure why it would fail.

The response of the client request:

```json
{
    "m.homeserver": {
        "base_url": "https://matrix.ajay.app:443"
    }
}
```

The response of the login request contained correct values with `user_id`, `access_token`, `home_server` and `device_id`.

**Comment by ajayyy** [comment]
Looks like this may be caused by my well-known file not being served with `application/json` because it is served from GitHub pages.

**Comment by ajbura** [comment]
Does response of login request contained `response.well_know['m.homeserver'].base_url`. If not then how your response contain base_url?

**Comment by ajbura** [comment]
Should be fixed after https://github.com/ajbura/cinny/commit/8cf030585f8de9def779af47bbd127455e453799 Can you please check it out?

**Comment by ajayyy** [comment]
Works now, thanks!
