### ISSUE TITLE
bromite pwa issues 

### ISSUE THREAD

**Issue by deltanedas** [ajbura/cinny#1306]
### Describe the bug

first i have only tested cinny on bromite not mull or anything else

a few issues:
- sometimes the message box is frozen and i cant send until changing to another room and back
- sending messages that dont have a trailing newline splits off the first character, something to do with cursor i think
- arrow keys for example from hackers keyboard are no longer handled so its hard to edit typos and such

### Reproduction

for second problem:
1. send a message, it will send the first character then sending again sends the rest
2. send a message with a trailing newline, it will send as-is.

### Expected behavior

should just let you send messages

### Platform and versions

```shell
using dev.cinny.in on bromite 108, android 9
```

**Comment by Silther** [comment]
as bromite is no longer developed I think this issue is not relevant anymore
