### ISSUE TITLE
Joining via address shows empty page

### ISSUE THREAD

**Issue by vallode** [ajbura/cinny#1309]
### Describe the bug

Attempting to join `#helix-community:matrix.org` via the Cinny web client renders an empty page with no indication to the state of the connection (was it a success? was there an error?) or the next steps I can take.

![image](https://github.com/cinnyapp/cinny/assets/18506096/f872d2ac-7902-4547-bdc4-2af7edbf9eaf)

### Reproduction

1. Click the plus on the top left (add rooms/spaces)
2. Join with address and type/paste `#helix-community:matrix.org`
3. Observe empty page with no rooms/information

### Expected behavior

If there was an error with fetching the space information, present it to the user, and ideally present further actions that can be taken.

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Firefox 114.0.2
3. Cinny: v2.2.6
4. Matrix homeserver: matrix.org
```

### Additional context

Upon further experimentation I now understand I just needed to join a room, I think maybe an empty state that prompts you joining a room would be great.

**Comment by kfiven** [comment]
It's empty because you have joined a space and haven't joined any room of that space. So it's not a bug but yeah the space room exploration can definitely be improved and there's already an issue for that #753

**Comment by vallode** [comment]
Closing as issue 753 is more relevant, thanks for pointing that out.
