### ISSUE TITLE
Markdown not rendered

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1310]
### Describe the bug

With the introduction of the new editor, Markdown is not rendered in the main message compose box, despite it's enabled in settings.

When editing a message, it's rendered.

### Reproduction

Go to dev.cinny.in, and write a Markdown message

### Expected behavior

Markdown is rendered, if enabled in settings.

### Platform and versions

```shell
Firefox, Linux
```

### Additional context

dev.cinny.in

**Comment by iambumblehead** [comment]
possibly related https://github.com/cinnyapp/cinny/issues/890

**Comment by notramo** [comment]
It's fixed in the latest nightly with the timeline refactor.
