### ISSUE TITLE
Cinny crashes browser them open emoji panel

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1311]
### Describe the bug

Then im open emoji panel it freezes and appears "Aw, snap" error

### Reproduction

1. Click on emoji button
2. It freezes
3. Aw, snap!

### Expected behavior

Normally opened emoji panel for select a emoji

### Platform and versions

```shell
OS: Android 10
Browser: Chrome 113.0.5672.132
Cinny: Cinny 2.2.6 [doesnm.cc/cinny]
Homeserver: matrix.org
```

### Additional context

I took out the Cinny shortcut to desktop so that when entering there were no frames and it turned out like pwa

**Comment by kfiven** [comment]
Can not reproduce on Android 9 and 13, Chrome v114.0.5735.131

**Comment by ghost** [comment]
My bug reproduces 

https://github.com/cinnyapp/cinny/assets/116358854/6760e4a7-575c-4dc8-b25c-e515b50f0d7c

**Comment by kfiven** [comment]
Closing as per discussion in Matrix room, this seem to be fixed in dev.cinny.in
