### ISSUE TITLE
Search modal

### ISSUE THREAD

**Issue by vwkd** [ajbura/cinny#132]
#### Is your feature request related to a problem? Please describe.

Cinny currently lacks a search. See #90.

But Cinny already has "Goto commands" that allow to go to a space, room or user. #129 proposes to put commands into a command modal. But going somewhere is actually the same thing that a search provides. It makes sense to have "Goto commands" as part of search such that there is one way to go somewhere.

#### Describe the solution you'd like
A search modal which can be evoked using a keyboard shortcut similar Spotlight search on macOS. Another reference could be GitHub's [Command Palette](https://docs.github.com/en/get-started/using-github/github-command-palette) (at time of writing still in Preview).

It can start of with the "Goto commands". With #90 it can then be expanded to include content search, and in the future more advanced searches as new search APIs are added to Matrix.

Note, on mobile there needs to be an UI element somehow that's accessible everywhere because mobile lacks keyboard shortcuts. A button in the main menu (whatever that will be when Cinny gains mobile support) seems best to me since the main menu is the one thing that needs to be accessible everywhere already. It could be right next to the command button for #129.

#### Describe alternatives you've considered
None.

**Comment by ajbura** [comment]
Related #57
