### ISSUE TITLE
threads are a must have 

### ISSUE THREAD

**Issue by seshubonam** [ajbura/cinny#1321]
### Describe the problem

https://github.com/cinnyapp/cinny/issues/257

referring to the previous request, which might have been lost in the issue list. 

Threads works on element and is the main reason i still continue to use element for some conversations. 

would help if cinny implements threads, opens up more possibilities to customise for different communities. 

### Describe the solution you'd like

implement threads like element, since the spec is available in matrix

### Alternatives considered

element

### Additional context

resurfacing a long requested feature

**Comment by kfiven** [comment]
duplicate of #257

**Comment by kfiven** [comment]
Yeah they are must but spec isn't still mature and there are tons of issue on element implementation that's they are experimenting putting it under labs again. https://github.com/vector-im/element-web/labels/A-Threads

**Comment by seshubonam** [comment]
sure thanks for the update
