### ISSUE TITLE
Combine cinny-desktop repo

### ISSUE THREAD

**Issue by HybridEidolon** [ajbura/cinny#1323]
### Describe the problem

It is currently possible but tedious to develop Cinny Desktop concurrently with Cinny itself, e.g. to implement features that would work only on Cinny Desktop using the Tauri API.

### Describe the solution you'd like

Combine the cinny-desktop repo with the cinny repo, allowing both the web version and the desktop version to be built together and for the upstream cinny project to leverage Tauri APIs.

### Additional context

Examples of Tauri-specific features:

- Custom window decorations
- Minimize to system tray
- Global push-to-talk in VOIP calls
- Disabling prompts for JS API access (notifications, etc) since they are always active in a Tauri context
- Multi-window (ala Slack's recent multi-window feature, which is only available on their electron app)

**Comment by kfiven** [comment]
Closing as explained in https://github.com/cinnyapp/cinny/pull/1324#issuecomment-2124649587
