### ISSUE TITLE
Contract long descriptions in "Explore public rooms" dialog

### ISSUE THREAD

**Issue by jivanpal** [ajbura/cinny#1330]
### Describe the problem

When searching for rooms in "Explore public rooms", search results have their entire room description shown. Some rooms have very long descriptions (e.g. `#RussianFightClub:matrix.org` at over 14kB, about 4 pages of text), which must be scrolled through in their entirety in order to see any further search results.

### Describe the solution you'd like

Cap the description of rooms in this view to a few lines of text (e.g. 300 bytes), followed by a "show more/less" button/link. Alternatively, put this button *before* the description as e.g. "show/hide full room description", so that when "show full room description" is clicked, the subsequent "hide full room description" button is in the same place, not many pages of text down.

**Comment by ajbura** [comment]
this has been fixed in v4.0.0
