### ISSUE TITLE
Feature message bubbles rather than text only

### ISSUE THREAD

**Issue by anditosan** [ajbura/cinny#1345]
### Describe the problem

I would love it if Cinny had chat bubbles instead of simply text. This makes it much easier to section out the data and understand who said what. Especially for large rooms.

### Describe the solution you'd like

Use chat bubbles.

**Comment by mobergmann** [comment]
I wouldn't like it if the messages were always displayed in chat bubbles. I would much rather prefer an option that allows the switch to chat bubbles if the user wishes to.

**Comment by tezlm** [comment]
this exists on the dev branch now (https://dev.cinny.in)
