### ISSUE TITLE
Add a way to show the rooms internal ID

### ISSUE THREAD

**Issue by sbug0** [ajbura/cinny#1360]
### Describe the problem

Sometimes you want to know the rooms internal ID (for example when you want to purge a room using the synapse admin API).

### Describe the solution you'd like

Element has a way to show you the room ID, so I would like the same in Cinny

**Comment by kfiven** [comment]
Click any message in room > options > View source and that will have room ID in it.

**Comment by sbug0** [comment]
> Click any message in room > options > View source and that will have room ID in it.

Oh, yeah that will do just fine. Thanks
