### ISSUE TITLE
Feature Request: Close Quick Switcher with Escape

### ISSUE THREAD

**Issue by jtrees** [ajbura/cinny#1371]
### Describe the problem

I'm always frustrated when I open the quick switcher with Ctrl+K, and then try to get back out with the Escape key and it doesn't work.

There is no way that I know of to close it with the keyboard. Instead, I have to grab the mouse and click outside of the switcher.

### Describe the solution you'd like

Pressing Escape closes the switcher.

### Alternatives considered

It could be a different key but Escape just seems to make most sense.

**Comment by kfiven** [comment]
It is already supported. Could you give more details so we can find out why it's not working for you?

**Comment by jtrees** [comment]
Ah, turns out the Vimium add-on was interfering. Thanks for pointing me in the right direction!
