### ISSUE TITLE
Resize Panes

### ISSUE THREAD

**Issue by Anaphylaxis** [ajbura/cinny#1373]
### Describe the problem

Rooms and people panes should be resizable. Makes no sense to have fixed size for these panes, most of it is empty space. I see this issue https://github.com/cinnyapp/cinny/issues/270 and believe the button is not a full implementation of this request, resizing would be much more effective.

### Describe the solution you'd like

Resizable panes on left/right

### Additional context

Could not find any request related to this

**Comment by kfiven** [comment]
We have no plans to have the view manually resizeable. They do change their size on the overall window size automatically though.
