### ISSUE TITLE
does not work on all chromium browsers

### ISSUE THREAD

**Issue by Silther** [ajbura/cinny#1374]
### Describe the bug

does not work on mobile browsers like cromite or bromite

### Reproduction

1. use bromite or cromite
2. login
3. the message "heating up" is shown without a change

### Expected behavior

should work an all browsers

### Platform and versions

```shell
1. Android 13
2. Cromite 115
3. Cinny Web
4. matrix.org
```

**Comment by kfiven** [comment]
On Bromite you need to enable JavaScript and JavaScript JIT.

Then relogin and it will work.

**Comment by Silther** [comment]
oh thanks,
it would be nice if you could show a help message if it's loading to long
