### ISSUE TITLE
Sidebar space click opening recent room on mobile

### ISSUE THREAD

**Issue by Silther** [ajbura/cinny#1376]
### Describe the bug

if you click on a space or home on the sidebar it will open the first chat/room on mobile browsers, which is quite annoying because then you always have to click back firs to see the overview

### Reproduction

1. click on a space pinned to the sidebar
2. last opened chat/room from that space will open

### Expected behavior

the overview of all spaces/rooms in the space should be displayed, which you get when you leave the current room via the back button.

### Platform and versions

```shell
1. Android 13
2. Mobile Browser (Firefox)
3. Cinny Web
4. matrix.org
```

### Additional context

https://github.com/cinnyapp/cinny/assets/97352673/9b2a8bd7-edb4-428e-93f7-e7f408054af3

**Comment by ajbura** [comment]
this has been fixed in v4.0.0
