### ISSUE TITLE
Cannot login to beeper.com homeserver

### ISSUE THREAD

**Issue by MFAshby** [ajbura/cinny#1384]
### Describe the bug

Cannot login to beeper.com homeserver with cinny

![image](https://github.com/cinnyapp/cinny/assets/1760515/f6735c0b-eebc-4d75-aa19-0b375db61205)

### Reproduction

* go to app.cinny.in
* set homeserver to `beeper.com`

### Expected behavior

expected: login is available

### Platform and versions

```shell
1. OS: linux
2. Browser: firefox
3. Cinny version: v2.2.6
4. Matrix homeserver: beeper.com
```

### Additional context

* I noticed in browser tools that a POST request made to https://matrix.beeper.com/_matrix/client/r0/register fails with 501 (not implemented) error code. This makes sense since registration on beeper.com homeserver is not enabled. I don't know if this complies with the matrix [spec](https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3register) so I'll also ask beeper support.
* same homeserver works OK in app.element.io

**Comment by ajbura** [comment]
As a workaround we can password login by typing entire mxid in username field
