### ISSUE TITLE
Explore public rooms "View more" option just loads the first set of public rooms again

### ISSUE THREAD

**Issue by LiamPerson** [ajbura/cinny#1387]
### Describe the bug

When I open the "Explore public rooms" modal and scroll down to the bottom where it says "View more", it just loads the same list of servers that have already been loaded.

![image](https://github.com/cinnyapp/cinny/assets/34695601/9909fd01-4431-43b5-9e9e-c6b0bc0d2ce4)

### Reproduction

1. Load Cinny
2. In "Home" press the + icon
3. Select "Explore public rooms"
4. Scroll all the way to the bottom of the list
5. Click "View more"

### Expected behavior

I expect that more servers with less members should show.

Example of what happens if I click currently:
![image](https://github.com/cinnyapp/cinny/assets/34695601/e5b37ab7-1c79-4e7d-9627-eb0b3670a9db)

![image](https://github.com/cinnyapp/cinny/assets/34695601/aa76bba5-3b97-4159-86ed-aa9772ab5f85)

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Brave 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
3. Cinny: (app.cinny.in)
4. Matrix homeserver: matrix.org
```

**Comment by ajbura** [comment]
this has been fixed in v4.0.0
