### ISSUE TITLE
No :gasp: emoji smart selection

### ISSUE THREAD

**Issue by LiamPerson** [ajbura/cinny#1388]
### Describe the bug

Smart select (or whatever it is called) at the bottom of the text box does not have an entry for :gasp:.

![image](https://github.com/cinnyapp/cinny/assets/34695601/145fc038-7542-41c9-87c8-7c42ca191e31)

Example of smart select with an emoji that works
![image](https://github.com/cinnyapp/cinny/assets/34695601/f41e2805-3f05-48c7-800d-054adb7cef1e)

### Reproduction

1. Go to the chat anywhere
2. Type :gasp
3. Observe smart select having no options

### Expected behavior

Have :gasp: appear with the emoji in the smart select list below the the text input as :gun: has.

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Brave 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
3. Cinny: (app.cinny.in)
4. Matrix homeserver: matrix.org
```

### Additional context

There is probably quite a few emojis that are lacking here. I only tested the gasp emoji

**Comment by kfiven** [comment]
Does :gasp: emoji actually exist?

**Comment by LiamPerson** [comment]
![image](https://github.com/cinnyapp/cinny/assets/34695601/ca05d5b6-22bc-48e8-ac4e-8f5604a66d07)

@kfiven

**Comment by kfiven** [comment]
That's :face_with_open_eyes_and_hand_over_mouth:

**Comment by LiamPerson** [comment]
Ah, I see now that Cinny just converts :gasp: to :face_with_open_eyes_and_hand_over_mouth: when I send :gasp:... Perhaps I should open another feature request for aliases to appear in that smart selection.
