### ISSUE TITLE
After editing a message by pressing `UP`, browser should automatically refocus text input

### ISSUE THREAD

**Issue by LiamPerson** [ajbura/cinny#1389]
### Describe the problem

When I edit a message (using the `UP` arrow key), then finish editing (by pressing `Enter`), my browser does not focus any inputs, leaving me to accidentally call obscure hotkeys in my browser.

### Describe the solution you'd like

After I edit a message using keyboard shortcuts (e.g: pressing `UP`, and then pressing enter) my browser should automatically refocus the main input (being "Send a message...").

![image](https://github.com/cinnyapp/cinny/assets/34695601/681dcaa7-d475-4603-bb87-84cbe4bd3dca)

> Pressing `UP`

![image](https://github.com/cinnyapp/cinny/assets/34695601/5fffba08-3936-42ff-b1f6-8c15b504d769)

All is good so far...
Now when I press `Enter`, you will notice nothing is focused anymore. Ideally, it should refocus to the input with the arrow pointing to it in the below image:

![image](https://github.com/cinnyapp/cinny/assets/34695601/737ad23a-7f26-4bce-8205-576fdeb1705b)

**Comment by N-R-K** [comment]
> Ideally, it should refocus to the input

This seems to be what discord does as well for reference.

(Also the `UP` arrow binding doesn't seem to be working at all on `dev` version anymore).

**Comment by notramo** [comment]
This is fixed by completely removing the message editing feature on latest nightly build.

**Comment by ajbura** [comment]
https://github.com/cinnyapp/cinny/pull/1447 handled it

**Comment by N-R-K** [comment]
On current `dev`, UP is working again. ~~But it doesn't refocus on the input box after editing.~~ Actually nevermind, it does. But no cursor seems to appear on the input box, which is what had me confused.
