### ISSUE TITLE
Have emoji aliases appear in smart selection

### ISSUE THREAD

**Issue by LiamPerson** [ajbura/cinny#1396]
### Describe the problem

Smart select (or whatever it is called) at the bottom of the text box does not have an entry for :gasp:. This is because :gasp: is actually an alias for :face_with_open_eyes_and_hand_over_mouth: as mentioned in issue #1388 

![image](https://github.com/cinnyapp/cinny/assets/34695601/6eac8bc0-c49f-47ed-bace-33046d6038f0)

### Describe the solution you'd like

It would be good to have the aliases show in the smart selection screen as :gun: does:

![image](https://github.com/cinnyapp/cinny/assets/34695601/bf59686d-9bc3-4f78-947d-6cb777e1540d)

Poorly illustrated example:

![image](https://github.com/cinnyapp/cinny/assets/34695601/fbae365f-1fb0-4da1-80bd-a6e9156846a9)

**Comment by kfiven** [comment]
Probably problem of the library we use for the short code. We do have a gasp emoji but it's named different. So it's something not fixable on cinny side.
