### ISSUE TITLE
Command detection removes message

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1434]
### Describe the bug

When i send a message beginning with a slash Cinny takes it as a command, this is okay.
However, when it's a long message and it's not a command, I lose the whole message.
This is very annoying when sending long messages.

### Reproduction

1. Go to a chat
2. write a message beginning with /
3. watch it all drain into the void

### Expected behavior

I would like it to leave the message in tact or add a button saying "Nein, this is actually what I want!! But Thanks client I know you're just trying to help"

### Platform and versions

```shell
Cinny version: v2.2.6
rest is irrelevant
```

**Comment by cloudrac3r** [comment]
![Screenshot of SchildiChat Desktop's command warning popup](https://github.com/cinnyapp/cinny/assets/28467304/8d7842cc-8b97-4fb7-9e19-6d1edeb1fe43)

Just noting that SchildiChat Desktop (and probably Element, which it forked from) handles this in an extremely good way. In my view, this is the best possible way to do it. It keeps the chat input, warns you about a potentially mispelled command, and still allows you to send anyway.
