### ISSUE TITLE
Code block handling

### ISSUE THREAD

**Issue by tezlm** [ajbura/cinny#1452]
### Describe the problem

- showing line numbers (with `user-select: none`) would be nice
- markdown fenced code blocks don't seem to work
- there's no way to change the code block's language in the rich text editor
- the editor uses enter to send + tab as navigation (instead of a literal tab) while in a code block

### Describe the solution you'd like

add these things

**Comment by williamkray** [comment]
not sure if it's worth it, but this issue could effectively be expanded to a feature request to "support multi-line markdown" with details about how to render codeblocks, as the current markdown implementation is limited only to in-line markdown formatting.

**Comment by ashkitten** [comment]
i run into this deficiency on a regular basis and frustratingly have to go into element to send messages

**Comment by neptuwunium** [comment]
Additional broken markdown features: Block quotes (`> `), lists, headings. These features are supported by the WYSIWYG but markdown is not processed.

**Comment by K900** [comment]
Pretty sure this regressed in 3.1.0.

**Comment by ajbura** [comment]
> Pretty sure this regressed in 3.1.0.

@K900 fix https://github.com/cinnyapp/cinny/pull/1524 in 3.2.0. Let us know if there is still any issue?
