### ISSUE TITLE
Rooms can open subspaces instead top level space

### ISSUE THREAD

**Issue by tezlm** [ajbura/cinny#1465]
### Describe the bug

Clicking a notification, using room search, or a room link will open the space the room is in instead of the top level space.

### Reproduction

1. Create a space
2. Create a subspace in that space
3. Create a room in the subspace
4. Use the switcher to view the room
5. Observe that the room list shows the subspace instead of space 

### Expected behavior

It should open the top level space.

### Platform and versions

```shell
1. OS: NixOS unstable
2. Firefox 118.0.1 (64 bit)
3. Cinny version: 144cf7136887e2a31522511d42c3065ba17ade58 (dev.cinny.in)
4. Matrix homeserver: Conduit 0.7.0-alpha (celery.eu.org)
```

**Comment by ajbura** [comment]
this has been added in v4.0.0
