### ISSUE TITLE
Login fails with TypeError: a.well_known is undefined

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#15]
**Describe the bug**
Immediately after `https://home.server/_matrix/client/r0/login` returns this error will be displayed and no further requests will be made.

**To Reproduce**
Login to HS with delegation. Might be specific to some configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/106598/127437566-43ffbcb8-cee9-418f-8938-3597f8914631.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 89

**Comment by ajayyy** [comment]
https://github.com/ajbura/cinny/issues/13

**Comment by ajayyy** [comment]
Related https://github.com/ajbura/cinny/issues/13

**Comment by hifi** [comment]
This has been fixed on app.cinny.in but not pushed to master I believe.

**Comment by ajbura** [comment]
Fixed  https://github.com/ajbura/cinny/commit/8cf030585f8de9def779af47bbd127455e453799
