### ISSUE TITLE
Add more whitespace between categories

### ISSUE THREAD

**Issue by thibaultamartin** [ajbura/cinny#1509]
### Describe the problem

When browsing the rooms in a Space that has been categorised, the categories are very close to each other.

### Describe the solution you'd like

Adding a bit of whitespace between categories would make the UI much more readable to me.

Discord does this, and it makes the categories easier to see at a glance

<img width="238" alt="Screenshot 2023-10-27 at 10 35 59" src="https://github.com/cinnyapp/cinny/assets/1688309/08965a30-c54d-43d0-8bed-43697ac28b20">

**Comment by ajbura** [comment]
v4 has added plenty of spaces between categories. can we confirm if it is good enough?

**Comment by thibaultamartin** [comment]
Not entirely sure whether you're asking my opinion or not, but if so would you mind pasting a screenshot :) ?

**Comment by ajbura** [comment]
<img width="259" alt="image" src="https://github.com/user-attachments/assets/b9532f4d-aab5-4787-89e5-10de97e6704b">

**Comment by thibaultamartin** [comment]
Looks pretty good to me!

**Comment by ajbura** [comment]
Thanks.
