### ISSUE TITLE
HTML dump appears after custom emojis

### ISSUE THREAD

**Issue by GamePlayer-8** [ajbura/cinny#1516]
### Describe the bug

Every time I type my custom emoji, there's a HTML dump after it like:
```html
wire" title="nomwire" height="32">
```

Visual look:
![image](https://github.com/cinnyapp/cinny/assets/115881539/9cb54a16-fde5-4b6b-96b1-25888019cd13)

It doesn't matter what custom emoji I type. Removing the dump manually doesn't make it disappear from other clients / servers / users's view.

### Reproduction

1. Type a custom emoji into a chat.
2. See a HTML dump after it.

### Expected behavior

I expected Cinny to not show HTML dump after emoji.

### Platform and versions

```shell
1. Artix Linux Rolling
2. LibreWolf Firefox `115.0.2-2`
3. Cinny `v3.1.0` / `app.cinny.in`
4. Matrix server `matrix.catgirl.cloud`
```

**Comment by ajbura** [comment]
Fixed in a2cbe797875ca96394c5af1e69093c32b169eff0 and a98903a85b81d5d799bb65dee9713499ea0ac029 

Until the next release a good workaround can be to turn off markdown in editor
