### ISSUE TITLE
change Twitter shields badge  to new logo 𝕏

### ISSUE THREAD

**Issue by BandhiyaHardik** [ajbura/cinny#1517]
### Describe the bug

In README.md the Twitter shields badge is old.

Twitter is now known as 𝕏.

### Reproduction

1. Go to <a href='https://github.com/cinnyapp/cinny'>cinny repository</a>
2. Look at the shields badge of Twitter.

### Expected behavior

![image](https://github.com/cinnyapp/cinny/assets/110784317/3209ebab-c678-4017-bd99-8e747b417eae)

### Platform and versions

```shell
-
```

**Comment by kfiven** [comment]
I actually like the previous logo. Twitter (name and the logo) still is more recognisable than the new one. So as long as that's the case we should keep it.

**Comment by BandhiyaHardik** [comment]
@kfiven  then should i close this issue and PR ? or any other suggestions?
