### ISSUE TITLE
leaving spaces

### ISSUE THREAD

**Issue by deltanedas** [ajbura/cinny#152]
#### Is your feature request related to a problem? Please describe.
I'm always frustrated when I try to make a test space to test stuff then I try to leave it so i can join again but i cant leave it

#### Describe the solution you'd like
Having the context menu for rooms also be available for spaces, with pinning pinning inside it

#### Describe alternatives you've considered
alt f4 to leave space

**Comment by vwkd** [comment]
All of these meta actions like creating / renaming/ removing / changing hierarchy of spaces as well as creating / renaming / leaving rooms could be solved using commands (#129).

**Comment by deltanedas** [comment]
if you can join a room using the ui, why should a command be needed to leave it?
