### ISSUE TITLE
Show channel topic next to the channel name

### ISSUE THREAD

**Issue by Ravencentric** [ajbura/cinny#1523]
### Describe the problem

Cinny already allows you to set channel topics which you can see here:
![image](https://github.com/cinnyapp/cinny/assets/78981416/a116ca09-7986-4362-9e1d-b1395b4ba8ff)

But you cannot see it without clicking the dropdown
![image](https://github.com/cinnyapp/cinny/assets/78981416/7235cb37-b0b5-41ea-ae2c-45bdd71fde9b)

### Describe the solution you'd like

Show the channel topic next to the channel name, something similar to this:
![image](https://github.com/cinnyapp/cinny/assets/78981416/27efa985-2446-44e5-ad33-a27d665704ee)

**Comment by kfiven** [comment]
It shows now.
