### ISSUE TITLE
Clicking on libnotify notification launches second instance of cinny

### ISSUE THREAD

**Issue by shtrophic** [ajbura/cinny#1532]
### Describe the bug

I am having this issue where clicking on a notification spawns another instance of cinny-desktop instead of opening up the one present, which is minimized to tray.

On Gnome 45.

### Expected behavior

Open up the existing cinny instance

### Platform and versions

```shell
Linux, Desktop version 3.1.0, self-hosted synapse
```

**Comment by kfiven** [comment]
Duplicate of https://github.com/cinnyapp/cinny-desktop/issues/210
