### ISSUE TITLE
Higher contrast

### ISSUE THREAD

**Issue by Silther** [ajbura/cinny#1534]
### Describe the problem

with the upgrade to version 3.0 the contrast in the sidebar was lowered.

![image](https://github.com/cinnyapp/cinny/assets/97352673/e7dd4353-8115-42df-b4df-5f36d83bdbd7)

### Describe the solution you'd like

Please restore the old colors for better visibility or add it as an alternative theme.

**Comment by kfiven** [comment]
Seems to be better in v4.

**Comment by Silther** [comment]
thanks
