### ISSUE TITLE
Show all commands when typing "/"

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#157]
#### Is your feature request related to a problem? Please describe.
Kind of annoying that I can't view all the commands available in Cinny. 

#### Describe the solution you'd like
Pressing "/" (maybe also a tab) can give a pop up with a list of commands

#### Describe alternatives you've considered
Add available commands in the command button

**Comment by vwkd** [comment]
Would be solved by #129.

**Comment by ajbura** [comment]
Done in 88a988d876bc28e9a433cc10138695b4e87d8fc6
