### ISSUE TITLE
Show number of unread messages

### ISSUE THREAD

**Issue by free-electrician** [ajbura/cinny#1577]
### Describe the problem

The number of unread messages in active rooms can quickly surpass the 99 mark. After that it seems to be impossible to tell if there are 100 or 1000 unread messages. In order to decide if it is feasible to catch up on the backlog it would be good to know the exact number of unread messages.

### Describe the solution you'd like

Adding an option to truncate the number in the unread badge after n digits

### Alternatives considered

Adding a tooltip with the exact number on mouse over

**Comment by ajbura** [comment]
this has been fixed in v4.0.0
