### ISSUE TITLE
Support for Page Navigation keybinds

### ISSUE THREAD

**Issue by soupglasses** [ajbura/cinny#158]
#### Is your feature request related to a problem? Please describe.
Webbrowsers and Electron applications have support for ALT+Left and ALT+Right keybinds for navigating backwards and forwards between your recently viewed pages. I'd like to see this supported by Cinny as its a nice feature for quality of life.

#### Describe the solution you'd like
A solution, either trough modifying the browsers history to link to rooms when switching to them, letting the browser use its default keybinds. Or one could try to hook into the keybinds themselves and add the behavior trough javascript.

#### Describe alternatives you've considered
Manually clicking around for the 3~ conversations i usually follow. But this is tedious, especially when they are in different spaces and dms. Usually requiring several mouse clicks around. While with ALT+Left and ALT+Right you could easily flip between the recently viewed rooms.

#### Additional context
I know other clients like Element support this trough their web version already.

**Comment by samueldr** [comment]
A good way to get this "for free" is to mindfully use the browser history for (part of) the application state. E.g. using a router which hooks into the history to select where in the app you are.

I'm only just getting familiar with Cinny's codebase, and I see it uses `react-router`, at least to direct the user to the right part of the application for auth/app.

@ajbura was it your intention to use `react-router` to "route" the application to e.g. the appropriate room at some point?

**Comment by ajbura** [comment]
@samueldr yes but now I feel using custom history api is good choice for it  rather than using react-router. so I am going to remove react-router soon and would not advise to build something else on it.

**Comment by samueldr** [comment]
I'm glad I asked!

**Comment by ajbura** [comment]
Related #70, #170

**Comment by kfiven** [comment]
Given the implementation of Url navigation, I think this is now resolved and you can navigate back and forth now.
