### ISSUE TITLE
Flatpak official?

### ISSUE THREAD

**Issue by erebion** [ajbura/cinny#1585]
### Describe the problem

It is unclear whether the Flatpak package is official.

### Describe the solution you'd like

Clarification on whether the Flatpak issue is offical.

### Additional context

If the Flatpak package is official, please mark it as such on https://flathub.org/apps/in.cinny.Cinny :)

**Comment by sycam0r-e** [comment]
How is that unclear?! Flatpaks are instaled on non-mobile platforms. Simply checking the `cinny-desktop` repo would show you that that flathub link is literally in that repo's README.

**Comment by erebion** [comment]
I cannot see this in the README. Mainly because it is not mentioned.

On Flathub it is not marked as official.

So before I install this on my phone I would like to know where it is coming from and whether it is the real software.

**Comment by sycam0r-e** [comment]
I told you clearly that that link _is_ mentioned in that repo's README which I mentioned. You are stealing time from the devs and everyone involved here. If you cannot read properly then installing purportedly non-official software is the least of your problems.

**Comment by erebion** [comment]
My suggestion to mark the Flathub package as official did not change by reading a meaningless comment. It'd still be great to have this marked as what it is.

**Comment by erebion** [comment]
Do you still want to divert from what this is about?

Seems a good way to get people away from projects, I was even considering looking into translations and adding some.

**Comment by erebion** [comment]
I just came here from Flathub, following a link, being unsure whether said Flatpak is actually official. A small note would suffice and I'd even add it to the README.md file myself via PR, if desired.

Just from Flathub linking here it is not clear whether this is an official Flatpak or packagee by the community.

The website just links to this repo without any further info as to what its relations to that website are, thus it is not clear.

**Comment by lionirdeadman** [comment]
To mark it as official, instead of linking in the README or such, it would be good to follow [Flathub documentation](https://docs.flathub.org/docs/for-app-authors/verification)

It shouldn't be very hard to modify https://github.com/cinnyapp/cinny-site to include this file.

**Comment by kfiven** [comment]
https://github.com/cinnyapp/cinny-desktop already mentioned about flatpak, now flatpak is also verified. 
<img width="230" alt="image" src="https://github.com/user-attachments/assets/8d978d91-d4db-4532-ac30-57bedf91e2eb">
