### ISSUE TITLE
Mark All As Read option for Home/People views

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#1586]
### Describe the problem

while Spaces in the left panel have a right-click context menu that includes "mark all as read", Home and People do not.

Other issues related to messages being marked as read in a more persistent manner mean that when I reload Cinny, I have dozens of PMs and rooms that I need to mark as read... many of those rooms are tombstoned and removed from their old space, meaning they show up in the Home section. I don't have an easy way to mark them all as read.

### Describe the solution you'd like

ideally, fix _all_ these problems, but this issue is really just about adding the feature to mark Home and People rooms as read easily as a workaround to the above issues.

### Alternatives considered

Tombstoned rooms should not appear in the interface as a separate room from its replacement, it should be hidden from normal navigation and made accessible from the room options. This eliminates the need for marking these rooms as read.

Messages marked as read should _stay read_, but I believe this is an issue with how the protocol handles read receipts.

**Comment by ajbura** [comment]
this has been fixed in v4.0.0
