### ISSUE TITLE
Feature Request: Commands in the client

### ISSUE THREAD

**Issue by farribeiro** [ajbura/cinny#16]
**Is your feature request related to a problem? Please describe.**
Commands for operation of HS, like join, part, invite, ban, kick and others.

**Describe the solution you'd like**
Implements matrix HS commands in the client. Its essentials for non listed rooms or not easy to find in directory list 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ajbura** [comment]
Done with https://github.com/ajbura/cinny/commit/b552e2cda8e372414268a731fee4f4c9fc97cf88 Although it doesn't include all the commands but remaining will be added when there will be interface components for them.
