### ISSUE TITLE
Cinny doesn't recieve client login verification requests

### ISSUE THREAD

**Issue by Tcll** [ajbura/cinny#1607]
### Describe the bug

Cinny gives no response when a verification request is sent.

### Reproduction

1: send a device verification request:

![](https://i.stack.imgur.com/dMSOD.png)

2: Cinny never gives a notification of the recieved request:

![](https://i.stack.imgur.com/ZoHEr.png)

![](https://i.stack.imgur.com/dFf9z.png)

### Expected behavior

I should recieve a verification request notification at the bottom left that I can click on to start the verification with the other client.

### Platform and versions

```shell
1. OS: Linux ws2 5.19.10-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Sep 2022 14:46:30 +0000 x86_64 GNU/Linux
2. Browser: LibreWolf 102.0
3. Cinny Version: latest from https://app.cinny.in
4. Matrix homeserver: matrix.org
```

**Comment by Tcll** [comment]
any chance at this getting fixed??

**Comment by kfiven** [comment]
Just tested it with Cinny <=> Element and Cinny <=> Fluffychat and Emoji verification is working for me. Seems something off with Nheko.

**Comment by Tcll** [comment]
Just wanted to update, I was able to verify Cinny through Nheko, Cinny actually showed the expected emoji verification now. :)

Not sure if that was you guys who fixed anything, or if that was me removing everything from /usr and isolating (adding missing libs to) my appimages...
Too much has happened on my end to really be sure, including fixes to LibreWolf

**Comment by kfiven** [comment]
Okay, thanks for the update. Gonna close it now as it's working.
