### ISSUE TITLE
grid view of multiple rooms like hydrogen-web client

### ISSUE THREAD

**Issue by seshubonam** [ajbura/cinny#1612]
### Describe the problem

Is it possible to generate a grid view like the following within cinny forked client. 
<img width="1440" alt="Screenshot 2023-12-26 at 10 09 24 PM" src="https://github.com/cinnyapp/cinny/assets/1757478/0c11fe4a-7a98-4ec0-a966-b2547fda1784">

### Describe the solution you'd like

can you give a heads up on such an implementation.

**Comment by kfiven** [comment]
I don't think cinny is designed to support use cases like this.
