### ISSUE TITLE
hide link preview card for matrix.to

### ISSUE THREAD

**Issue by camelCaseNick** [ajbura/cinny#1626]
### Describe the problem

When .content.body contains an `<a data-mention-type="user" href="https:\/\/matrix.to/#/@…">` this is understood as message containing a URL and thus gets a preview card.

### Describe the solution you'd like

From a user perspective who doesn't understand how mentioning works, I would expect to be confused that mentioning someone creates a link. Thus, I would prefer this preview card to not be shown.

**Comment by bengaywins** [comment]
Hah this was what I was coming to report about, but I don't think hiding for _all_ `matrix.to` is the right choice here. I think hiding them for mentions of _users_ should be hidden, but not necessarily anything else.
