### ISSUE TITLE
Infinite load when trying to perform token-based registration

### ISSUE THREAD

**Issue by OdinGitDat** [ajbura/cinny#1629]
### Describe the bug

I'm unable to complete registration on my homeserver that has token-based registration enabled. Loading indicator appears and hangs after that.

### Platform and versions

```shell
Firefox & Chrome
```

**Comment by ajbura** [comment]
Are you on app.cinny.in ? it does not support registration with token yet. dev.cinny.in dev build has it

**Comment by OdinGitDat** [comment]
Oh thanks!
