### ISSUE TITLE
Allow users to create and manage Spaces

### ISSUE THREAD

**Issue by du82** [ajbura/cinny#163]
Allowing users to create spaces would help keep up with feature parity on Element and other clients, and reduce dependancy on other clients so I can entirely use Cinny.

**Comment by samueldr** [comment]
See also:

 - https://github.com/ajbura/cinny/issues/52#issuecomment-915116197
 - https://github.com/ajbura/cinny/issues/152

**Comment by ketanmujumdar** [comment]
Is this already supported?

**Comment by ajbura** [comment]
Yes. You can see manage space option in plus icon next to space name
