### ISSUE TITLE
Cinny desktop app is reported as Cinny web in the session list

### ISSUE THREAD

**Issue by alexlehm** [ajbura/cinny#1644]
### Describe the bug

When I log in with the Cinny desktop client in Windows and the Cinny web client, both are identified as Cinny Web in the session list

### Reproduction

Log into an account with Cinny Desktop Windows
Go to another Matrix client with the same account, e.g. the Cinny Web client
show the active sessions

![image](https://github.com/cinnyapp/cinny/assets/156144/f9444319-805f-4dac-94e9-18109015ad2a)

### Expected behavior

The Desktop client should show a name that is different from the Web client, otherwise its confusing

### Platform and versions

```shell
Windows
Cinny Desktop 3.2.0
matrix.org homeserver
```

**Comment by kfiven** [comment]
Duplicate of https://github.com/cinnyapp/cinny-desktop/issues/64
