### ISSUE TITLE
Decrypt chat history in new session

### ISSUE THREAD

**Issue by abluemeI** [ajbura/cinny#1656]
### Describe the bug

When I log in to Cinny (web) after previously using Element, the message history of my chats fails to be decrypted even after entering the security key. If I type a few messages, log out, log in again, and open the chat, the "new" messages are again still encrypted (even after verifying the session).

![image](https://github.com/cinnyapp/cinny/assets/24776133/a3c29deb-0aee-484f-91d5-fef88916c1e5)

### Reproduction

1. Log in with my Matrix account
2. Verify session with my security key
3. Open an encrypted chat

### Expected behavior

I expect to see the previous messages of a chat that I was part of before switching to Cinny.

### Platform and versions

```shell
1. OS: Arch Linux
2. Browser: Firefox 124.0.1 (64-bit)
3. Cinny: v3.2.0 (app.cinny.in)
4. Homeserver: matrix.org
```

### Additional context

I have tried the same thing in other clients (Fluffychat, Element), where the issue did not occur.

**Comment by kfiven** [comment]
Duplicate of #792
