### ISSUE TITLE
Key based account registration

### ISSUE THREAD

**Issue by Sleuth56** [ajbura/cinny#167]
#### Is your feature request related to a problem? Please describe.
I'm waiting for a web based client to support key based registration. I have several friends that I would like to get on matrix and this is a requirement for me to do that.

#### Describe the solution you'd like
When a server isn't accepting open registration a field to enter a pre-shared key should be presented along with the usual username, password, and email fields. Some text above the key field could say. "This server doesn't allow open registration. If you have a registration key from an admin please enter it here." Once a correct key is entered the account should be created as usual.

**Comment by marek-lach** [comment]
[This](https://github.com/zeratax/matrix-registration) may be of help as a reference, when implementing the feature of `token-based registration` into _Cinny_.

**Comment by kfiven** [comment]
Ref: https://github.com/matrix-org/matrix-spec-proposals/pull/3231 and https://github.com/matrix-org/matrix-react-sdk/pull/7275

**Comment by heylix** [comment]
@ajbura **please** implement _MSC3231 "Token authenticated registration"_ as Element-Web (https://github.com/vector-im/element-web/issues/18931) and Element-Android already have it (https://github.com/matrix-org/matrix-react-sdk/pull/7275) and Cinny is one of the three clients recommended on the [Matrix.org clients page](https://matrix.org/ecosystem/clients/) and it's [in the specification](https://spec.matrix.org/v1.7/client-server-api/#token-authenticated-registration), not only a proposal anymore.

If you have done it, you can make sure it is shown on https://matrix-org.github.io/canitmatrix/clients/cinny/.
