### ISSUE TITLE
Remember people pane state

### ISSUE THREAD

**Issue by wezm** [ajbura/cinny#168]
Cinny defaults to opening with the People pane on the right open. I have to close it each time I load Cinny. It would be great if the open/closed state was remembered across page loads (so that it would remain closed for me).

**Comment by samueldr** [comment]
This has just been done!

 - https://github.com/ajbura/cinny/commit/cb6e71e5445e38e1248f957bd3564e27a200b384

AFAIUI you can try the `dev` branch at https://dev.cinny.in/, or you can wait until the next stable release :).

**Comment by wezm** [comment]
Brilliant! Thanks
