### ISSUE TITLE
An option to add favourite rooms into a separate place in side-bar. 

### ISSUE THREAD

**Issue by ARBoyGo** [ajbura/cinny#1682]
### Describe the problem

Currently, when we are in a space, there are often multiple spaces below it, Under it multiple rooms. It's hard to find the room we actually need. It would be nice to have them separate. 

### Describe the solution you'd like

I would like to see a separate menu/space-like called favourites, Which includes all the rooms we use most of the time. 
I saw this on element. 
![image](https://github.com/cinnyapp/cinny/assets/69381592/a0bdf003-281b-46da-a82d-0db61b3d2070)

### Alternatives considered

We can actually make a private space which includes all the rooms we use mostly. This wouldn't be a build-in feature within app. We have to manually do this : )

**Comment by kfiven** [comment]
Duplicate of #44

**Comment by ARBoyGo** [comment]
> Duplicate of #44

Sorry when I share I wasn't able to find. My bad.... Good luck 🥰
