### ISSUE TITLE
Add m.mentions when ping anyone

### ISSUE THREAD

**Issue by loliconshik3** [ajbura/cinny#1688]
### Describe the problem

When ping another users cinny send just a link in formatted_body, it breaks bridges and MSC

### Describe the solution you'd like

Add m.mentions list to event when ping anyone:

```
"content": {
    "body": "nickname ",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"link">nickname</a>:",
    "m.mentions": {
      "user_ids": [
        "@nickname:homeserver"
      ]
    },
    "msgtype": "m.text"
  }
```

**Comment by tezlm** [comment]
duplicate of #1544
