### ISSUE TITLE
Question: What cryptographic algorithm is Cinny using for e2e encryption in-browser?

### ISSUE THREAD

**Issue by marek-lach** [ajbura/cinny#169]
Is it something like [ed25519](https://github.com/paulmillr/noble-ed25519), which [Matrix also recommends](https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide) for public-key pairs, or is it something else?

Thanks for the info,
M

**Comment by ajbura** [comment]
Yes, @marek-lach To support e2ee Cinny use [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk) which use Olm and Libolm libraries.
