### ISSUE TITLE
link to open cinny to a certain room

### ISSUE THREAD

**Issue by deltanedas** [ajbura/cinny#170]
#### Is your feature request related to a problem? Please describe.
element has links like `https://app.element.io/#/room/#cinny:matrix.org`

#### Describe the solution you'd like
something like `https://app.cinny.in/#/room/#cinny:matrix.org`

#### Describe alternatives you've considered
no

#### Additional context
i like to send people links to join rooms on matrix with Good Client(TM)
cinny having a nice link thing to sign up and join a room would be epic

**Comment by deltanedas** [comment]
so basically when navigating to cinny with page history url, if the user isnt signed in, make them then redirect back to the history url

**Comment by ShadowJonathan** [comment]
I'd rather recommend adding Cinny [here](https://github.com/matrix-org/matrix.to/tree/main/src/open/clients), where it'll show up on `matrix.to`.

**Comment by deltanedas** [comment]
why not both?
element has links and is (first lol) on matrix.to

**Comment by ShadowJonathan** [comment]
The app.element.io link is mostly to allow room viewing persistence between reloads, the "go to room directly" is merely a sideeffect, so I really suggest doubling down on just matrix.to.

**Comment by ThePharaohArt** [comment]
> I'd rather recommend adding Cinny [here](https://github.com/matrix-org/matrix.to/tree/main/src/open/clients), where it'll show up on `matrix.to`.

would be good enough imo
