### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Saiv46** [ajbura/cinny#172]
#### Is your feature request related to a problem? Please describe.
Cinny currently lacks offline support and proper caching, which may slow down loading.

#### Describe the solution you'd like
Add service worker that will handle caching, offline support, pushes and other features in future.

#### Describe alternatives you've considered
- Removing `fontshare.com` CSS (that's for another PR)
- Implementing cache in IndexedDB

**Comment by ajbura** [comment]
Duplicate of #17

**Comment by Silther** [comment]
@kfiven 
Can a PWA change the colour of the android statusbar?
