### ISSUE TITLE
Blank line not displayed in bridged discord

### ISSUE THREAD

**Issue by wizard-28** [ajbura/cinny#174]
#### Is your feature request related to a problem? Please describe.

I have markdown formatting enabled. Whenever I enter a blank line in Cinny, it gets rendered properly in the client, but when the message gets copied over to discord the blank line gets removed. This is very annoying.

#### Describe the solution you'd like

Replace the blank space with `&nbsp;` or any other markdown compatible code so that it displays correctly both in Cinny, and the bridged Discord.

#### Describe alternatives you've considered

Force the discord bridge to display the blank line correctly using some other method.

#### Additional context

I got the `&nbsp;` code from [stackoverflow](https://stackoverflow.com/questions/20543454/create-two-blank-lines-in-markdown). Check and use any other method if needed to implement this feature request.

**Comment by samueldr** [comment]
> but when the message gets copied over to discord the blank line gets removed.

What's the behaviour with other Matrix clients? This sounds like it could be a bug in the Discord bridge, and "fixing" on our side would be unwarranted.

**Comment by kfiven** [comment]
AFAIK it's micromark causing these newlines to disappear but in my testing newlines only appear in input and when message is sent they disappear even in Cinny.

**Comment by samueldr** [comment]
Maybe I'm misunderstanding the issue. There may be more than one conflated here.

One I observed and need to look into, but is *technically correctly handled* is empty lines *in a message* are treated as paragraph breaks, while compared to element, the same empty lines are newlines, e.g. the following input:

```
line 1

line 3
```

When written with Cinny shows up as:

> line 1
> line 3

When written with element shows up as:

> line 1  
>   
> line 3

**Note:** I said *written with $client* as the produced HTML is correct and visually matches what is observed on either client; both client shows the same results. This is purely an issue when sending messages, and technically is "more right" as `<p>` like Cinny does, considering what Markdown is.

Though, I expect the original issue isn't that. Maybe this is what @kfiven is observing.

* * *

**With that said**, I don't think this is what this issue is about.

@kfiven, and @wizard-28, can you provide more information about your (assumed to be different) issues, with screenshot of what was written, and how it's handled? A good way to provide information is to copy/paste what you enter in the Cinny text box between backticks <code>```</code>, like here:

````markdown
```
line 1

line 3
```
````

@kfiven, if @wizard-28 answers first and is not relevant to your issue, can you file a new issue?

**Comment by kfiven** [comment]
Hi @samueldr I believe both me and wizard reporting is same issue. So this behaviour is not specific to discord bridge and happening on other clients too.

If I have markdown enabled:

```
line1

line3
```
render in Cinny as 
> line1
> line3

in Element as
> line1
>
> line3

and on discord as 
>line1line3

If markdown is off:
```
line1

line3
```
render in Cinny as 
> line1 line3

in Element as 
> line1
>
> line3

in discord as
> line1
>
> line3

Sorry for mis-clicking and closing the issue.

Also if we try both these steps in Element bridge doesn't show any discrepancy but Cinny does.

**Comment by samueldr** [comment]
Right, I see. I think it's highly likely you're reporting the same issue. Though they may be two distinct problems with different fixes.

And (not so coincidentally) the issue I've shown is one of those.

I believe the two issues are as such:

 - The discord bridge handles the markdown input poorly *or* specific to paragraphs in markdown input
 - Cinny and Element disagree about what input should be sent how.

**Note** that messages may be either *plain text* or *HTML formatted* in Matrix. And this probably matters a lot for all of this.

* * *

### Discord bridge issues

(I can't say anything about that, I don't know which bridge it is, and I don't care about discord...)

I suspect something has to be handled differently by the bridge. It's also unclear whether it's in the Discord→Matrix or Matrix→Discord direction that there are issues (or both, either different or the same).

### Cinny and Element disagreeing about input

Looking at our previous example input:

```
line 1

line 3
```

 - Cinny with Markdown **sends rendered** the example input as: `<p>line 1</p>\n<p>line 3</p>` and it's a valid interpretation of the markdown.
 - Element, **sends the example input as *plain text***!!, contrary to my initial assumption.

Let's force some markdown by using:

```
line *1*

line 3
```

 - Cinny with Markdown **sends rendered** the example input as: ` <p>line <em>1</em></p>\n<p>line 3</p>` and it's a valid interpretation of the markdown.
 - Element, **sends rendered** the example input as: `<p>line <em>1</em></p>\n<p>line 3</p>\n`.

This explains the issue I had observed, and a chunk of what you are observing.

**Comment by samueldr** [comment]
Ah, and about Cinny configured for sending plain text:

```
text 1

text 3
```

I have tried it on my WIP branch and don't see the same issue as you do. I'm somewhere between the current state of the dev branch and the last release, **with additional changes to rendering**, so I can't say for sure. I should rebase my changes on top of dev to better test with plain text.

**Comment by wizard-28** [comment]
> @kfiven, and @wizard-28, can you provide more information about your (assumed to be different) issues, with screenshot of what was written, and how it's handled? A good way to provide information is to copy/paste what you enter in the Cinny text box between backticks ```, like here:

I've typed the `--Testing begins for Cinny (matrix client) bug--` before testing begins to act as a marker.

## Cinny
### Typed Message
![cinny_typed_message](https://0x0.st/-huM.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

### Sent message
![cinny_sent_message](https://0x0.st/-hu_.png)

*Image transcript*:
```monospace
Line one.
Line three.
```

### Discord Bridged Message
![discord_bridged_message](https://0x0.st/-hu2.png)

*Image transcript*:
```monospace
Line one.Line three.
```

## Element
### Typed Message

![element_typed_message](https://0x0.st/-huf.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

### Sent Message
![element_sent_message](https://0x0.st/-huO.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

### Discord Bridged Message
![discord_bridged_message](https://0x0.st/-huV.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

## Discord

### Typed Message

![discord_typed_message](https://0x0.st/-huJ.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

### Sent Message

![discord_sent_message](https://0x0.st/-hut.png)

*Image transcript*:
```monospace
Line one.

Line three.
```

### Matrix Bridged Message

#### Cinny

![cinny_bridged_message](https://0x0.st/-huw.png)

*Image transcript*:
```monospace
Line one.
Line three.
```

#### Element

![element_bridged_message](https://0x0.st/-hux.png)

```monospace
Line one.

Line three.
```

**Comment by samueldr** [comment]
@wizard-28 

Can you send, **with element**, the following lines and see what it looks like on the discord end?

```
Line *1*

Line 3
```

I hope it will fail the same exact way it fails with Cinny. If so, it's really a bug in the Discord bridge, not correctly handling either HTML or specifically `<p>` in HTML.

This is because Element will send plain text if there's no markdown formatting, instead of sending an HTML message. Forcing markdown formatting makes it send an HTML formatted message.

**Comment by wizard-28** [comment]
> @wizard-28 
> 
> Can you send, **with element**, the following lines and see what it looks like on the discord end?
> 
> ```
> Line *1*
> 
> Line 3
> ```
> 
> I hope it will fail the same exact way it fails with Cinny. If so, it's really a bug in the Discord bridge, not correctly handling either HTML or specifically `<p>` in HTML.
> 
> This is because Element will send plain text if there's no markdown formatting, instead of sending an HTML message. Forcing markdown formatting makes it send an HTML formatted message.

## Element

![Screenshot_20211203-000315_Element.jpg](https://user-images.githubusercontent.com/49679481/144482160-99ab9b18-4267-45b5-91f2-622e3a478c58.jpg)

## Discord

![Screenshot_20211203-000413_Discord.jpg](https://user-images.githubusercontent.com/49679481/144482272-bf64edd8-5c36-4ee9-832b-073747c20e3c.jpg)

**Comment by wizard-28** [comment]
> it's really a bug in the Discord bridge,

So, I should open an issue on t2bot's GitHub?

**Comment by samueldr** [comment]
> So, I should open an issue on t2bot's GitHub?

Yes. AFAICT, any "fix" done in a specific client (e.g. Cinny) would be a workaround done at the wrong place. Complexity added for no good reasons.

I would also suggest you refer to this issue directly so they know what inputs cause the misbehaviour :).

Oh, and thank you for taking the time to do the tests all the way through!

**Comment by kfiven** [comment]
https://github.com/ajbura/cinny/issues/174#issuecomment-984296305
```
If markdown is off:

line1

line3
render in Cinny as

line1 line3
```
has been fixed in recent release. So only issue left is the one pointed by Samueldr, is because of bridge. 

So closing this.
