### ISSUE TITLE
Separate login and registration form URIs.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ajbura/cinny#1746]
### Describe the problem

I use a password manager - https://github.com/bitwarden/clients/releases/tag/desktop-v2024.5.0 - which provides autofill capabilities. I don't want it to autofill on the registration form, and do want it to autofill on the login form. I cannot do this without explicitly whitelisting and blacklisting both of the form pages' input elements' HTML anchor IDs.

### Describe the solution you'd like

Display separate URIs for each page.

### Alternatives considered

> Explicitly whitelisting and blacklisting both of the form pages' input elements' HTML anchor IDs.

This isn't a solution, because these can *invisibly* change at any time, without any notice, so it remains a more significant security issue than the URI changing.

**Comment by ajbura** [comment]
current dev branch now have url navigation in auth screen you can check it at dev.cinny.in
