### ISSUE TITLE
Allow sponsoring via GitHub

### ISSUE THREAD

**Issue by grandeljay** [ajbura/cinny#175]
Would you consider allowing [sponsorships via GitHub](https://github.com/sponsors)? Not sure about others but it would be a convenience I would appreciate.

**Comment by ajbura** [comment]
Hi, I don’t reside in supported regions, so it’s not available for me.

**Comment by grandeljay** [comment]
It seems to be available now. I would like to do a monthly subscription but 5 USD/Month (required minimum) is a bit much for my budget, do you mind adjusting it please?

**Comment by kfiven** [comment]
There’s a custom one as well.

**Comment by grandeljay** [comment]
Yes, that is the field I am referring to. It has a required minimum of 5 USD set.
![image](https://github.com/cinnyapp/cinny/assets/45571053/af3e5a4a-9b16-451e-ab78-9f086898d46f)

Can you please check your sponsor dashboard? It's probably under https://github.com/sponsors/ajbura/dashboard/tiers and looks something like this:
![image](https://github.com/cinnyapp/cinny/assets/45571053/b4b6cd14-ae3e-4840-930a-cb138ec93339)

**Comment by kfiven** [comment]
Ping @ajbura

**Comment by ajbura** [comment]
I have removed the limit.

**Comment by grandeljay** [comment]
Thank you
