### ISSUE TITLE
More control over donated money

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#1753]
I want to donate to the project, but I want to be able specify which feature I want the money to be used for. I don't want to generally donate to the project, because I don't want my money to be spent on a rich text editor, sticker pack or PWA support. I want to donate specifically for message threads (MSC 3440, tracked in #257), as this is the one I would use. Donating to other features is just a waste of money for me. Surely, it would be a nice thing to give unconditionally, but unfortunately I don't have infinite money, so I'm more likely to donate if I receive added value in exchange for it. Multiple studies confirm that willingness to donate is reduced by the inability to specify what feature/bug will receive the money (it also applies to other fields, e.g. charities).

[Polar](https://polar.sh) has a good UX for this. I'm not affiliated with Polar, and would be happy to use other platforms that provide the same feature, but I don't know about others. Bug bounty sites exist, but those are different, and many consider it harmful:
https://ziglang.org/news/bounties-damage-open-source-projects/

Instead, the donation model Polar is using, is benefitting the maintainers:
https://ziglang.org/news/announcing-donor-bounties/ (The Zig project figured it out separately from Polar, but the principles are similar - this is an indication that many think it's a good direction.)
https://polar.sh/polarsource/posts/polar-v1-0-lets-fix-open-source-funding

Again, I would be happy to donate using a different bug financing platform, if it has the same model as Polar, and not bug hunting sites. Unfortunately, recurring payments like Liberapay and OpenCollective are not too motivating for me. It's better for sponsors who don't care about features/bugs, but instead they want a place to display their logos to gain popularity/SEO backlinks.

**Comment by kfiven** [comment]
Looks like Polar is available in [selected countries only](https://polar.sh/docs/overview/faq/for-maintainers#which-countries-are-supported), so we won't be setting that up. 

Also the existing donation mediums are enough and works for all and also have the minimum commission fee, so I also don't see a need to setup another one.
