### ISSUE TITLE
spoiler display support

### ISSUE THREAD

**Issue by deltanedas** [ajbura/cinny#176]
#### Is your feature request related to a problem? Please describe.
Spoilers with reason using `<span data-mx-spoiler>` are not supported by cinny. https://spec.matrix.org/v1.1/client-server-api/#spoiler-messages

#### Describe the solution you'd like
Show a darkened rectangle over spoiler'd text, click to hide it

#### Describe alternatives you've considered
element blurs it which i don't like for my minesweeper bot command (kinda spoils it doesn't it)
element android has a white rectangle which works but is ugly

**Comment by ShadowJonathan** [comment]
@DeltaNedas Could you change the title to "Spoiler display support"? else people might think this is about supporting creating spoilers

**Comment by deltanedas** [comment]
done, creating spoilers now in #177 specifically

**Comment by ajbura** [comment]
It's already done and live in dev.cinny.in. Gonna keep it open until the release.

**Comment by ShadowJonathan** [comment]
@ajbura does it display reasons for spoilers as well?

**Comment by ajbura** [comment]
@ShadowJonathan nope.

**Comment by ShadowJonathan** [comment]
Then I'd recommend leaving this issue open, as showing spoiler reasons is something that matrix also explicitly specs

**Comment by deltanedas** [comment]
minor issue, but you can't click spoilers to toggle them, instead of only being able to show them when hovered
would be cool if spoiler behaviour had a toggle

i basically only care about this for playing minesweeper, so its not too big of a deal

**Comment by ajbura** [comment]
> would be cool if spoiler behaviour had a toggle

Sure, I was just playing around with them and hover looked really cool but I guess that isn't the right way. :D

**Comment by deltanedas** [comment]
oh no, it is really cool for "normal" use cases

**Comment by kfiven** [comment]
Closing this as spoilers display now, and created new issue for reason.
