### ISSUE TITLE
spoiler creation support

### ISSUE THREAD

**Issue by deltanedas** [ajbura/cinny#177]
#### Is your feature request related to a problem? Please describe.
being able to send spoiler text from cinny

#### Describe the solution you'd like
`||text||` -> plain `(Spoiler: text)` or something, html `<span data-mx-spoiler>text</span>`

#### Describe alternatives you've considered
<span data-mx-spoiler>text</spoiler> - ew verbose
<spoiler>text</spoiler> - ew still verbose, and has no grounds in matrix

#### Additional context
discord uses ||
afaik element has no way to create it besides a command (for the whole message)
not part of commonmark so custom parsing is probably needed

**Comment by deltanedas** [comment]
probably involves a pr to https://github.com/micromark/micromark

**Comment by samueldr** [comment]
> afaik element has no way to create it besides custom events

No in-line spoilers, but full-message with `/spoiler the spoiler text` works in Element.

**Comment by deltanedas** [comment]
interesting, updated
