### ISSUE TITLE
Reply in Thread

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#1773]
### Describe the problem

#ROOMS  Cinny
##Cinny issus  
> Cinny issus. is ROOMS Cinny. "Reply in Thread"
---

Discord channel bridge to Cinny Reply in Thread.

### Describe the solution you'd like

like (Element) Reply in Thread 

### Additional context

#ROOMS **AA Testing  invites**
##AAA test enc 
> AAA test enc is ROOMS AA Testing  invites. "Reply in Thread"

##Anime & Manga
> Anime & Manga is ROOMS AA Testing  invites. "Reply in Thread"

![Screenshot_20240611-131314](https://github.com/cinnyapp/cinny/assets/169121286/39235b9b-55a7-4bb1-84e3-b25ccfbe672d)

**Comment by kfiven** [comment]
Duplicate of #257
