### ISSUE TITLE
Replying to a message losses text cursor focus

### ISSUE THREAD

**Issue by RoyalWolfie** [ajbura/cinny#1789]
### Describe the bug

When replying to a message using the reply feature, the text cursor is lost; which means you need to click back on the message box.

### Reproduction

1. Reply to a message that was sent previously

### Expected behavior

When replying to a message for the text cursor to keep its position, and not having to re click on the message box

### Platform and versions

```shell
OS: Arch Linux
Browser: NA
Cinny version: 3.2.0
Homeserver: Matrix.org
```

### Additional context

If you already have typed out a message this isn't an issue. But for people who reply then compose a message it is.

**Comment by kfiven** [comment]
Working with v4.0.3
