### ISSUE TITLE
Chat history fails to load without any indication

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#179]
#### Describe the bug
When scrolling up on a chat room, cinny will randomly fail to load a chunk of messages. For example:

```
a
b
c
```
Assuming `a` `b` and `c` are chunks of messages, cinny will fail to load `b` and show:
```
a
c
```
Without any indication that a chunk of message failed to load in the middle.

This leads to confusion on weather that chunk of msg was deleted or what happened. Reloading the page typically fixes the issue.

#### To Reproduce
Not sure how to trigger this consistently, but simply scrolling up on chat rooms can randomly trigger this.

#### Expected behavior
Either load the messages or at least show some indication that some messages failed to load.

#### Desktop (please complete the following information):
 - OS: GNU/Linux
 - Browser: Firefox v93

**Comment by kfiven** [comment]
Just to be sure, are you using app.cinny.in and is the room you having issues is encrypted? @N-R-K

**Comment by N-R-K** [comment]
Yes I'm using app.cinny and no, the room is not encrypted.

**Comment by ajbura** [comment]
@N-R-K Could you please keep an eye on this in 1.6.0 release. To my knowledge it shouldn’t happen now.

**Comment by N-R-K** [comment]
Though I haven't used matrix/cinny too much in the past week, I didn't come across this bug during my limited usage.

Closing for now, will reopen if I come across this bug again.
