### ISSUE TITLE
Feature Request: Markdown Support

### ISSUE THREAD

**Issue by farribeiro** [ajbura/cinny#18]
**Is your feature request related to a problem? Please describe.**
The messages going to plain text to HS. 

**Describe the solution you'd like**
Add Markdown Support

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ajbura** [comment]
Done in https://github.com/ajbura/cinny/commit/92ba6c98023c520066cdf8d462e68e5ff45a6ed2
