### ISSUE TITLE
Jump-to-Unread and Mark-as-Read buttons blurred

### ISSUE THREAD

**Issue by Duvio** [ajbura/cinny#1805]
### Describe the bug

When shown in a room, the Jump-to-Unread and Mark-as-Read buttons are blurred.
![cinny_issue](https://github.com/user-attachments/assets/4425e230-40b2-4e3b-a888-cb5917870678)

### Platform and versions

```shell
1. Linux Debian Testing
2. Cinny 3.2.0, Flatpak
```

**Comment by kfiven** [comment]
Seems to be some issue with your graphics? Messages also looks blurry.

**Comment by Duvio** [comment]
> Seems to be some issue with your graphics? Messages also looks blurry.

The messages are displayed correctly. They might look blurry in the screenshot because it's zoomed in.

**Comment by kfiven** [comment]
Looks duplicate of https://github.com/cinnyapp/cinny-desktop/issues/332
