### ISSUE TITLE
Support for MSC3916: Authenticated Media

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1818]
### Describe the problem

Matrix.org is [planning to sunset the old media endpoints](https://matrix.org/blog/2024/06/26/sunsetting-unauthenticated-media/) in August, which will break media access for clients that do not support [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916)

### Describe the solution you'd like

Ensure that Cinny supports Authenticated Media Access according to the MSC

### Alternatives considered

-

### Additional context

-

**Comment by bkil** [comment]
Just to remind you about this issue: Cinny has become a text-only client since about yesterday. That's definitely a hipster quality and I'm a big fan of terminals, but was kind of surprised it rolled this way.

**Comment by Kimiblock** [comment]
That’s not true on home servers that doesn’t enforce authenticated media. Which is the default setting on Synapse.
Authenticated media can be easily defeated by using other servers as a proxy, not sure why they end up enforcing that.

**Comment by bkil** [comment]
Is there any further information we can provide you to help fix this issue?

**Comment by ShadowRZ** [comment]
Implmented with https://github.com/cinnyapp/cinny/pull/1930

However service workers seems to be hard to refresh, so probably the best thing people can do is to do multiple refersh (maybe even hard refersh) until media loads properly.

**Comment by sutnistj** [comment]
Images finally are showed, but thereʼs still problem with mp4 — error with mime-type. Before auth-media-error mp4 were also showed. 
![зображення](https://github.com/user-attachments/assets/46ac05ae-ff6e-4c61-b870-8d3b7559bece)

Itʼs the same error or itʼs better for me to write a separate issue here?

**Comment by Salamandar** [comment]
FYI you need to reload the app page after upgrade, wait for it to `connect` to your home server, then wait a bit then AGAIN reload the web page. And now it should work.
