### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#182]
#### Is your feature request related to a problem? Please describe.
When I receive a notification, I am not actually notified unless I am looking at the Cinny app tab in my browser.

#### Describe the solution you'd like
Many web apps leverage browser functionality to send notifications to the desktop, allowing native popup notifications when an event occurs. This requires additional browser permissions for the tab.

#### Describe alternatives you've considered
A native desktop app would require more development effort

#### Additional context
N/A

**Comment by 3nt3** [comment]
Can I work on this?

**Comment by ajbura** [comment]
Sure @3nt3
