### ISSUE TITLE
After updating to 4.0 chats can no  longer be navigated with PgUp / PgDown

### ISSUE THREAD

**Issue by tux93** [ajbura/cinny#1838]
### Describe the bug

After updating Cinny to version 4.0.0 it is no longer possible to scroll a chat with Page Up / Down.

This is a regression re-introducing #1015 

### Reproduction

1. Open any room
2. Try to scroll with Page Up / Down

### Expected behavior

The chat scrolls.

### Platform and versions

```shell
openSUSE Tumbleweed
Firefox 127.0.2
Cinny 4.0.0 (cinny.squirrel.rocks)
Dendrite 0.13.7 (matrix.squirrel.rocks)
```

**Comment by kfiven** [comment]
Seems to be working here on firefox 128.0.2

**Comment by tux93** [comment]
I got the update to Firefox 128.0.0 today and the issue still exists there, the only thing that happens when pressing page up / down is that the input box gets focused.
