### ISSUE TITLE
After upgrade to 4.0, messages predating the update can't be marked as read

### ISSUE THREAD

**Issue by therealprof** [ajbura/cinny#1841]
### Describe the bug

After update to 4.0.3 (which I only noticed due to setting up a new web brower), messages which were not read before the update can't be marked as read anymore. It seems the only way to get those marked is new messages coming in, which might not happen for a while on a low traffic channel.

<img width="255" alt="Screenshot 2024-07-25 at 09 59 45" src="https://github.com/user-attachments/assets/00d685bd-3286-4d59-918f-71b8134d763a">

Rust Embedded also had 400 unread messages which disappeard right after someone sent a message.

### Reproduction

1. Go to a server which has low traffic channels with unread messages
2. Reload cinny to update
3. Observer that "Mark as read" doesn't work and the counter just stays

### Platform and versions

```shell
macOS 14.5
Various browsers: e.g. Opera 112 and Duckduckgo 1.97
https://app.cinny.in/%23rust-embedded-space%3Amatrix.org/%23rust-embedded-graphics%3Amatrix.org
Cinny v4.0.3
```

**Comment by ajbura** [comment]
How are you marking them as read.
1. Marking space as read?
2. Marking individual room as read?

**Comment by therealprof** [comment]
Both don't work. Also simply reading the messages doesn't work.

**Comment by therealprof** [comment]
<img width="1724" alt="Screenshot 2024-07-25 at 11 09 11" src="https://github.com/user-attachments/assets/cc507fa9-d624-424d-adee-e8acbcab9545">

Down to one channel now. The problem is slowly disappearing. ;)

**Comment by kfiven** [comment]
Closing as it seems to be working now.
