### ISSUE TITLE
Position the cursor at the end of the message when editing a message

### ISSUE THREAD

**Issue by SteffoSpieler** [ajbura/cinny#1857]
### Describe the problem

When I try to edit a message (in my case: with pressing the arrow-up button), then the cursor gets positioned at the beginning of the message. So I have to manually click / move to the end when I just wanted to fix or add something small.

### Describe the solution you'd like

Position the cursor at the end of the message (like almost every other messenger does it: Discord, Signal, Unigram) when starting to edit a message.

### Alternatives considered

1. Moving my mouse to click at the end
2. Pressing Ctrl+arrow-right multiple times
3. ...

**Comment by paulbdavis** [comment]
confirmed, this seems to have been introduced in 4.1.0, IIRC in 4.0.x it was behaving normally

**Comment by SteffoSpieler** [comment]
As I'm using Cinny Desktop, and this issue was created a week ago (and the 4.1.0 release only 2 days ago), the bug had to have been introduced in 4.0.X.

**Comment by kfiven** [comment]
it's there since long time. we haven't changed anything in v4.0 related to rich input editor.

anyways, when you goes into edit mode, you can use up/down left/right arrow to navigate.
