### ISSUE TITLE
Usability: Accept Matrix address in username field at login

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#187]
Currently, the user has to enter the server name, then enter the localpart of the Matrix address.

The username field should accept a full Matrix ID in that field(eg. @notramo:grin.hu), then fill the server name automatically.

![image](https://user-images.githubusercontent.com/26059643/146612336-9ba87443-d390-4d1a-be1f-bfc9730b1167.png)

**Comment by notramo** [comment]
@ajbura, it doesn't work on dev.cinny.in
It don't show the error, but doesn't change the homeserver input field.
![image](https://user-images.githubusercontent.com/26059643/178745327-6be89e6b-66a5-4e7a-8474-2793f7230143.png)

**Comment by ajbura** [comment]
it’s never supposed to change that field but it will log you in. Changing that field will slow the login process as card will reload based on what login methods are supported by homeserver.

**Comment by notramo** [comment]
But the new homeserver may not support SSO.
For example, the grin.hu server doesn't support Apple, Google, GitHub, etc. logins, but the icons are shown.
Also, it's a problem with mozilla.org HS as it only supports SSO.

**Comment by ajbura** [comment]
yeah, I still recommend username in that field and changing homeserver where it’s shown. It’s for pro users who wants to get into app fast.

I don’t like the idea when someone enter their mxid in username field, say a mozilla hs mxid and that field disappear completely. but now it will just show them an error that password based login isn’t supported.
