### ISSUE TITLE
Add a warning or indicator next to messages with type "m.thread"

### ISSUE THREAD

**Issue by rosemash** [ajbura/cinny#1871]
### Describe the problem

I just started using Cinny, and I almost immediately embarrassed myself by replying to messages in an active room that nobody else could see.

### Describe the solution you'd like

If Cinny doesn't have any immediate intention of adding support to threads (https://github.com/cinnyapp/cinny/pull/1349), it would be very practical to have a UI indicator beside any message that has the type "m.thread" attached to it, so you can infer that it's not visible to others.

### Alternatives considered

The alternative would be adding support for threads.

**Comment by greentore** [comment]
Sounds like a good idea. Element-x is doing that.

**Comment by ajbura** [comment]
fixed in #1349
