### ISSUE TITLE
Loading module from “https://cinny.tld.com/src/index.tsx” was blocked because of a disallowed MIME type (“text/html”).

### ISSUE THREAD

**Issue by Patriot2407** [ajbura/cinny#1878]
### Describe the bug

When deploying cinny docker, Cinny does not load and just present me with the above error in devtools

### Reproduction

Completely remove docker image and delete it's data, and redownload docker container and reconfigure, and same thing happens. Tried last 3 version tags as well, no change.

### Expected behavior

Cinny should load the loogin page.

### Platform and versions

```shell
1. OS: Unraid
2. Browser: LibreWolf (Firefox)
3. Cinny version (4.1.0)
4. Matrix homeserveRr: self hosted
```

### Additional context

I have tried clearing cookies and cache, and using inPrivate window.

**Comment by Patriot2407** [comment]
Also, it is behind an unmodified NPM reverse proxy, this configuration used to work fine.

**Comment by Patriot2407** [comment]
I tried directly loading it in another device directly using IP:port with same behavior, so I don't believe it's an issue with the reverse proxy.

**Comment by kfiven** [comment]
Why it's loading .tsx file? Could you please share your docker config file if possible?

**Comment by Patriot2407** [comment]
Its the exact one downloaded from your repo, as I said, no changed made

**Comment by Patriot2407** [comment]
I have no idea, I came here for help

**Comment by Patriot2407** [comment]
Nevermind, the issue was on my end. I incorrectly mapped the entirety of the html dir in the container to a volume, when I only needed the config.json file mapped, this was user error. Thanks for your time.
