### ISSUE TITLE
Bottom left Settings icon should be in sidebar, not in menu

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#188]
It should be like the search icon.
![image](https://user-images.githubusercontent.com/26059643/146655621-4ea25dda-3b62-418a-8551-57abe2c3ca55.png)

**Comment by ajbura** [comment]
Now user settings window just open on profile click.

**Comment by notramo** [comment]
When I click my profile picture, I expect to find some profile-related settings, and logout.
When I want to configure the app, I look for a gear icon, like the one in the above screenshot.

What about having that gear icon in the size of the magnifying glass icon in the sidebar, between the profile picture and the magnifying glass?

And when the profile image is clicked, it would show logout and account switch buttons (when multiaccount is added).

**Comment by ajbura** [comment]
Reasons I don’t want to add Settings between Room search and user profile a) Afterall app/client settings are user settings too. b) To avoid using different icon that leads to same settings drawer.

**Comment by ajbura** [comment]
Closing as we no more have menu after clicking Profile avatar.
