### ISSUE TITLE
Sharing a link to a message should produce a matrix: URI, following matrix: URI should work

### ISSUE THREAD

**Issue by bkil** [ajbura/cinny#1880]
### Describe the bug

* Sharing a link to a message at present produces a `https://` URI to your Cinny web app client. Others clients (or those on other web apps) can't follow such links.
* If one shares a link to a message in a widespread, provider-agnostic format (such as `matrix:` or `https://matrix.to/`), a Cinny web app user should be able to click on the button (link) and it should open the respective room and scroll to the respective message.

### Platform and versions

```shell
Cinnyv web 4.0.3
```

**Comment by ajbura** [comment]
please upgrade to Cinny 4.1.0

**Comment by bkil** [comment]
Thanks
