### ISSUE TITLE
option to mute a space at once

### ISSUE THREAD

**Issue by yumpyy** [ajbura/cinny#1895]
### Describe the problem

currently, cinny doesn't provide an option to mute a space in the "space settings" menu.

### Describe the solution you'd like

add in an option to mute a space at once.

### Alternatives considered

an alternative way to mute a space is by muting every room in a space individually, but this alternative is annoying as going through the "room settings" page of 10+ channels takes a lot of time and clicking.

**Comment by kfiven** [comment]
Because Spaces are just collection of rooms. Sadly the only way to go is by doing for each or maybe change the global user notification setting.
