### ISSUE TITLE
Design: Separate "Jump to unread" and "Mark as read" buttons

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#192]
![cinny-unread](https://user-images.githubusercontent.com/26059643/146674030-8cef7dcf-9fc2-4994-88a1-3aa93ea4ac3f.png)

It seems that it is one button, that when clicked, jumps to unread (since it's written on it). If the user accidentally clicks the right side of  the button, it marks the conversation as read, and there will be no convenient way to go to the first unread message.
The two buttons should be a few pixels apart from each other and have their inner corners rounded. Maybe both buttons should have text (instead of icon on "Mark as read").

**Comment by ajbura** [comment]
Made some changes into this direction, check if they are sufficient to remove this confusion.

**Comment by ajbura** [comment]
The reason im not using arrow in jump to unread is because jump to unread could be used for both upward and downward. Instead of tick mark other client show cross but used tick mark because it’s truly what’s happening. Having both in text also looks ugly.

**Comment by notramo** [comment]
What about separating the two, putting them e.g. 5 pixels apart, and having the inner borders rounded too? Would be that ugly?

**Comment by ajbura** [comment]
> What about separating the two, putting them e.g. 5 pixels apart

I have done something similar but it’s subtle (1px), tried more than 1px too but doesn’t look great.

**Comment by notramo** [comment]
And what about not having "Jump to unread" at all, and jumping to the first unread automatically instead?

**Comment by ajbura** [comment]
That already work but only when Unread indicator load with initial timeline load but when it's too deep in timeline then only option to show Jump to unread.

**Comment by notramo** [comment]
> >   What about separating the two, putting them e.g. 5 pixels apart

> I have done something similar but it’s subtle (1px), tried more than 1px too but doesn’t look great.

![image](https://user-images.githubusercontent.com/26059643/146759184-47c0dae0-587b-4527-aa62-f1eb6ed92c17.png)

Do you find it ugly? If yes, then I think, the issue can be closed.

**Comment by ajbura** [comment]
Closing as per discussion in Matrix room.

**Comment by N-R-K** [comment]
I agree that the buttons needed some separation, I failed to notice they were two different buttons as well (#184). The current 1px separation is a clear enough indication, at least for me. So I'd say adding more space is not strictly needed.
