### ISSUE TITLE
Images don't load after matrix.org pulled the plug on unauthenticated media access

### ISSUE THREAD

**Issue by Reinachan** [ajbura/cinny#1926]
### Describe the bug

Images do not load anymore in neither E2EE rooms nor unencrypted rooms as matrix.org now requires support for authenticated media.
https://mastodon.matrix.org/@matrix/113080295526560511

### Expected behavior

Images should be fetched with authentication headers so that it can be loaded.

### Platform and versions

```shell
All platforms. I'm currently at v4.1.0
```

**Comment by kfiven** [comment]
duplicate of #1818
