### ISSUE TITLE
Cannot login to servers that use Matrix Authentication Service with an upstream OIDC provider

### ISSUE THREAD

**Issue by thefinn93** [ajbura/cinny#1931]
### Describe the bug

When I try to use Cinny with my Matrix server, I'm unable to login:

![image](https://github.com/user-attachments/assets/40aca7ac-4421-41a2-9d20-627b97e1442c)

### Reproduction

1. Visit https://app.cinny.in
2. Enter the domain of a Matrix server that uses MAS with an upstream OIDC provider and no password auth. `devhack.net` is an example of such a server.

### Expected behavior

An OIDC login button is shown

### Platform and versions

```shell
OS: Debian 12
Browser: Firefox 
Cinny: v4.1.0
```

### Additional context

This server works fine with Element and FluffyChat.

**Comment by tulir** [comment]
https://github.com/cinnyapp/cinny/blob/dev/src/app/hooks/useParsedLoginFlows.ts#L10-L12 looks like cinny requires `identity_providers` to be present, but according to [the spec](https://spec.matrix.org/v1.11/client-server-api/#client-login-via-sso), those fields are not required

![image](https://github.com/user-attachments/assets/88ce79e0-12dc-4cd3-9e29-2df2ef3ce39a)
