### ISSUE TITLE
Reaction search allows using any text

### ISSUE THREAD

**Issue by jman-schief** [ajbura/cinny#1951]
### Describe the bug

I'm not 100% sure this is a bug or rather something else.

Using the Web App I can search and use as reaction whatever I feel like typing in the search field.

### Reproduction

1. Click the emoji reaction icon on any message in a room
2. In the search field type "Today I feel like meteors could fall on my head"
3. Click "React"
4. A reaction with such text is added to the message

### Expected behavior

Maybe keep the "React" button disabled until an emoji matching the search is found?

### Platform and versions

```shell
1. Linux Debian/trixie (testing channel)
2. Mozilla Firefox 131.0b5 
3. Cinny 4.2.0 (app.cinny.in)
4. Matrix homeserver: (own instance) synapse v1.111.0
```

**Comment by kfiven** [comment]
This is a feature. These are custom text reaction used by many people.

**Comment by jman-schief** [comment]
> custom text reaction

TIL!

Alright. thanks for the reply
