### ISSUE TITLE
OpaqueResponseBlocking prevents image from loading

### ISSUE THREAD

**Issue by Ashvith10** [ajbura/cinny#1960]
### Describe the bug

Images fail to load on Cinny. Here's the log on the console:

![Screenshot_2024-09-18_09-37-03](https://github.com/user-attachments/assets/e243a68d-66e0-4f63-94df-5a4ccb72125d)

(Text for screen reader)

```console
(ERROR)
------------
GET
https://matrix-client.matrix.org/_matrix/client/v1/media/download/matrix.org/OqwoiUGdvgDsgjdXDVlqaDet?allow_redirect=true#_uDarkclass=_189qrd90+_1mqalmd1+_1mqalmd0&tabindex=0&loading=lazy
NS_ERROR_FAILURE

(WARNING)
----------------
A resource is blocked by OpaqueResponseBlocking, please check browser console for details. OqwoiUGdvgDsgjdXDVlqaDet
```

### Reproduction

1. Go to a room
2. Look for image embedded in Matrix, or upload your own image
3. Image fails to load

### Expected behavior

The image should load without any issues.

### Platform and versions

```shell
1. Guix (unstable master branch, see channel commit below):

$ guix describe
  guix eed2fcc
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: eed2fcc719e0d32ee914794adae7166067d2f9a8
  nonguix 99a4773
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: 99a47731552b179ea021a65a8a6f474cece68182
  omega cd83c85
    repository URL: https://codeberg.org/pastor/omega
    branch: main
    commit: cd83c852a1d9d4a2a1522d09bf535fe54686c98a

2. LibreWolf 129.0.1-1, Firefox 130.0
3. v4.2.1
4. matrix.org
```

### Additional context

\-

**Comment by diamondburned** [comment]
<details>
<summary>Old, incorrect comment</summary>

I can replicate this as well on Firefox, although with a different error:

```
GET
https://matrix-client.matrix.org/_matrix/client/v1/media/thumbnail/t2bot.io/5a3a2939f12126d8ce106385831867d1d6cdc8161771316280532402176?width=100&height=100&method=crop&allow_redirect=true
NS_BINDING_ABORTED
```

</details>

I'm actually having a hard time replicating this error. After turning off uBlock Origin and Firefox's Enhanced Tracking Protection, everything works fine now.

**Comment by Ashvith10** [comment]
@diamondburned btw the Firefox instance that I tried here (alongside LibreWolf) was a fresh install, with all the vanilla settings.

**Comment by kfiven** [comment]
Can not reproduce on the Firefox.

**Comment by kfiven** [comment]
Closing as no response and can not reproduce. Btw this is just an warning and not any error so it should not be an issue.

**Comment by maurges** [comment]
Happened to me after the latest update. Turning off uBO in my firefox still fixes this.

**Comment by yodaluca23** [comment]
Happening for me too, toggling uBlockOrigin sometimes seems to fix it, still annoying though.
