### ISSUE TITLE
Implement MSC4193

### ISSUE THREAD

**Issue by 88572** [ajbura/cinny#1966]
### Describe the problem

There is not a way to add a spoiler/CW (content warning) to media.

### Describe the solution you'd like

Implement [MSC4193](https://github.com/matrix-org/matrix-spec-proposals/pull/4193) instead.

### Additional context

I may be biased on this suggestion, as I made the MSC.

**Comment by kfiven** [comment]
We don't have bandwidth to work on msc proposals, but if you want to implement this, I am happy to look at PR.
