### ISSUE TITLE
Incorrect Mozilla HS name

### ISSUE THREAD

**Issue by notramo** [ajbura/cinny#199]
The domain used in Matrix IDs is mozilla.org
The displayed mozilla.modular.im is only the .well-known address (like matrix-client.matrix.org).
![image](https://user-images.githubusercontent.com/26059643/146769442-44a992e4-da21-42ad-a3ef-439db67fce46.png)

**Comment by ajbura** [comment]
[Mozilla wiki](https://wiki.mozilla.org/Matrix#Connection_parameters) recommend `modular.mozilla.im` as homerserver. I have tried mozilla.org and it doesn’t return anything.

**Comment by notramo** [comment]
https://www.mozilla.org/.well-known/matrix/client

**Comment by notramo** [comment]
The wiki doesn't recommend it over mozilla.org
It says that **most clients** will work with that address. Including the geeky ones which doesn't support .well-known lookup.

From the Mozilla wiki:
> These details will be autofilled for you in most clients if you enter your full username (e.g. @susan:mozilla.org rather than susan) into the username field. In general it is preferable to do that rather than trying to remember what the homeserver URL is. 

The autofill is done by .well-known lookup. However, they messed it up with their configuration:

![image](https://user-images.githubusercontent.com/26059643/146771524-4c01e24f-ea37-463d-a877-25ec9bf33db0.png)

**Comment by ajbura** [comment]
> https://www.mozilla.org/.well-known/matrix/client

Don’t know whats happening **_www_.mozilla.org** work but not mozilla.org. Not only Cinny, Element also behave same.

**Comment by notramo** [comment]
They have misconfigured their CORS headers. I took the screenshot from devtools while entering mozilla.org in Element.

**Comment by dreaddr** [comment]
Can this be fixed? I can't log in via mozilla.org for some reason.

**Comment by kfiven** [comment]
@dreaddr I believe this needs to fixed from Mozilla side. What we have (mozilla.modular.im) should work for you.

**Comment by notramo** [comment]
I notified them via Matrix.
Once they fix the HTTP headers, it can be switched to mozilla.org in Cinny.

**Comment by ajbura** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1747089 bug request link.
