### ISSUE TITLE
Allow navigating the search mode suggestion via keyboard

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#201]
#### Is your feature request related to a problem? Please describe.

Currently there doesn't seem to be a way to navigate the search mode (<kbd>Ctrl+k</kbd>) suggestion via keyboard. Pressing <kbd>Up/Down</kbd> or <kbd>PageUp/PageDown</kbd> simply takes the cursor to the beginning and the end of the text.

#### Describe the solution you'd like

Allow navigating the suggestions via keyboard (preferably via customizable binding #171).

**Comment by ajbura** [comment]
Actually there's way, <kbd>TAB</kbd> can be used to navigate through the search list.

**Comment by N-R-K** [comment]
@ajbura Thank you, that works. Is there any help or manual page where all the keybindings are documented? If not, then I would suggest adding one.

**Comment by ajbura** [comment]
Well for now we have just Crtl+k for room search panel and Tab for all kind of keyboard accessibility, but I will try to document it in wiki.

**Comment by N-R-K** [comment]
Hmm, I see. I'll close this since my original issue has been addressed.
