### ISSUE TITLE
PGP Signing Key (on Ubuntu Keyserver) is Expired

### ISSUE THREAD

**Issue by TheBlueMatt** [ajbura/cinny#2014]
### Describe the bug

Dunno if there's a more recent version, but the Cinny PGP signing key that's available on `keyserver.ubuntu.com` is expired ("Note: signature key 94330C7A50AFCCF3 expired Thu 02 May 2024 10:03:57 AM UTC").

### Platform and versions

```shell
keyserver.ubuntu.com
```

**Comment by kfiven** [comment]
Seems to be working in action though https://github.com/cinnyapp/cinny/actions/runs/11363854931/job/31608671766#step:9:98

**Comment by TheBlueMatt** [comment]
May just need to be updated on the keyservers.

**Comment by TheBlueMatt** [comment]
Maybe as a part of the actions job do `gpg --keyserver keyserver.ubuntu.com --send-keys $FINGERPRINT`

**Comment by kfiven** [comment]
Should be updated on `keyserver.ubuntu.com` now.
