### ISSUE TITLE
Is it possible to set Hide membership events - on by default for all web version users?

### ISSUE THREAD

**Issue by exdess** [ajbura/cinny#2033]
### Describe the problem

Is it possible to set Hide membership events - on by default for all web version users? And set the default Bubble style?

### Describe the solution you'd like

Is it possible to set Hide membership events - on by default for all web version users? And set the default Bubble style?

**Comment by kfiven** [comment]
We like to keep it that way as room join and leaves are important bit of information that should be broadcasted, otherwise it would feel like room members are appearing like ghosts. Modern is what we design the interface for so we would like to keep it default for the best experience.

**Comment by exdess** [comment]
It would be ideal to put this possibility in the configuration. As I understand it is impossible to change these functions by default?

**Comment by kfiven** [comment]
These are change-able in app settings so we still have options here, what could be improved is persist these settings so that changing sessions doesn't affect them.

**Comment by exdess** [comment]
The ability to set these features by default for all users in the web version would be a great thing.
