### ISSUE TITLE
[Enhancement] Display emoji-only messages using jumbo emoji

### ISSUE THREAD

**Issue by alch-emi** [ajbura/cinny#204]
A lot of chat clients include a feature where messages consisting only emoji (and whitespace) are shown using larger versions of the emoji so that you can see them in more detail.  This behavior is present in (at the very least) Discord, Fluffychat, Mattermost, and I'm sure countless others.

A lot of people, myself included, find that this is a handy feature because it makes the emoji immediately more readable by taking advantage of space that wouldn't have been used by text anyway.

Often, this feature is constrained to a certain number of emoji (say, maybe six), and only to messages without any non-whitespace non-emoji characters, to avoid alignment issues.

I'd like to see a feature like this in Cinny.  To propose specifics:
- Messages containing at most six emoji and no non-whitespace characters would be affected
- Both twemoji and custom emoji would be affected
- Affected emoji would be displayed at 64px
- The implementation should not differ significantly from existing implementations in other apps, to preserve intuitivity

The current behavior is simply to display emoji-only messages (and the emoji within) at the same size as they would appear in a standard message.

Cards on the table, I've actually already written an implementation of this here: https://github.com/Alch-Emi/cinny/tree/big-emoji

I foolishly wrote this implementation before reading the Contributing guidelines, which specify that even minor feature changes should go through an issue before a PR is opened, so I'm opening this issue to discuss feature specifics before the PR is opened.  I'd also like to make it clear that I absolutely understand if this feature is rejected or needs significant changes from my implementation, and will be willing to make those changes if need be.

Thank you for your feedback!

**Comment by ajbura** [comment]
Hey, feel free to make a pull request so I can suggest changes and review. Thanks
