### ISSUE TITLE
Emoji pack import/export

### ISSUE THREAD

**Issue by nekoedges** [ajbura/cinny#2058]
### Describe the problem

It's hard to manually upload every emoji of pack to cinny. And also it's almost impossible to export emoji packs to share them with friends.

### Describe the solution you'd like

It'll be nice to add emoji pack import/export feature. Also, using ready pack format (like Misskey one) will be perfect

### Alternatives considered

Before that my friend used self-written python script to upload them, but he did not share code with anyone and lost access to it.

**Comment by kfiven** [comment]
Duplicate of #940

**Comment by nushea** [comment]
Hi, the implementation only consists of importing emoji, having a way to export them to share them would also be very useful
