### ISSUE TITLE
Other login options is invisible on Cinny Web Client

### ISSUE THREAD

**Issue by shasoka** [ajbura/cinny#2070]
### Describe the bug

On **Web Client**, when `matrix.org` is selected as server, authorization options (e.g. GitHub, GitLab, Google and so one) are **invisible** (I mean there are clickable <a> tags on page, but there are no icons for them):
![image](https://github.com/user-attachments/assets/0a422e3a-bdfe-44b1-8ab9-ed62f34bd60e)

In devtools I can see that all five `GET` requests are being refused with `net:ERR_CONNECTION_CLOSED` exception:
![image](https://github.com/user-attachments/assets/8dd6d0f8-821c-4b42-8b4b-74461e9dbf86)

If I try to manually `GET`, everything works fine:
![image](https://github.com/user-attachments/assets/c05e5406-eeaf-4484-a658-5b895b6ac339)

### Reproduction

1. Go to [Cinny Web Client Login Page](https://app.cinny.in/login/matrix.org)
2. Select [matrix.org](matrix.org) as homeserver
3. Reload the page
4. You don't see icons for external login options :/

### Expected behavior

Icons for external login options are visible

### Platform and versions

```shell
1. OS: Windows 11
2. Browser: Google Chrome 130.0.6723.117 (Stable) x64
3. Cinny Version: 4.2.3
4. Matrix homeserver: matrix.org
```

### Additional context

It's so annoying, that I have to explore the page to find the button I need :(

**Comment by kfiven** [comment]
You probably have some extension blocking them because they are working for me.

**Comment by shasoka** [comment]
Even in clear browser they don't load

And I thought that such addons just block requests, not making them response with `net::ERR_CONNECTION_CLOSED`

**Comment by kfiven** [comment]
net::ERR_CONNECTION_CLOSED means something is wrong with your computer or Internet connection.

**Comment by shasoka** [comment]
From your comments:
- my computer doesn't work properly
- I don't have Internet

And a small tip: `net::ERR_CONNECTION_CLOSED` also occurs when the server abruptly terminates an existing connection

Best wishes! 🤡
