### ISSUE TITLE
Failed to load. undefined on log in attempt

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#2073]
### Describe the bug

I registered for a new account, then upon attempting to log in with my credentials it says "Connecting to Server", "Heating Up", then says: Failed to load. undefined

When attempting to follow steps in another Issue ([Failed to Load. Cannot read properties of null (reading 'NextBatch')](https://github.com/cinnyapp/cinny-desktop/issues/331), by deleting the cached data, it allowed me to return to the register or log on screen. When attempting to log on again it fails, when attempting to register again with the same username it says the username already exists.

### Reproduction

1. Visit [the-apothecary.club](https://cinny.the-apothecary.club/home/)
2. Register. Add username, password, and registration token. Submit.
3. Goes to Fail to Load page (or sometimes a 404 error nginx page).

### Expected behavior

I've never logged into Cinni before or used matrix so I was expecting it to log into the app. 

### Platform and versions

```shell
Windows 11
Cinny version (not sure how to check without being logged in- the crypto-store in IndexedDB says version 11)
the-apothecary.club
Using the web app with Firefox
```

### Additional context

Here is a screenshot. 
![cinny-failed-to-load-undefined](https://github.com/user-attachments/assets/b423d584-6670-4644-81a2-a5a9fa4cfa0f)

**Comment by kfiven** [comment]
Is that Firefox private browsing?

**Comment by kfiven** [comment]
Also, please test the following:

1. try the official instance https://app.cinny.in
2. make sure you are not in firefox's private window
3. try disabling the extensions

**Comment by ghost** [comment]
Going to the official instance fixed it. [https://app.cinny.in/ ](https://app.cinny.in/)

I wasn't in a Firefox private window though I did at one point to test.

Even after disabling all the add-ons I kept getting the same error on the [the-apothecary.club](https://cinny.the-apothecary.club/home/)

**Comment by kfiven** [comment]
Then it looks like issue is with [the-apothecary.club](https://cinny.the-apothecary.club) instance and advise you to take it to them to get fixed.

**Comment by ghost** [comment]
Okay thank you I will

**Comment by kfiven** [comment]
Alright, I'm closing this one then, feel free to comment back if you need any help related to this.
