### ISSUE TITLE
[ISSUE] "Unable to connect" to a homeserver with TLS-enabled listener at port 8448

### ISSUE THREAD

**Issue by menturion** [ajbura/cinny#208]
I just tested Cinny with a homeserver that is configured with a TLS-enabled listener (incl. a PEM-encoded X509 certificate) at port 8448: `https://example.com:8448/`.

Cinny doesn't seem to be able to connect prompting the error: `Unable to connect. Please check your input.`

**Comment by ajbura** [comment]
Hi @menturion , what’s the name of homeserver (if you like to share, you can dm me if it’s private hs)?

**Comment by menturion** [comment]
@ajbura 

Thanks for your prompt reply. 
It is a local HS. So I cannot send you a public address.

**Comment by ajbura** [comment]
Ok, can you try the input with full address. eg. https://example.com:8448 ?

Also look for any errors in console, UI provide generic for all kind of error.

**Comment by menturion** [comment]
Yes, I used the full address in the config file.

Error thrown in the console:
"Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID".

**Comment by ajbura** [comment]
Also have you tried it in element web? Does it connect successfully there?

**Comment by ajbura** [comment]
And what is response in https://example.com/.well-known/matrix/client ?

**Comment by menturion** [comment]
> And what is response in https://example.com/.well-known/matrix/client ?

`https://example.com:8448/.well-known/matrix/client` prompts the Json response with the `base_urls` of `m.homeserver` and `m.identity_server`.

`https://example.com:8448/_matrix/static/` also says that "`It works! Synapse is running`".

**Comment by menturion** [comment]
> Also have you tried it in element web? Does it connect successfully there?

Just tested with latest Element Web v1.9.8. No issues in console, prompting besides others `Using homeserver config`:

```
hsName: "example.com"
hsNameIsDifferent: false
hsUrl: "https://example.com:8448"
isDefault: true
isNameResolvable: true
...
warning: null
```

**Comment by ajbura** [comment]
Ok, have you entered hs with trailing slash (/) when tested in Cinny?

**Comment by ajbura** [comment]
is there any registration flow in your homeserver and what does hs send to register endpoint?

**Comment by menturion** [comment]
This issue already occurs while loading Cinny.

**Comment by ajbura** [comment]
I meant what does https://example.com:8448/_matrix/client/r0/register return.

**Comment by menturion** [comment]
It responds with `{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`.

**Comment by menturion** [comment]
This issue is gone after I added explicitly the port '8448' to the `public_baseurl` param in the `homeserver.yaml`.
Strange that Element Web didn't throw an issue.

I close this issue report due to I don't know whether something has to be fixed/changed within Cinny.
