### ISSUE TITLE
Failed to load. undefined after logging in on Vanadium 

### ISSUE THREAD

**Issue by NarwhalPrince** [ajbura/cinny#2089]
### Describe the bug

On Vanadium, a chromium based browser on GrapheneOS, after entering credentials for the home server, it fails to load.

![Screenshot_20241211-212718](https://github.com/user-attachments/assets/a055c65a-a3aa-4104-b4f3-d427260c2d98)

### Reproduction

1. Open regular browser tab in Vanadium.
2. Enter credentials for matrix.org home server
3. Get error: "Failed to load. undefined"

### Expected behavior

After logging in, it should load the application.

### Platform and versions

```shell
1. GrapheneOS 
2. Vanadium (Chromium)
3. app.cinny.in
4. matrix.org
```

**Comment by kfiven** [comment]
You need to enable JIT (just-in-time compliation) for Cinny in Vanadium's per-site settings.

**Comment by NarwhalPrince** [comment]
Thank you, that resolved the issue.
