### ISSUE TITLE
Feature Request: Read receipts

### ISSUE THREAD

**Issue by kidonsky** [ajbura/cinny#21]
**Is your feature request related to a problem? Please describe.**
No, just an enhancement that already exists in element

**Describe the solution you'd like**
I'd like to see if my correspondent saw my message. Like existent solutions... or a new one :)

**Additional context**
Like this in Element.io
![read-notig](https://user-images.githubusercontent.com/12858135/127642442-f5824f5f-1477-446e-ba58-1d886525292f.png)

Thank you !

**Comment by farribeiro** [comment]
These are the receipts and don't forget the presence/status support

**Comment by farribeiro** [comment]
Related issue #28

**Comment by ajbura** [comment]
Done https://github.com/ajbura/cinny/commit/683ce431dbb24a8836c80f79280252dfc6beaa8e
