### ISSUE TITLE
Mention cycling uses enter to confirm instead of tab

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#216]
This creates a tad of anxiety for me, as on other platforms, Tab usually means *confirm* for these kinds of choices.

I suggest making mention select use a different cycle key, like left or right, to select the right user. Enter is too linked to sending a message, so users might be tentative to use it.

**Comment by N-R-K** [comment]
> This creates a tad of anxiety for me

The same problem exists for emojies and `/` commands.
