### ISSUE TITLE
Decrypt message history with Security Key/Paraphrase

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#22]
Splitting from #4

**Comment by farribeiro** [comment]
I think the @ajbura doing all adjacents features about that issue what you point

Then I imagine is a duplicated

**Comment by kfiven** [comment]
@farribeiro No it's different. #4 had two features request; one about decrypting by exporting/importing keys and another by using key/backup. We are only doing the former one in #4 so I created this one.

**Comment by viasux** [comment]
I think this is the one thing keeping me from recommending cinny to any new users. Most people don't understand or know how to "convert keys" to another session or why they even would need to. Even with element, when I invite people to talk on matrix, they usually end up deleting their original session, in favor of a new one, not realizing that they haven't backed up their keys (or even understanding what that means). I think there needs to be support for key backup, along with some sort of quick explanation of why it's needed, and why it may be a bad idea to not back up your keys. (a prompt or something when you first register an account through cinny, or log into an account without key backup enabled). This is really hard to balance on, as you don't want to discourage the user from using the app (or clicking off of the notification without reading it) with an information overload, however it's important info.

**Comment by viasux** [comment]
I see this is on the roadmap, so I'd like to clarify that I think it's important users can both decrypt their message history with secure key backup, as well as letting *new* users *set up* secure key backup.
