### ISSUE TITLE
User profile wonkiness

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#221]
There's a few criticisms about the User Profile i have so far;

![image](https://user-images.githubusercontent.com/22740616/147752495-a0cec25e-ca40-4864-970a-f95c23fa558d.png)

Currently, the top title shows all three parts (displayname, "in", and the room) in the same text format.

I also think that the "sessions" being dynamic-length spans that dont arrange in a neat row is a bit off-putting.

---

Suggestion; Seperate the "in this room" and "the user in general" parts from eachother, i.e. add a seperator that adds "in <room>", after which it shows a room-specific avatar or nickname (if the user has one), and the role the user has. The top part could show their server-reported profile and sessions (which can be different from the profile the user has in the room).

**Comment by ajbura** [comment]
In 74464992e61467ee6e05624c634bb7da7174560f I have removed the ‘displayname in’ part as that is already present below, so only thing left is room name in header.

About the sessions chip, they are now inside a card which doesn’t cause the profile modal to adjust accordingly and feels more stable now. I hope these are enough to solve the issue you had.

**Comment by ajbura** [comment]
Closing per above cmt.
