### ISSUE TITLE
Version 1.6.1 was not published in docker hub

### ISSUE THREAD

**Issue by rakshazi** [ajbura/cinny#226]
#### Describe the bug
[Docker image](https://hub.docker.com/r/ajbura/cinny/tags) doesn't have the 1.6.1 tag/release

#### To Reproduce
1. Check docker image tags

#### Expected behavior
Docker image should have 1.6.1 tag

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 3.22]

**Comment by ajbura** [comment]
https://hub.docker.com/layers/ajbura/cinny/v1.6.1/images/sha256-ac25e19a7586558800f55aff3e73ddda18e0ac31fe2455c8e7fe94df533b6a15?context=explore ? @rakshazi

**Comment by rakshazi** [comment]
Sorry, seems like some weird caching - now I see 1.6.1 tag, but it was not here when I posted the issue (about 30 mins ago)
