### ISSUE TITLE
Focus Emoji `<Input/>` on modal open

### ISSUE THREAD

**Issue by jasikpark** [ajbura/cinny#229]
#### Is your feature request related to a problem? Please describe.

When using the emoji picker, I usually want to immediately search for an emoji or [select from recently used emoji](https://github.com/ajbura/cinny/issues/194) 

#### Describe the solution you'd like

When ever the emoji picker modal is opened, I want the input to be cleared (or the text that is in there selected) and focused so I can immediately start typing

**Comment by kfiven** [comment]
Duplicate of #62 ?

**Comment by jasikpark** [comment]
looks like it!

**Comment by jasikpark** [comment]
closing as a duplicate of #62
