### ISSUE TITLE
Inline Code markdown not applied

### ISSUE THREAD

**Issue by TheBlueMatt** [ajbura/cinny#230]
When typing text surrounded by `s, most other clients and messengers map it as inline code and render it with fixed-width. Cinny treats it as normal text however. It would be nice if Cinny mapped it as "inline code" consistent with other markdown rendering/interpretation.

**Comment by kfiven** [comment]
You need to enable markdown in settings.

**Comment by TheBlueMatt** [comment]
Ah, duh. Should that be default given it seems to be the default on most other messaging platforms?

**Comment by ajbura** [comment]
Done. in f310196937e4a8bee74bf0e12645c0fb86c65ce6 we have enabled markdown by default.
