### ISSUE TITLE
[Feature Request] Add support for `/me`

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#233]
Element and a couple other clients support `/me` action. For example `/me waves` would be sent as `* <my_name> waves`. Would be nice to have this feature on cinny as well.

**Comment by vwkd** [comment]
This overloads the chat input field with another command (text substitution). Instead this could be a command in a command palette. See #129

**Comment by N-R-K** [comment]
No, `/me` is a very common command among various (IRC as well as Matrix) clients. It makes no sense for something like that to go to some other palette. You're supposed to type it out into the chat box, like this: `/me laughs`.
