### ISSUE TITLE
[Feature Request] One click login

### ISSUE THREAD

**Issue by gleachkr** [ajbura/cinny#234]
#### Is your feature request related to a problem? Please describe.

I'd like to be able to onboard a large group of non-technical users, with minimal friction. The usual sign up process (select a server, choose SSO method, authenticate, join a room) tends to lose a few people along the way.

#### Describe the solution you'd like

It would be amazing to be able to share a single link (something like `app.cinny.in?server=...` with some query parameters, perhaps) which Cinny can use to initiate an SSO login flow with a given server, and then after login, invite the user to join a given room.

So, for example, you could distribute a link to a class of students. They could click it and be directed to authenticate with univesity SAML. Then after authentication, they'd be invited to join the discussion for a class they're part of.

**Comment by kfiven** [comment]
This is done as cinny navigation can be controlled by URL. We also added featuring Rooms inside explore tab, so rooms can be featured for onboarding there and a direct link can be provided.

**Comment by zacharymichaelmoore** [comment]
EDIT: after discussion in the chat server this is a backend implementation feature and so this feature request is more aligned with a `Will Not Address` status. Cinny is focused on client and leaves server implementation to your choice. Maybe someone else can explain it better than me but that's what I understood.

~~
Can someone explain to me how this is done? 
I am seeking to understand the current architecture :). 

The current process of onboarding a new user:
Step 1: I send the link `https://{MY_DOMAIN}/register/{MY_HOME_SERVER}`
Step 2: The home server is prefilled but the user must now enter username, password, and registration token

Expected process (which aligns with the original ticket request
Step 1: I send the link `https://{MY_DOMAIN}/register/{MY_HOME_SERVER}`
Step 2: The home server is prefilled and the user must now only enter username and password

Possibly able to help out. I'm looking forward to your reply @kfiven 

Thanks!
Zach
~~

**Comment by ajbura** [comment]
https://github.com/cinnyapp/cinny/issues/2506 for further improvements
