### ISSUE TITLE
[Feature] "Jump to mentioned" button 

### ISSUE THREAD

**Issue by mizzunet** [ajbura/cinny#235]
#### Is your feature request related to a problem? Please describe.
Somewhat. Once, I was mentioned in a group and lot of messages are after that, it's hard to get to the mentioned message.
![image](https://user-images.githubusercontent.com/10193999/149610970-3f895847-de9e-4457-9662-a61b2d319909.png)

#### Describe the solution you'd like
A button ,just like Jump to unread, for the mentioned message.

![image](https://user-images.githubusercontent.com/10193999/149610892-f2b947df-8118-467c-a99f-1c0d140a7c7e.png)

#### Describe alternatives you've considered
Manually scrolling and finding it.

**Comment by tezlm** [comment]
imo, an alternative/addidional feature would be to have a way to view all mentions, with a button to jump each message

for example: "notifications" on element and "inbox" on discord.

**Comment by LoneWolfHT** [comment]
This would be really nice to have, I'm currently having to switch over to Element to check my mentions

**Comment by kfiven** [comment]
Since now we have Inbox containing all notifications, this is now resolved.
