### ISSUE TITLE
URL detection includes '>' in link

### ISSUE THREAD

**Issue by reinerh** [ajbura/cinny#236]
#### Describe the bug
I'm using a matrix twitter bridge which regularly posts URLs into a room.
The URLs are surrounded by `<...>`, but cinny thinks the closing `>` is part of the link.
See attached screenshot, where the closing `>` is also colored in blue.

#### To Reproduce
1. Go to any room.
2. Post a link surrounded with `<>`, e.g.:  `<https://example.com>`
3. The link is now invalid (and cinny also appends a `;` at its end)

#### Expected behavior
`>` should not get detected as part of the URL, so that when you click on the URL, you land on the actual target.

#### Screenshots
![cinny](https://user-images.githubusercontent.com/3106950/149618650-fe997f4a-b834-450c-b42c-1c371641936f.png)

#### Desktop (please complete the following information):
 - OS: Linux
 - Browser: Firefox 96.0
 - Version: Cinny 1.6.1

#### Additional context
I also checked the behavior of Element, and there `>` is not part of the link.

**Comment by ajbura** [comment]
This is an issue with Linkifyjs https://github.com/Hypercontext/linkifyjs/issues/350

**Comment by kfiven** [comment]
Fixed in #665
