### ISSUE TITLE
When rooms are loading info, it's unclear it's even loading.

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#242]
#### Is your feature request related to a problem? Please describe.
When rooms are loading info, it's unclear it's even loading. There's no indication that it's loading anything.
#### Describe the solution you'd like
I think that some sort of animation when you click on a room that hasn't been fully loaded would be nice.

**Comment by kfiven** [comment]
Given we now have the connecting header and placeholder while loading in room timeline, this is resolved.
