### ISSUE TITLE
Option for spaces to appear similar to discord guilds.

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#245]
#### Is your feature request related to a problem? Please describe.
I'm unsure why this isn't an option/default. The current "folder"-ish system is a fair bit confusing and imho there's no reason to change the established, functional design, which is successful in discord, slack, etc.

There's already a ton of _unused_ space there, so _freeing up space in the rooms list_ for rooms which aren't in a space would just make sense to me.

![image](https://user-images.githubusercontent.com/47131867/150396799-d191c823-a98b-4def-a04d-94edc7f7bad6.png)

#### Describe the solution you'd like
Add an option / default to showing spaces in the left hand bar as icons, similar to the "home" and "people" icons, but below those icons. There's already a dividing line on the top and bottom.

**Comment by kfiven** [comment]
Are you aware that you can pin spaces to sidebar? The reason for breadcrumb navigation is simple, Element tried putting spaces in Sidebar and it's a mess (fyi I have read somewhere that Element is also going to switch space navigation somewhat similar to Cinny). Discord has a different kind of setup, they don't have subservers so they can only show server list in sidebar.

**Comment by kfiven** [comment]
Yeah found the element link https://github.com/vector-im/element-meta/issues/56 #2.5

**Comment by viasux** [comment]
> Are you aware that you can pin spaces to sidebar? The reason for breadcrumb navigation is simple, Element tried putting spaces in Sidebar and it's a mess (fyi I have read somewhere that Element is also going to switch space navigation somewhat similar to Cinny). Discord has a different kind of setup, they don't have subservers so they can only show server list in sidebar.

OH! This is wonderful, I didn't know you could pin spaces. I still believe that the reason this doesn't work in element is because of element's plethora of other issues with their user experience. I really really like how this is implemented in cinny, and I believe it would be a good default.

But even if it isn't, I believe spaces should be removed from the 'breadcrumb' listing when they're added to the sidebar navigation (as part of the reason putting them on the sidebar in the first place is to decrease visual clutter, keeping them in 2 places seems silly to me). I also can't find a way to reorder the spaces without unpinning and repinning, so that would be nice.

I personally run into the issue of having too much clutter/too many rooms for me to do what I need to with the current setup. Spaces being in a different column _just makes sense to me_, and it would decrease user friction when trying to find a room, since the room section would be dedicated to _just rooms_. Again, when no spaces are pinned, the pinned section is completely unused white space, I see no downside to just placing spaces there.

**Comment by kfiven** [comment]
Removing pinned space from Home tab create more issues, for example you can even pin subspaces and if we remove that from home tab, we are essentially saying this space isn’t child of it’s parent space, which isn’t true.
But to decrease noise we do one thing that notifications of pinned spaces won’t show under home tab anymore.
Also when you’ll open pinned spaces from sidebar there’s won’t be a breadcrumb navigation on top (which also reduces some noise).

Pinning spaces is somewhat like room favourite, since area of sidebar is limited, we only want it to utilised for spaces that matters most and extra spaces can live under home tab (you also don’t need to exit a space to remove it from sidebar, which is also extra benefit).

For rearranging there’s already an issue, see #153 .

**Comment by viasux** [comment]
> 

Yes, the sidebar's space is limited, but if it's scrollable, it should be technically infinite (I don't have enough spaces for it to be) and implementing something like discord's "server folder" feature could solve almost all friction in that aspect

As for the breadcrumb issue with the child space, I think that there's a way to work around that, I'm just too tired to come up with anything right now lol

Yeah, just for me, having to scroll through all like 10 of my spaces before I even see any of my rooms causes a lot of friction. I can't imagine how bad that would be for someone with a significantly larger number of spaces they're in.

I just don't see the appeal of the breadcrumb design, if the "discord server"-like guild system is perfected.

**Comment by kfiven** [comment]
Yeah I understand the discord’s folder structure. We also have plans for that with drag to reorder, but the key issue here is subspaces. 
* We don’t want to put them in sidebar (mistake Element did).
* We also don’t want to treat Main space and Sub-spaces differently (that makes to two UX for same thing).
* Some even don’t want to see Main space in sidebar but may want to see Subspace. (For example in Matrix community space, I just want the Clients space because that’s where Cinny room is).

**Comment by viasux** [comment]
> Yeah I understand the discord’s folder structure. We also have plans for that with drag to reorder, but the key issue here is subspaces.
> 
>     * We don’t want to put them in sidebar (mistake Element did).
> 
>     * We also don’t want to treat Main space and Sub-spaces differently (that makes to two UX for same thing).
> 
>     * Some even don’t want to see Main space in sidebar but may want to see Subspace. (For example in Matrix community space, I just want the Clients space because that’s where Cinny room is).

Couldn't you just use the breadcrumb system, but *only* for sub-spaces? I think that would work well, as it would take up less space and be much more situational. I'd have to see it in action though.

About "not treating them differently" I'd argue that they are inherently different, although I see the argument.

I think it would be nice if joining a space, which happens to be in another space wouldn't automatically move it there, it's a bit confusing but that's a matrix backend thing. Like I could join "space x" and then join "space y" without knowing that space x is in space y, and then space x would randomly (from a user perspective) be moved to space y, which is hella confusing.

**Comment by kfiven** [comment]
> Couldn't you just use the breadcrumb system, but _only_ for sub-spaces? I think that would work well, as it would take up less space and be much more situational. I'd have to see it in action though.

Yeah, we can but that doesn't solve the issue, as I said some people just want to follow a subspace but not the mainspace.

Also why I said we should not treat mainspace and subspace differently because suppose I joined the Clients space and that will appear in sidebar and then I also joined Matrix Community (which is mainspace of Clients), now we have to remove Clients from sidebar and then pin Matrix Community to sidebar. This will be more confusing than just putting everything in home tab and giving people the choice of pinning (and grouping in future).

**Comment by code3z** [comment]
Yes, please do it discord style. [Copying other sites IS good UX.
](https://lawsofux.com/jakobs-law/)

The matrix equivalent of servers in the sidebar would be spaces. I don't like the concept that spaces only appear when pinned, I think they should always be pinned, but users can change the order. Individual rooms can be hidden from the sidebar by default, but not spaces. Then sub-spaces are represented by a section in the sidebar like in discord. Sub-sub-spaces could be a subsection in the sidebar, and so on.

![image](https://user-images.githubusercontent.com/77302900/151684733-f0ef2a87-ebc4-4bf3-b685-c02401626674.png)

**Comment by ajbura** [comment]
Spaces looks similar to Discord servers but they are not. _Technically space is a matrix room_ in which you can define that certain number of room should appear together. So the reason to keep them in room list is simple: they are rooms with special powers. (Also kfiven explained the issues with great depth.)

Also it’s not like that we haven’t thought of going discord way, it’s great but when spaces nesting go more than 2 level, it starts to break down. 
For example: A space > B space > C space. How we will show C space with discord way?

**Comment by viasux** [comment]
> Spaces looks similar to Discord servers but they are not. _Technically space is a matrix room_ in which you can define that certain number of room should appear together. So the reason to keep them in room list is simple: they are rooms with special powers. (Also kfiven explained the issues with great depth.)
> 
> Also it’s not like that we haven’t thought of going discord way, it’s great but when spaces nesting go more than 2 level, it starts to break down. For example: A space > B space > C space. How we will show C space with discord way?

Couldn't you have nested folders?

I also think that it could be a good idea to just neglect nested spaces as a feature until they're more developed and there's a better way to implement them. Imo this aspect of user experience is more important than the functionality nested spaces gives. Couldn't you just show nested spaces as completely separate spaces, at least temporarily until a better solution is found?

I also find it weird how the act of nesting a space isn't completely a user-sided option. Kind of weird to me that the administrator of a space can choose to nest it, even if a user doesn't want that..

**Comment by code3z** [comment]
> Couldn't you have nested folders?

Yeah, that’s what I was saying…

Spaces are just discord servers with some additional customization like nesting.

**Comment by kfiven** [comment]
Do we still need this after option to pin spaces at one place and with categorized space feature?

**Comment by code3z** [comment]
> Do we still need this after option to pin spaces at one place and with categorized space feature?

Yeah

**Comment by kfiven** [comment]
So with those features it isn't similar to discord guilds? If yes why so? @code3z

**Comment by code3z** [comment]
@kfiven they’re similar but discord has a better UI

**Comment by code3z** [comment]
Rooms in spaces in spaces in spaces is confusing, sorted rooms in spaces is better.

**Comment by kfiven** [comment]
Have you checked the app after v1.8.0 release @code3z ? Please see categorized subspace option.

**Comment by code3z** [comment]
> Have you checked the app after v1.8.0 release @code3z ? Please see categorized subspace option.

Alright I’ll check

**Comment by kfiven** [comment]
Ping pong? Any further comments folks or should we consider it resolved?

**Comment by viasux** [comment]
> Ping pong? Any further comments folks so should we consider it resolved?

I don't see what 1.8.0 changed in relation to this

**Comment by ajbura** [comment]
Option to appear subspaces as categories instead of folder system.

**Comment by viasux** [comment]
> 

Where is this option?

**Comment by ajbura** [comment]
<img width="534" alt="Screenshot 2022-03-26 at 7 14 56 PM" src="https://user-images.githubusercontent.com/32841439/160242271-a0478308-990b-434d-ac10-2aa378e12552.png">

**Comment by ajbura** [comment]
Closing as there is now an option.
