### ISSUE TITLE
Placeholder profile picture

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#247]
#### Is your feature request related to a problem? Please describe.
Currently, when an avatar hasn't loaded yet, it shows up as a cut off "Av"

#### Describe the solution you'd like
Having a placeholder profile picture would help decrease visual clutter

#### Additional context
Un-loaded avatars currently look cluttered to me, example:
![image](https://user-images.githubusercontent.com/47131867/150414507-d0f3e548-0415-4e61-b82f-d2903fa1ba12.png)

**Comment by kfiven** [comment]
Done in f0c9a458bb69d9f9e38c95636cac52c8ccd3d662

**Comment by viasux** [comment]
This appears to still be happening in 1.7.0.

![image](https://user-images.githubusercontent.com/47131867/151679277-b6355130-4c3d-4ae6-ad16-4cdd6878e93b.png)

**Comment by viasux** [comment]
> This appears to still be happening in 1.7.0.
> 
> ![image](https://user-images.githubusercontent.com/47131867/151679277-b6355130-4c3d-4ae6-ad16-4cdd6878e93b.png)

@kfiven (sorry for @, just can't re-open the issue and im unsure if that comment gave you a ping)

**Comment by kfiven** [comment]
Could you please test the same on app.cinny.in with a test account?

**Comment by viasux** [comment]
> 

yeah, I'll do so in a bit!

**Comment by kfiven** [comment]
This is also specific to firefox based browsers. Firefox show `avatar` until picture is loaded, if it fails then the broken fallback comes.

So fallback works but firefox does something weird when trying to load avatar.
