### ISSUE TITLE
Sometimes sent messages take up to 10 seconds to appear

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#249]
#### Describe the bug
Sometimes sent messages take up to 10 seconds to appear

#### To Reproduce
1. Talk in a chat
2. Keep talking
3. Eventually your messages stop showing up immediately (sometimes)

#### Expected behavior
Expected sent messages to appear immediately.

#### Screenshots
I can try to take a video sometime not right now

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Linux
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.6.1
 - Matrix homeserver: [e.g. matrix.org] yiff.social

**Comment by kfiven** [comment]
Maybe related #185

**Comment by viasux** [comment]
> Maybe related #185

To my memory, messages are received fine, refreshing does fix it though.

It also does seem to progressively take longer and longer to show sent messages until you refresh.

**Comment by viasux** [comment]
> Maybe related #185

I believe this is a duplicate of 185, closing!
