### ISSUE TITLE
Time is incorrect (*possible browser issue)

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#250]
#### Describe the bug
The time (timestamps & such) seems to be 4 hours behind.

#### To Reproduce
1. Use LibreWolf
2. Look at a read receipt
3. See time being different from computer/local time.

#### Expected behavior
The time should be correct

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Linux
 - Browser: [e.g. chrome, firefox] Libre Wolf
 - Version: [e.g. 3.22] 1.6.1
 - Matrix homeserver: [e.g. matrix.org] yiff.social

#### Additional context
This could be a browser issue (librewolf) - I'm unsure how time is calculated, but if it's calculated by location, perhaps the browser isn't being pinged for perms? I'd assume it's system clock so maybe it's just a problem with librewolf not sharing that.

**Comment by kfiven** [comment]
Unix timestamp comes with events and that is converted by the browser to local time, so yeah it looks like your browser is doing something weird. 

Maybe try a different browser to pin down if it's indeed browser or your machine?

**Comment by viasux** [comment]
> 

closing because this is likely a browser issue, sorry!
