### ISSUE TITLE
Add notification on favicon in browser tab

### ISSUE THREAD

**Issue by ajbura** [ajbura/cinny#251]
a notification indicator in the favicon would be a great and necessary addition. : ) by @and1:matrix.org. Also related #173 #182

**Comment by C0ffeeCode** [comment]
I think we should use [Badging API](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API) instead.

**Comment by iambumblehead** [comment]
cinny's favicon never indicates any notification here.

cinny's favicon always looks the same. By comparison, discord's favicon does display a number corresponding to the message events for my user.

so, for me, this feature appears to be not working
