### ISSUE TITLE
Clicking more than once on the emoji picker selects

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#254]
#### Describe the bug
When you click more than once (even relatively slowly), it selects (like a double click on text)

#### To Reproduce
1. Click on the emoji clicker
2. Click an emoji more than once

#### Expected behavior
I expected this bug to not occur and for the emoji to just send. This bug seems to be purely visual though, it still functions technically.

#### Screenshots
https://user-images.githubusercontent.com/47131867/150753478-2dd59437-1da6-4815-a487-1642b1e7fd15.mp4

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Windows 10
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.6.1
 - Matrix homeserver: [e.g. matrix.org] yiff.social

**Comment by ajbura** [comment]
This is not happening for me. Chrome on windows.

**Comment by kfiven** [comment]
@ajbura its specific to firefox based browsers and I am also able to reproduce this on firefox latest.
