### ISSUE TITLE
Erroneous read reciept behavior

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#258]
#### Describe the bug
The room says it's been read at the bottom of the screen, but the newest and past messages have not been read yet.

#### To Reproduce
Not sure how (see vid)

#### Expected behavior
I expected that the latest message would be read if the room is telling me the conversation has been read.

#### Screenshots
https://user-images.githubusercontent.com/47131867/150929896-3f992afb-2fb9-43f9-985f-bf31a6d9fd0e.mp4

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Windows 10
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.6.1
 - Matrix homeserver: [e.g. matrix.org] yiff.social

**Comment by viasux** [comment]
Checking element shows that the conversation is not read.

Also, this persists after refreshing

**Comment by kfiven** [comment]
Is room encrypted?

**Comment by viasux** [comment]
> Is room encrypted?

Yes

**Comment by ajbura** [comment]
I have fixed this in #227

**Comment by ajbura** [comment]
Closing as release is live.

**Comment by ajbura** [comment]
Feel free to reopen if it persist.
