### ISSUE TITLE
User directory "No result found!" in large rooms

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#261]
#### To Reproduce
1. Go to a large room
2. Go to the users section
3. See error

#### Expected behavior
Expected to see the users in the room

#### Screenshots
![image](https://user-images.githubusercontent.com/47131867/151180971-9546e102-304a-4325-8c7c-b3061fafcace.png)

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Windows 10
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.7.0
 - Matrix homeserver: [e.g. matrix.org] yiff.social

#### Additional context
Could be solved from adding a "refresh listing" button possibly?

**Comment by ajbura** [comment]
This appear for only few milliseconds when loading room users so we should show some other msg when loading the list.

**Comment by viasux** [comment]
> This appear for only few milliseconds when loading room users so we should show some other msg when loading the list.

Alright, my homeserver is a bit slow, so it appears for a while, didn't realize that!
