### ISSUE TITLE
Url's which end in a '_' do not get interpreted correctly.

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#262]
#### Describe the bug
Url's which end in a '_' do not get interpreted correctly.

#### To Reproduce
1. type a url which ends in an underscore
2. send message

#### Screenshots
![image](https://user-images.githubusercontent.com/47131867/151192773-a9992b8c-27d6-48f9-b2ac-d20935de1a1b.png)

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Windows 10
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.7.0
 - Matrix homeserver: [e.g. matrix.org] yiff.social

**Comment by kfiven** [comment]
Related to linkifyjs. Also #236

**Comment by kfiven** [comment]
Fixed in #665
