### ISSUE TITLE
Allow collapsing the member panel

### ISSUE THREAD

**Issue by bbhtt** [ajbura/cinny#270]
#### Is your feature request related to a problem? Please describe.

On small screen sizes the member panel and the room panel on both sides makes the actual chat area quite narrow, it'd be nice to be able to collapse and hide the members panel to the right with a click of a button.

#### Describe the solution you'd like

Have a button to allow collapsing or at least resizing the member panel.

#### Additional context

**Comment by kfiven** [comment]
There's already a button to hide member panel in upper-right corner of room.

**Comment by bbhtt** [comment]
Ah right, thanks. I completely missed the "people" icon. Closing.
