### ISSUE TITLE
Read Receipts wording is confusing.

### ISSUE THREAD

**Issue by Sleuth56** [ajbura/cinny#28]
**Is your feature request related to a problem? Please describe.**
The wording for read receipts makes it appear that people listed are getting notifications for messages and not that it's just a read receipt which is what it actually is.

**Describe the solution you'd like**
I think there are two possible solutions. Lozenge on matrix talked about the intent was for people to know who is most active in chat. If you wanted to keep this functionality a mark next to the people or darkening of people that aren't deemed to be following in the people section on the right would do that while being less confusing. Then remove the `are following the conversation.` part under the compose bar. 

The second solution would to just remove the `are following the conversation.` part and leave it at that.

**Comment by farribeiro** [comment]
Related issue #21

**Comment by ajbura** [comment]
https://github.com/ajbura/cinny/commit/683ce431dbb24a8836c80f79280252dfc6beaa8e Adds a functionality to see who actually saw the message and explicitly says "Seen by". So @Sleuth56 please have a look and see if it's still confusing.

**Comment by ajbura** [comment]
Closing as it’s been long time without any response. Feel free to reopen if you think it’s still confusing.
