### ISSUE TITLE
Add Channel Folder Support

### ISSUE THREAD

**Issue by caughtquick** [ajbura/cinny#29]
**Is your feature request related to a problem? Please describe.**
Support for "local" folders for organization of multiple channels.

**Describe the solution you'd like**
-
Adding support for folders and in the future maybe spaces.

**Describe alternatives you've considered**
Support for spaces, channels organized by spaces and allowing the creation of a space within the client.

**Comment by ShadowJonathan** [comment]
What do you mean with "folders"? I think Spaces has the exact use-case you're looking for, though maybe private spaces could be rebranded as "folders" like that.

If you mean sidebar folders (like discord), then please elaborate on it like that.

**Comment by InfiniteWorldSoftware** [comment]
Yes, especially because Spaces already includes the functionality for "folders" if you use subspaces.

**Comment by caughtquick** [comment]
Would it be possible to create a space of already existent channels?

**Comment by ShadowJonathan** [comment]
Yes, in matrix, you can create spaces which contain existing rooms. I guess cinny just doesnt offer this functionality yet.
