### ISSUE TITLE
Ability to manage Room Settings

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#3]
Currently there is no way to view or manage a room's settings (room name, aliases, permissions, etc).

**Comment by ajbura** [comment]
Sub-issues: 
* [x] #90 
* [x] 8c55f38b0780f90a2ebf4113f2e011425b210d50 Manage permissions
* [x] 0ddeb02d233e3dc337b6102a1d003c4a50322c40 History visibility 
* [x] 54635bf0d3e1dcd8b81645dbfb818b7983898538 Room addresses 
* [x] d6b5f92d6cfbe0f18a07afca23180c520802126a General settings
