### ISSUE TITLE
Mentions don't seem to work properly (at least with other clients)

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#319]
#### Describe the bug
Mentions don't seem to work properly (at least with other clients)

#### To Reproduce
1. Type `@` then hit tab and enter to select someone to mention
2. Send the message
3. I don't believe they get notified (it just sends their plaintext name)

#### Expected behavior
I expected it to mention the user.

#### Desktop (please complete the following information):
 - OS: [e.g. Windows, MacOS] Windows 10
 - Browser: [e.g. chrome, firefox] LibreWolf
 - Version: [e.g. 3.22] 1.7.0
 - Matrix homeserver: [e.g. matrix.org] yiff.social

**Comment by ajbura** [comment]
It does ping users, just don’t make that fancy pill which is tracked in #19

**Comment by viasux** [comment]
> It does ping users, just don’t make that fancy pill which is tracked in #19

sorry, didn't see that!
