### ISSUE TITLE
Add "made for matrix" or "matrix" at the footer of the login screen

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#32]
And make "matrix" link to matrix.org or it's FAQ

Maybe/or with this logo instead of "matrix"; https://github.com/vector-im/logos/blob/master/matrix/matrix-logo.png

Or, use the ["made for matrix" badge](https://matrix.org/docs/guides/made-for-matrix-badge-guidelines)

**Comment by farribeiro** [comment]
The foundation logo

**Comment by ShadowJonathan** [comment]
(The reason i'm requesting this is to make sure users at least see the matrix logo, or a mention of matrix, *once* before starting to use the client, so they may be introduced to the wider ecosystem of matrix, and not get tunnel-visioned to Cinny specifically.)

**Comment by ShadowJonathan** [comment]
Semi-related issues; https://github.com/vector-im/logos/issues/7, https://github.com/vector-im/logos/issues/8
