### ISSUE TITLE
Codeblock syntax highlighting

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#324]
#### Is your feature request related to a problem? Please describe.

It's kind of annoying when somebody posts code in a codeblock and there's no syntax highlighting or copy to clipboard button.

Element:
![element](https://user-images.githubusercontent.com/66189242/154839353-a6434191-f124-442e-8de4-988ac4e4c413.png)

Cinny:
![cinny](https://user-images.githubusercontent.com/66189242/154839348-f7f58523-ac51-41bb-ae03-da9cc9a68d16.png)

Github:
```go
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

#### Describe the solution you'd like

Implement some type of syntax highlighting for codeblocks.

#### Additional context

I've heard highlight.js is popular https://github.com/highlightjs/highlight.js/

**Comment by ginnyTheCat** [comment]
highlight.js is really bloated and just overall awful to use. Prism is a much better choice.
I already made an implementation a while ago using Prism, but did not know which colors to go for (keywords, strings, etc.).

**Comment by deanveloper** [comment]
I mean, anything is better than nothing. It can always be changed later if it's ugly

**Comment by ajbura** [comment]
> highlight.js is really bloated and just overall awful to use. Prism is a much better choice. I already made an implementation a while ago using Prism, but did not know which colors to go for (keywords, strings, etc.).

We can use css variable for color? Which will be good to change code colors based on theme.

**Comment by natsukagami** [comment]
> We can use css variable for color? 

Someone made a Prism theme with CSS variables here, https://github.com/antfu/prism-theme-vars
