### ISSUE TITLE
Feature Request: Server disconnection message

### ISSUE THREAD

**Issue by kidonsky** [ajbura/cinny#35]
#### Is your feature request related to a problem? Please describe.
Matrix is brilliant. But if I use a homeserver, its availability is not perfect.
It may be unreachable (down or ipv6-only problem).

In this case, I would like to see an big message to prevent me that I can not use it.

#### Describe the solution you'd like
A big message to advertise me for this problem

#### Additional context
Today, I just can "use" the client. But I know that it does not work just because I test it with another matrix.org account.
(ipv6-only problem)

Thanks !

**Comment by ajbura** [comment]
Hi, Is there any other client which does this? If yes, how can I check it.

**Comment by kidonsky** [comment]
I remember that I saw several times during last years (maybe less now) this message while matrix.org was down or near to down.
So I think that it would be useful for all to know that its server can not be used
