### ISSUE TITLE
Feature Request: Show full description popup when clicking it

### ISSUE THREAD

**Issue by arche-dev** [ajbura/cinny#37]
#### Is your feature request related to a problem? Please describe.

Right now it's impossible to read the full description in rooms, it just ends in `...` if its too long.
![image](https://user-images.githubusercontent.com/66189242/127861253-1d446671-794d-4f2a-9dc1-154b05330443.png)

#### Describe the solution you'd like

I would like a way to display the full description, when clicking the description text and then showing a popup:

![image](https://user-images.githubusercontent.com/66189242/127862165-8a920905-5b6d-499b-b320-2e28d97005d9.png)

**Comment by vwkd** [comment]
Please not a pop up. Pop ups block the rest of the UI completely.

Remember when iOS used pop ups for everything? Notifications that should have been a banner?

Instead consider a “view more” button that expands downwards and a “view less” that contracts upwards.

**Comment by ajbura** [comment]
Full room description in now available in room settings.
