### ISSUE TITLE
`Ctrl+k` doesn't update sidebar

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#374]
#### Describe the bug
If you're inside space `A` in the sidebar, and use <kbd>ctrl+k</kbd> to go to a room on space `B`, then the sidebar still stays on space `A`.

#### Expected behavior
The sidebar should be in sync with the current room.

**Comment by Mapledv** [comment]
I am interested in working on this issue. Is there any extra information I need to know before getting started?

**Comment by ginnyTheCat** [comment]
This is cause by the recently added blurhash support. It stacks the image ontop of the blurred version to make do this. I did not think of images with transparency :sweat_smile:.

The culprit lies in this line:
https://github.com/cinnyapp/cinny/blob/04f910ee03e3e0ba9fcb4265bb6b799449718060/src/app/molecules/media/Media.jsx#L179

**Comment by ajbura** [comment]
@Mapledv  If we can create a mapping of selected space to selected room id(if that selected space has this room as child). We can call this map `selectedSpaceToRoomId`.
When user select a space we can automatically select the selected room (by looking into mapping) or if there is not any we can select by activity. (This will fix #353)

Now that we have this mapping and whenever we open a room (lets say RoomA) (from ctrl+k or etc):
1. we can get parents of RoomA using `roomlist.roomIdToParents` map;
2. we will filter these parent spaces if `selectedSpaceToRoomId` point to RoomA.
3. now if we have filtered array.length > 0 we can open the first.
4. else we can open first from unfiltered parents.
5. or if there is no parents we can open home or directs message tab

To make it more perfect we can add a timestamp in `selectedSpaceToRoomId` so we select the space which has latest timestamp (^ in point 3).

Let me know if you have any better ideas
