### ISSUE TITLE
Pinging/Tagging users similar to Element

### ISSUE THREAD

**Issue by x3221** [ajbura/cinny#398]
### Describe the problem

While using Element, we were able to click on users' names or @ them, on Cinny however, @ing does bring up their name but they don't seem to be getting a mention. Neither is the mention a block proceeded by a colon like it is on Element.

### Describe the solution you'd like

Bringing over the tagging/pinging feature of Element.

**Comment by kfiven** [comment]
Duplicate of #19 

Also see #319
