### ISSUE TITLE
Ability to import encryption keys

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#4]
It would be nice to have the ability to export encryption keys from another client and import them manually in Cinny so that you can decrypt old messages.

Additionally, being able to take advantage of key backup/restore would be excellent and more seamless for users.

**Comment by farribeiro** [comment]
And verify the session/device

**Comment by ajbura** [comment]
Ability to import encryption keys is done in https://github.com/ajbura/cinny/commit/e597f81b45f1312047e4284201de572f4d8530b2
key backup/restore is followed at #22
