### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by mewwo** [ajbura/cinny#41]
![Capture](https://user-images.githubusercontent.com/59064119/128097884-c84a9cfe-43b3-442c-a2b5-c1fec4de012e.PNG)
should be enough

**Comment by ajbura** [comment]
@mewwo which homeserver you are trying to register?

**Comment by mewwo** [comment]
> 
> 
> @mewwo which homeserver you are trying to register?

https://tchncs.de/

**Comment by ajbura** [comment]
![tchncs de](https://user-images.githubusercontent.com/32841439/128198159-f17d40cd-178e-4c77-b671-4716f749df5d.PNG)

Doesn't look like it's an issue on Cinny side.

**Comment by mewwo** [comment]
> 
> 
> ![tchncs de](https://user-images.githubusercontent.com/32841439/128198159-f17d40cd-178e-4c77-b671-4716f749df5d.PNG)
> 
> Doesn't look like it's an issue on Cinny side.

guess ill let the homeserver owner know instead
