### ISSUE TITLE
[bug] Join button doesn't appear

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#412]
### Describe the bug

if room join in public room list is too fast, spinner doesn't shows and button stays blue

### Reproduction

1. Find a really fast HS
2. open public rooms
3. join a room

### Expected behavior

Not showing spinner should not affect join button

### Platform and versions

```shell
NR
```

**Comment by kfiven** [comment]
Possibly it's same as #413

**Comment by ajbura** [comment]
per #419
