### ISSUE TITLE
[feat] Support text input as a reaction aka custom reaction

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#414]
### Describe the problem

Not a problem but having this additional functionality will make reactions more fun

### Describe the solution you'd like

the search box in emojiboard could show option to react with text entered in it.

**Comment by CrimsonFork** [comment]
Just adding this for easy accessibility, "freeform reactions", just put in any text in the reaction search bar and a <kbd>(React →)</kbd> button appears.
