### ISSUE TITLE
[bug] Cinny hangs when using dendrite

### ISSUE THREAD

**Issue by tezlm** [ajbura/cinny#417]
### Describe the bug

Cinny fails to load when loading rooms from a Dendrite homeserver.

![image](https://user-images.githubusercontent.com/56274831/159618457-e73a05aa-0734-4d25-b88e-b075268ab538.png)

### Reproduction

1. Create an account on a Dendrite server
2. Try to create/join a room

### Expected behavior

Cinny loads.

### Platform and versions

```shell
OS: void linux on both server and client
browser: ungoogled chromium (97.0.4692.71)
version: commit 7291932 (dev.cinny.in)
matrix homeserver: zibifods.eu.org
```

**Comment by ajbura** [comment]
Another dendrite issue:
`Uncaught (in promise) TypeError: this.pushRules[e].room is undefined`
