### ISSUE TITLE
Feature request: Support for replying to messages

### ISSUE THREAD

**Issue by hbarsaiyan** [ajbura/cinny#42]
#### Is your feature request related to a problem? Please describe.
Currently, Cinny does not have the ability to reply to messages.

#### Describe the solution you'd like
Ability to reply to messages.

#### Describe alternatives you've considered
None.

#### Additional context
A dedicated reply button would be great.
![IMG_20210804_212509_710](https://user-images.githubusercontent.com/37732050/128213599-e9596050-7d2e-4ac2-aa94-e03d4207d86a.jpg)

**Comment by farribeiro** [comment]
Related issue #40

**Comment by ajbura** [comment]
Done https://github.com/ajbura/cinny/commit/717ffe560f06452460a801038f5180ee5064d160
