### ISSUE TITLE
[bug] Message edit isn't reflected in reply

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#421]
### Describe the bug

when someone reply to a message and if later the replied message gets edited, the reply still show old message.

### Reproduction

1. Send a message A
2. reply B to it
3. now edit message A
4. observe the message B and see that the replied message still contains old content

### Platform and versions

```shell
1.8.2
```

**Comment by puyoxyz** [comment]
![image](https://user-images.githubusercontent.com/15311104/162475352-26c61994-8d59-41b5-8e09-58cfbeb5d4ce.png)
the issue description says that the old message content only shows if you reply *before* the edit, but it also shows the original even if you reply after the edit
