### ISSUE TITLE
App blackout when message contains a wrong closing tag

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#429]
### Describe the bug

On a certain room scrolling up a bit makes cinny black out entirely.

### Reproduction

Not sure which message exactly is causing this, but on the console I see the following:
`Uncaught TypeError: t.href is undefined`

### Platform and versions

```shell
1. OS GNU/Linux
2. Browser: Firefox 91.4.0
3. Cinny version: dev.cinny.in
4. Homeserver: matrix.org
```

**Comment by kfiven** [comment]
@N-R-K which room (if it's public)?

**Comment by N-R-K** [comment]
@kfiven It's public, yes: #gentoo-chatter:matrix.org

**Comment by N-R-K** [comment]
> On a certain room scrolling up a bit makes cinny black out entirely.

Hmm, my wording was bad here. It's not scolling up itself that causes it, but rather scrolling up to a *certain msg*. Not sure which one, since everything goes blank.

**Comment by kfiven** [comment]
This was the message causing this:

```
<a href=https://yewtu.be/watch?v=wl-LeTFM8zo>HOW IT FEELS TO CHEW FIVE GUM GUM GUM YOUR STIMULATION<a/>
```

Whoever sent it, wrote closing tag wrong `<a/>` which is causing blackout.

**Comment by N-R-K** [comment]
Ahh, I see. Thanks for looking into this and fixing the bug.
