### ISSUE TITLE
Creating a room temporary displays "welcome to empty room"

### ISSUE THREAD

**Issue by arnopensource** [ajbura/cinny#430]
### Describe the bug

When creating a room, the content of the message area displays « Welcome to empty room »
Going to another room and coming back will change the message to « Welcome to \<room name\> »
![image](https://user-images.githubusercontent.com/34061508/160099009-56bff5a7-a210-4bc9-95f4-75eefc172069.png)

### Reproduction

1. Create a room with a custom name

### Expected behavior

The welcome message should display the name of the room

### Platform and versions

```shell
1. OS : Debian 11
2. Browser : Firefox Developper Edition 99.0b8
3. Cinny version : dev (9cb13a91cd889320f5044c1921d9a48c1d6a2091)
4. Home server : matrix.org
```

**Comment by kfiven** [comment]
This is not a Cinny issue afaik. It depends upon how fast server send the room name and description after creation. 

So if you try it on a fast server, this can't be produced but with slow server this happens.

**Comment by arnopensource** [comment]
I think we can do something about it since at the top of the room the name is displayed correctly !
My guess is that the top of the room use the local name and the timeline wait for the server ?
