### ISSUE TITLE
Grammatical Issue at Room Start

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#434]
### Describe the bug

The sentence, "This is the beginning of `x` room" should be "This is the beginning of the `x` room" or "This is the beginning of the room, `x`"
![image](https://user-images.githubusercontent.com/47131867/160225296-9218ea45-ccfd-4f65-a029-f7c10fca2fb5.png)

### Reproduction

1. Create a room with a name
2. See issue in the room

### Platform and versions

```shell
1. Win10
2. LibreWolf
3. Cinny 1.8.2
4. yiff.social
```

**Comment by viasux** [comment]
Also, "Topic: " should be omitted if the room doesn't have any topic. I changed the room name and now it shows this, even though there is no topic.

![image](https://user-images.githubusercontent.com/47131867/160225506-c1eff4c1-db58-4f46-837d-5523da75dee9.png)

**Comment by kfiven** [comment]
Keeping reopen for the topic part.
