### ISSUE TITLE
Allow room/spaces invites to be directly loaded

### ISSUE THREAD

**Issue by Fabricio20** [ajbura/cinny#447]
### Describe the problem

Hello, currently, when receiving a private room link, you have to join it via Element, since Cinny does not support joining a room (or a space) by link directly, only by searching through public rooms! Not all rooms are public.

### Describe the solution you'd like

I'd like an option where a room invite link can be pasted and Cinny would join that specific room, an example of this link is available below:

https://matrix.to/#/#archlinux:matrix.org

Possibly under the + "Add rooms or spaces" area, along with "Join public room", have a "Join room by invite" or "Join room by URL".

### Alternatives considered

You could have Matrix.org list Cinny as an app under other apps. But this solution isn't ideal as an invite link may not be on matrix.org so their web ui would not necessarily be available to give you Cinny as an option.

![image](https://user-images.githubusercontent.com/7545720/160768275-cf8817a6-f3ad-460c-9503-03c98fc39da2.png)

### Additional context

Without this, it's currently not possible to join unlisted/private rooms via Cinny, as Cinny does not appear as an option when clicking alternative clients on Matrix.org (but since Matrix is federated this should just work from Cinny itself as it's not mandatory to have a list of apps on servers other than matrix.org).

**Comment by arnopensource** [comment]
> But this solution isn't ideal as an invite link may not be on matrix.org

I didn't understand this part
If it is about a room in another homeserver, matrix.to works https://matrix.to/#/#room:example.com

We could have "join room by invite button" + a discord-like embed for room invites links in messages ?

**Comment by Fabricio20** [comment]
> I didn't understand this part
> If it is about a room in another homeserver, matrix.to works https://matrix.to/#/#room:example.com

Indeed that seems to work, I guess my point is mostly "one may not want or is not able to" use matrix.org for invite resolution, for whatever other reasons, so a solution inside Cinny itself would be more appropriate.

I agree however, that having a screen like Discord's where you can join with an invite link as well as embed/preview support for invites would be awesome (though embeds might require a setting for using a different homeserver for invite resolution as a user might not want to connect to matrix.org, etc.. all that again).

**Comment by kfiven** [comment]
If room is not public and if user has it's alias, it can be joined through Public room list. Upon searching alias (eg `#archlinux:matrix.org`) it show a button
![image](https://user-images.githubusercontent.com/33421343/159686306-665cf5f2-ebd6-4af2-b428-63032b1e35fb.png)
like this but only issue here is that it only appear if there are no search results and thats why we have #420 for cases when you don't get right room in results but still try to join forefully. 

I know the UI of this is not really great but we have a workaround (or maybe feature) until we have proper solution.
