### ISSUE TITLE
The words used at the start of a room feel weird in the context of DMs

### ISSUE THREAD

**Issue by puyoxyz** [ajbura/cinny#455]
### Describe the bug

The beginning of a DM room uses the same words as a normal room, which feel unnatural in this context.
![image](https://user-images.githubusercontent.com/15311104/160991773-b33db05b-5eb1-4b58-8072-af9db268e8f6.png)

### Reproduction

Scroll to the top of a DM.

### Expected behavior

Something like "This is the start of your conversation with (name)" or whatever when it's a DM and not a room

### Platform and versions

```shell
Linux (GNOME 41.5 on Artix Linux)
Microsoft Edge
Cinny 1.8.2
puyo.xyz (on Synapse)
```

### Additional context

On Discord, this is the difference between (1) a DM 
![image](https://user-images.githubusercontent.com/15311104/160992489-b2acdedf-d5b7-4c6d-9805-9f783bed619b.png)
and (2) a channel 
![image](https://user-images.githubusercontent.com/15311104/160992696-711c383a-feb2-4261-9095-a649f6064052.png)

**Comment by arnopensource** [comment]
I'll do this in #431 !

**Comment by viasux** [comment]
I'd prefer "This is the beginning of your direct message with `user`"
(adding the word history seems unnecessary)

**Comment by arnopensource** [comment]
I went with "This is the beginning of your conversation with @user"

The fix is ready but I do not have a lot of time to finish the other part of the pull request. It adds some delay to the merge of the fix, sorry about that :/
