### ISSUE TITLE
Show mxid along with display name

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#46]
#### Is your feature request related to a problem? Please describe.
Currently there's no way to get user's MXID.

#### Describe the solution you'd like
Show mxid after display name on hover.

**Comment by farribeiro** [comment]
is good this feature, instead of the display name?

**Comment by bengaywins** [comment]
Wouldn't it be better if it showed mxid _on collision_? That way when you are the only one with `john` as a username in a channel/room, it just shows `john`. If you aren't, then it shows `@john:foo.com`. This is how Element currently does it, and it's quite nice.

**Comment by ajbura** [comment]
@bengaywins I believe this task is not to replace display names with mxid but showing both. It will look same as it now but when someone will hover over message then mxid will be visible after display name.

**Comment by bengaywins** [comment]
Right but I’m saying why require someone to perform an extraneous action when one could just automate it? It can be confusing if for example one we’re looking at a transcript and you do not have profile icons. Or any kind of auditing if one weren’t using a view which shows profile icons.

**Comment by ajbura** [comment]
This task doesn't handle nickname collisions at all. The reason we are adding this extra information on messages is because I am working on commands and some commands require mxid and Right now there's no option to find mxid in client.

**Comment by bengaywins** [comment]
Ah well then this description is wrong. The description is literally about collisions and what you’re talking about is something different

**Comment by kfiven** [comment]
I have updated it.

**Comment by ajbura** [comment]
Done https://github.com/ajbura/cinny/commit/c9b1a062ce621739e4323f36f1959f27861b380c
