### ISSUE TITLE
Crash on opening settings when it failed to fetch room name

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#477]
### Describe the bug

When sdk failed to get room name there is fallback name like *Xyz and 277 other*, in that situation, opening settings crash the app.

### Platform and versions

```shell
cinny 1.8.2 dev
```

**Comment by jamesjulich** [comment]
^ Just to clarify, is this when opening the client settings, space settings, or some setting related to rooms? Which actual menu is it?

**Comment by kfiven** [comment]
It's about room settings.
