### ISSUE TITLE
Posting screenshot and emoji causes browser to crash

### ISSUE THREAD

**Issue by grandeljay** [ajbura/cinny#497]
When I insert a screenshot via STRG + V and select an emoji from the list with some text my browser (Firefox / LibreWolf) crashes. The screen turns black I have to forcefully close the window. ~~This doesn't happen every time, but quite often~~ **This happens every time**. I've only noticed this behaviour on cinny and no where else so far.

Are there some logs I can look into?

**Comment by kfiven** [comment]
There could be some hint or error in browser console on why it's happening. 

Also I'm not able to reproduce this in latest Firefox. 

Also please use [issue form](https://github.com/ajbura/cinny/issues/new?assignees=&labels=&template=bug_report.yml) when submitting bug reports.

**Comment by grandeljay** [comment]
> There could be some hint or error in browser console on why it's happening.

Unfortunately I cannot use the browser console since the entire browser turns black, all tabs and panels are unusable.

**Comment by kfiven** [comment]
The what emoji+text+image are you sending will be helpful to reproduce. Also which version of Cinny you are running?

**Comment by grandeljay** [comment]
I just tried again and it crashed like clockwerk. Were you able to test it on Firefox or LibreWolf?

![image](https://user-images.githubusercontent.com/45571053/164621789-7c6767ee-16b6-4e5d-b929-856b1df4ff61.png)

**Comment by grandeljay** [comment]
It happens with any screenshot pasted from my clipboard

**Comment by grandeljay** [comment]
I am using cinny web (v1.8.2)

**Comment by kfiven** [comment]
I have tested it on FIrefox and it's working there. Let me try Librewolf.

**Comment by grandeljay** [comment]
In case it's relevant: I am using 2 [different profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US) and have both open at the same time.

The crash is also not immediately, it takes a couple of seconds. Usually I:
1. Paste the screenshot
2. Add a caption and any emoji
3. See the crashed window after 5 seconds

**Comment by kfiven** [comment]
for me librewolf is working too. Can you open console first and then send the img+msg and see if there's anything in console?

**Comment by grandeljay** [comment]
I made a video demonstrating the crash and how I can reproduce it: https://imgur.com/a/XjLj1Ye (with the browser console open)

**Comment by kfiven** [comment]
thanks for making a recording, what's your OS?

**Comment by grandeljay** [comment]
No problem 👍🏼 I am using Windows 10 here

**Comment by ajbura** [comment]
Hi @grandeljay , looks like it could be a browser specific issue (maybe some bad extension). Have you tried different browser or safe mode in same browser?

**Comment by grandeljay** [comment]
I've tried it in chromium and it works, but cinny doesn't even load in private mode for me. It's stuck here.

![image](https://user-images.githubusercontent.com/45571053/164734495-c77127d7-bafb-446c-be92-ae6f61ffdcff.png)

**Comment by kfiven** [comment]
It's not supposed to work in private mode (in case of firefox), see #20

**Comment by grandeljay** [comment]
Oh sorry, I confused safe mode with private mode. It does seem to be browser specific. **It works in safe mode.**

I haven't taken the time to exactly pinpoint it, but I'm guessing one of or the combination of these extensions was causing trouble:
- [Cookie-Editor](https://addons.mozilla.org/en-GB/firefox/addon/cookie-editor/)
- [Cookie Quick Manager](https://addons.mozilla.org/en-GB/firefox/addon/cookie-quick-manager/)
- [I don't care about cookies](https://addons.mozilla.org/en-GB/firefox/addon/i-dont-care-about-cookies/)

Thanks for all the help!
