### ISSUE TITLE
Flatpak package for of the desktop app

### ISSUE THREAD

**Issue by Ezwen** [ajbura/cinny#527]
### Describe the problem

AFAIK, the brand new Cinny desktop flavor has not been packaged for any distro yet (quite normal given that it's 1 only week old), which means it's not easy to install and try it.

### Describe the solution you'd like

Packaging Cinny as a Flatpak would make the installation completely painless, hence solve the above problem. Moreover, if published on Flathub, it would instantly be possible to install Cinny in only one click in [all distros that have Flathub configured by default](https://en.wikipedia.org/wiki/Flatpak#Supported_out-of-the-box), which could bring lots of new users.

### Alternatives considered

Among other "universal" packaging solutions:
- AppImage works well, but AFAIK is not integrated in any "software manager" UI of main distros, which means it would not create extra visibility for Cinny.
- Snap is the [default solution for Ubuntu and its derivatives](https://en.wikipedia.org/wiki/Snap_(software)#Adoption), but is not well supported outside Ubuntu, AFAIK.

Note that being a Fedora user, I am quite biased towards Flatpak.

**Comment by SharkyRawr** [comment]
I would be open to try this, with consent of the cinny team and if nobody else started working on this already, as I maintain two projects published on flathub already and I love cinny.

**Comment by kfiven** [comment]
I have tried to make one in VM but ran into some issues and now my VM stopped working. :D

**Comment by kfiven** [comment]
also I had some issues generating sources for node.

**Comment by kfiven** [comment]
Done, see https://flathub.org/apps/details/in.cinny.Cinny
