### ISSUE TITLE
Pasting by shortcut not possible in Cinny Desktop

### ISSUE THREAD

**Issue by Empty2k12** [ajbura/cinny#531]
### Describe the bug

CMD + V does not work in Cinny Desktop

### Reproduction

1. Try pasting something (e.g. password) in Cinny Desktop

### Expected behavior

Pasting by CMD + V works, not only by right-clicking and selecting Paste.

### Platform and versions

```shell
1. OS: MacOS
2. Cinny Desktop 2.0.0
```

**Comment by schwindp** [comment]
Same for Cinny Desktop v2.0.1 on MacOS.

**Comment by schwindp** [comment]
Update: All keyboard shortcuts using Cmd + … are dysfuctional. Ctrl+k for examples works fine.
Tested again in Cinny Desktop v2.0.3
