### ISSUE TITLE
Sort rooms/DM per activity

### ISSUE THREAD

**Issue by Ezwen** [ajbura/cinny#54]
#### Is your feature request related to a problem? Please describe.

Currently rooms (both DMs and group conversations) are sorted alphabetically. When one has lots of rooms, it becomes quickly complicated to browse this list, and to quickly switch between important/used rooms.

#### Describe the solution you'd like

A nice solution would be to have an option to sort rooms per activity, allowing to always put rooms with the most recent messages at the top of the list of rooms. This would put "stale" rooms at the bottom (and thus less/not visible), and "active" rooms at the top (visible and easy to access). As an example, Element already provides such an option on its web/desktop flavor.

#### Describe alternatives you've considered

Being able to tag rooms at "favorites" that would stick to the top of the list would also help for the same problem, but would require manual work from the user, and would not bring the extra benefit of automatically sorting stale/notstale rooms.

**Comment by hifi** [comment]
There's one issue with this approach that when there's a lot of activity the top rooms will keep reordering constantly.

**Comment by farribeiro** [comment]
And too the favorite feature and issue #52

**Comment by Salamandar** [comment]
This currently is my main issue with Cinny : I have to scroll a LOT in direct messages to discuss with my girlfriend :'(

**Comment by unexploredtest** [comment]
> I have to scroll a LOT in direct messages

A kind of work around I found is by creating a private space, pin it, then add important DMs there.

**Comment by alch-emi** [comment]
Would it be an appropriate solution to sort DMs by recency and rooms/spaces by alphabetical?  This is currently the implementation used by Discord, which I think works well and feels pretty natural.

**Comment by ShadowJonathan** [comment]
Discord doesn't sort their channels by alphabetical, the server owners can dictate the channel ordering, and the user can dictate their sidebar server ordering.

The only ordering in discord that's automatic is the DMs, which are by activity, yes.

**Comment by Ezwen** [comment]
Hi again, sorry to dig this one up. First of all, thanks a lot for making this work for DMs, works like a charm. I also agree that within a space it's up to the space admins to choose how should rooms be organized.

However, I personnally also have _lots_ of group discussions that are not part of any space (shown in the "Home" tab), which in my case are really akin to DMs, but with more than 2 persons involved at a time. Having an alphabetical order for such discussions feels really not adapted, as I have to sometimes scroll a very long list to reach a specific room I am interested in. Sorting these rooms by activity would, I feel, make much more sense. WDYT?

I can of course open another issue if that is preferred.

**Comment by Ezwen** [comment]
I've opened a new issue here: https://github.com/ajbura/cinny/issues/585
