### ISSUE TITLE
Custom Homeserver

### ISSUE THREAD

**Issue by codeandcreate** [ajbura/cinny#543]
### Describe the problem

I don't use one of the Homeservers suggested by the Ubuntu Touch version

### Describe the solution you'd like

A input-field to add a custom homeserver.

**Comment by kfiven** [comment]
@codeandcreate The input field where homeserver is displayed is editable.

**Comment by codeandcreate** [comment]
@kfiven it seems that i trapped into a little UX problem (it was late yesterday i tryed it ...);
On the bq m10 the UI is big enougth not to tap into the textfield besides the pulldown arrow. Since the input itself has a white background - and not a grey one like username/password - i thought it is just a pull down / select and not a input / select.

Maybe the background should be changed and/or usernames like @user:host should be useable...?

**Comment by kfiven** [comment]
I think the true solution for this is #187 
The background is kept white because for an average new user homeserver is alien word and we want them to only worry about username and password.

**Comment by codeandcreate** [comment]
Yeah, that was my first try to set my own homeserver. :)

**Comment by kfiven** [comment]
should we close this then?
