### ISSUE TITLE
Linked images not visible when using mautrix-facebook

### ISSUE THREAD

**Issue by patrikarvidsson** [ajbura/cinny#547]
### Describe the bug

It seem that images from bridges created with mautrix-facebook aren't showing up in cinny properly. It seem to work fine in Element. Some images which illustrates the bug:

- Image of the bug: https://x.arvd.sn/68oJjqraPOkZIv.png
- Image of code: https://x.arvd.sn/HHvYFd7yEy0Oem.png
- Image of console: https://x.arvd.sn/5QMihVbfHK8vsC.png

### Reproduction

1. Configure and install https://github.com/spantaleev/matrix-docker-ansible-deploy
2. Run cinny through the web interface (or desktop app, or app.cinny.in)
3. Log in to the account you created in step 1
4. Connect mautrix-facebook to facebook
5. View an image in a bridged facebook room (user or group chat) sent from facebook side

This seem to _**only**_ happen when someone on the facebook side is sending images (including myself). Sending through cinny (app.cinny.im, homserver instance or desktop) works fine.

### Expected behavior

Images should be visible

### Platform and versions

```shell
1. OS: Arch Linux (homeserver) MacOS (laptop)
2. Browser: Brave (v1.39.96 - Chromium: 101.0.4951.54, arm)
3. Cinny version: v2.0.0
```

### Additional context

Domain was masked in images.

**Comment by kfiven** [comment]
@patrikarvidsson Could you please invite me to a test room where Facebook bridge is working?

**Comment by patrikarvidsson** [comment]
> @patrikarvidsson Could you please invite me to a test room where Facebook bridge is working?

I'm not sure how this would work. The bridges are private conversations which takes place on Facebook Messenger. If you write to me on Facebook, I could probably invite your matrix user to that specific conversation.

Would that work? Let me know how I can reach you over matrix, and we can take it from there.

**Comment by kfiven** [comment]
@patrikarvidsson I am @kfiven:matrix.org on matrix.

**Comment by kfiven** [comment]
@patrikarvidsson ping pong

**Comment by kfiven** [comment]
Closing as got no response and we don't have any event data to determine what could be wrong.
