### ISSUE TITLE
[ISSUE] Dependency errors / v2.0.0

### ISSUE THREAD

**Issue by menturion** [ajbura/cinny#548]
### Describe the bug

Getting the below build errors when running `npm ci`. I had to use `npm install --legacy-peer-deps`.

`> npm ci`

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-autosize-textarea@7.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8" from @tippyjs/react@4.2.6
npm ERR!   node_modules/@tippyjs/react
npm ERR!     @tippyjs/react@"^4.2.6" from the root project
npm ERR!   9 more (flux, formik, html-react-parser, linkifyjs, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-autosize-textarea@7.1.0
npm ERR! node_modules/react-autosize-textarea
npm ERR!   react-autosize-textarea@"^7.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-autosize-textarea@7.1.0
npm ERR!   node_modules/react-autosize-textarea
npm ERR!     react-autosize-textarea@"^7.1.0" from the root project

### Reproduction

Fresh install by copying the package into an empty folder and running `npm ci`.

### Expected behavior

A successful build process.

### Platform and versions

```shell
Cinny: v2.0.0
npm: v8.7.0
node: v16.2.0
```

**Comment by kfiven** [comment]
What's your OS? Can't reproduce it on Windows.

**Comment by menturion** [comment]
Windows 10.

npm: v8.7.0 
node: v16.2.0

Maybe you have to clear the npm cache.

**Comment by kfiven** [comment]
No, it is a fresh install. Btw with node v16.2.0, npm is v7.13.0

**Comment by ajbura** [comment]
Can not reproduce on macOS with npm v8.5.2 and node v17.7.2 either.

**Comment by menturion** [comment]
Many thanks for cross-checking(!!) which proved that something is/was wrong on my system. 

Although I haven't changed anything of the setup (with respect to node, npm, Cinny ...) this issue (suddenly) occurs. Due to some other issues I noticed (e.g. npm - EPERM: operation not permitted) I guess that a main cause might be the latest Windows 10 update. 

For a first test I **disabled Ransomware protection**, cleared all caches, uninstalled npm, removed the `C:\Users\[username]\AppData\Roaming\npm` folder, and installed/downgraded to 

```
node v14.17.0
npm: 6.14.13
```
(I will test `node-v16.2.0` later again.)

Result: All works fine now.
