### ISSUE TITLE
If room history visibility is set to messages after join, then screen is stuck in the "loading phase".

### ISSUE THREAD

**Issue by DUOLabs333** [ajbura/cinny#549]
### Describe the bug

Title. Additionally, you can still send messages and respond, just that the part of the screen is just stuck in that animation.

Screenshot:
![image](https://user-images.githubusercontent.com/49244768/168136665-60f281cc-f3e3-4768-9998-4f6f14bbc7d3.png)

### Reproduction

1. Join such a server (any server that is bridged to IRC should work, I use #plasma:kde.org)
2. See issue

### Expected behavior

Just show something like "Room history visibility is set to messages after join" with a horizontal line below it, like Element.

### Platform and versions

```shell
1. Arch Linux
2. Firefox
3. v2.0.0
4. matrix.org
```

**Comment by kfiven** [comment]
I have looked into as discussed in room, and it's because when visibility setting is after join, you can still see past join/leave entries and that's what client try to fetch all the way up to room creation or when room was bridged to irc. If it's given enough time you'll see top of room.

**Comment by DUOLabs333** [comment]
It seems that Element has the same problem --- I believe it does a timeout to decide whether to keep checking or not.
