### ISSUE TITLE
arm64 Linux Desktop app?

### ISSUE THREAD

**Issue by DUOLabs333** [ajbura/cinny#553]
### Describe the problem

I want to try out Cinny Desktop, but it's not built for arm64.

### Describe the solution you'd like

Start building cinny-desktop for arm64.

**Comment by kfiven** [comment]
duplicate of cinnyapp/cinny-desktop#62

**Comment by DUOLabs333** [comment]
No, because that refers to MacOS arm64. I'm referring to Linux arm64.

**Comment by kfiven** [comment]
Just left a comment there, as someone also request one for windows in that issue.
