### ISSUE TITLE
Manual Sorting of Rooms

### ISSUE THREAD

**Issue by DUOLabs333** [ajbura/cinny#554]
### Describe the problem

Sometimes I want to sort rooms by a specific order, so that the ones I use most often would appear first.

### Describe the solution you'd like

Offer a way to drag rooms around to reorder them. Since this isn't supported by Matrix, it would have to be kept on localstorage.

**Comment by tezlm** [comment]
it would probably be better to store it in account data instead of localstorage

**Comment by kfiven** [comment]
User end sorting is unlikely to get added as we want the space admins to put them in order they want (#722).

**Comment by kfiven** [comment]
closing in favor of #722
