### ISSUE TITLE
Implement Ctrl-K quick search

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#57]
#### Describe the solution you'd like
Common idiom with chat applications has been to have Ctrl-K focus a search field to quick filter channels with arrow keys to browse the suggestions and enter to select. Esc should cancel the search and re-focus the current channel input field.

#### Describe alternatives you've considered
I don't know any better way to quickly jump into different channel _by name_.

**Comment by ajbura** [comment]
Have you tried go-to commands?

**Comment by hifi** [comment]
Might be a workable idea to bind Ctrl-K to clear the input field and insert `>` :thinking: 

Though it should then suggest the continuation characters already when you have started the line with `>`. They are great and I didn't really notice them before.

**Comment by vwkd** [comment]
This could be part of a search modal #132.

**Comment by ajbura** [comment]
done in https://github.com/ajbura/cinny/commit/fbeecc047918701c08289176d7765ff03fbd3738
