### ISSUE TITLE
Certain rooms not showing when using Conduit server

### ISSUE THREAD

**Issue by ChewingBever** [ajbura/cinny#581]
### Describe the bug

After logging in with an account on a Conduit server, Cinny only displays a seemingly random list of rooms. Only when the user sends a message in one of these missing rooms using another client does the room appear in the Cinny UI.

(I tested this using the Tauri build)

### Reproduction

1. Log in using a Conduit account
2. Notice the missing rooms

### Platform and versions

```shell
1. Linux, EndeavourOS
2. Cinny version 2.0.3
3. 2.0.3 Tauri build, https://aur.archlinux.org/packages/cinny-desktop
4. rustybever.be (Conduit)
```

**Comment by kfiven** [comment]
Tried to reproduce it and it is a Conduit issue. Cinny receives membership null, so that's why it doesn't show such rooms in room list. Element too shows the same rooms in the historical section.

**Comment by timokoesters** [comment]
Conduit omits the member event because of lazy loading

/sync spec:
> Further, like other members, the user’s own membership event is eligible for being considered redundant by the server.

Also see https://github.com/vector-im/element-web/issues/22565

**Comment by notramo** [comment]
Is it resolved or abandoned?
