### ISSUE TITLE
Sort group discussions (that are not in a space) by activity

### ISSUE THREAD

**Issue by Ezwen** [ajbura/cinny#585]
### Describe the problem

In the "Home" tab, I have lots of group discussions that are not part of any space. These discussions are really akin to DMs, simply with more than 2 persons involved at a time. 

However, currently this list is sorted by alphabetical order, which means I have to sometimes scroll a very long list to reach a specific room I am interested in, either because a new message was sent in a room, or because I want to send a message in a room.

### Describe the solution you'd like

I feel that rooms shown in "Home" (ie. rooms that are not part of any space) should be sorted by activity, the same way DMs are.

### Alternatives considered

Manual sorting could be an idea, but with large amounts of rooms that may not scale as well as sorting per activity.

**Comment by tibu** [comment]
Actually this is the only thing (plus threads) why I don't use cinny. Otherwise I find it a really lovely client, thanks developers.

**Comment by AdriDevelopsThings** [comment]
Are there any updates on this? Cinny seems like a great client, but it's challenging to use when my rooms aren't sorted by activity. :(

**Comment by kfiven** [comment]
They are now sorted with activity and hidden if read if you collapse the room category in home.

**Comment by DaforLynx** [comment]
Sorry to necro this, but right now my rooms are clearly not ordered by activity at all. They're ordered in the order I joined them with no way to change it. I'm on Linux Desktop.
