### ISSUE TITLE
Repositioning of one of the bottom screen elements

### ISSUE THREAD

**Issue by not-a-dev-stein** [ajbura/cinny#6]
**Is your feature request related to a problem? Please describe.**
The way it is right now it is a waste of space having the "someone is typing" prompt on top of the chat bar while the "X people are following the conversation on the bottom, specially since the top area doesn't shrink when no one is typing.

![image](https://user-images.githubusercontent.com/63420929/127359737-97a08b9d-1b1e-4c99-91cd-4930c7d656ca.png)

**Describe the solution you'd like**
Either moving the "X people are following the conversation" to the top of the chat bar, together with the "someone is typing" prompt or the opposite, to make better use of the vertical space. I made a couple of quick examples of how it would look:

![model1](https://user-images.githubusercontent.com/63420929/127360665-00dc6d52-5eee-4655-882f-b997d0d5e199.png)

![model2](https://user-images.githubusercontent.com/63420929/127360795-eb49049c-3185-4815-ad3d-1da3dbd31d80.png)

**Describe alternatives you've considered**
An alternative would be to shrink the top bar area when nobody is typing, but I feel like that would be troublesome to implement, since even Element struggles with dealing with that.

**Comment by cloudrac3r** [comment]
I think this is a good idea. I like the one where the names are positioned below the message input.

**Comment by ajbura** [comment]
Definitely a good suggestion but we have other plans for that space. Like showing quick emojis, commands etc.
