### ISSUE TITLE
Make "categorize subspaces" function clearer.

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#605]
### Describe the problem

I was initially very confused on what that option did, as the name isn't that clear and no tooltip exists.

### Describe the solution you'd like

Rename the option to something else, like "show rooms from subspaces".

### Alternatives considered

Show a tooltip, describing what the option does.

**Comment by kfiven** [comment]
"show rooms from subspaces" is very long and could overflow on small screens. Plus tooltips are for icon buttons not text ones.

**Comment by Miepee** [comment]
Well, what other options are there then to make the functionality more clearer?
I personally would like tooltips very much, and don't think that they're only for "text buttons". The FF inspector for example uses tooltips even for its text based buttons.
![image](https://user-images.githubusercontent.com/38186597/172194597-a8a4ec4b-c06c-4bcd-b357-514e79fab6ce.png)
Very short text isn't able to always properly show what the buttons do, and tooltips help *greatly* with them.

**Comment by kfiven** [comment]
I don't think we have a better word for it. Categorizing is what it does.

**Comment by ajbura** [comment]
Closing as spaces are categorize by default now.
