### ISSUE TITLE
Remember the state of "Room category toggles"

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#607]
### Describe the problem

I for example don't like spaces showing in my Home view, and rather only see them pinned. However, once I collapse the Spaces "room category toggle" in Home, switch to a different view "like DMs" and then go back to Home, the Spaces category suddenly is back uncollapsed.

### Describe the solution you'd like

Remember the state of room category toggles.

**Comment by ajbura** [comment]
this has been added in v4.0.0
