### ISSUE TITLE
Automatically pin all Spaces one is joined in

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#608]
### Describe the problem

I personally am too used to Element/Discord and would have all my grouped categories/Spaces in the left sidebar, rather than me having to pin them all manually.

### Describe the solution you'd like

Automatically pin all spaces when setting up Cinny for the first time.

**Comment by kfiven** [comment]
Pinning all of them creates more confusion, for discussion on this please see https://github.com/ajbura/cinny/issues/245#issuecomment-1019289004
