### ISSUE TITLE
Show room settings for a room on the room options

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#609]
### Describe the problem

Currently, the only way to check the settings for a room is to click on a room -> minimize via the arrow at the top, which isn't the most convenient.
Being able to quickly check a room settings via the right click/options menu for a room would be appreciated

### Describe the solution you'd like

A "room settings" entry, similar to this mockup:
![image](https://user-images.githubusercontent.com/38186597/172158985-e47304d1-3a31-42e7-88d9-a0ab0381dcfb.png)

**Comment by ajbura** [comment]
This has been adding in v4.0.0
