### ISSUE TITLE
Reaction selector does not reset the search text

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#61]
#### Describe the bug
After selecting a reaction or cancelling reaction selector the input text is not cleared and reopening it will keep the search text.

#### To Reproduce
0. React to some message
1. Type something in the reaction search
2. Select a reacton or cancel
3. React to another message
4. See the same text

#### Expected behavior
Text input is cleared and the default reactions are shown.

**Comment by ajbura** [comment]
#62 Got fixed in #299
