### ISSUE TITLE
Change "open in new tab" icon on media

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#612]
### Describe the problem

The current "open in new tab" (External.svg) icon on media files looks too much like a fullscreen icon and confused me a few times, as I was thinking it'd show the media file in the same tab (similar to #5 )

### Describe the solution you'd like

Change the icon to be more of an arrow, rather than a square.

**Comment by kfiven** [comment]
What we have as "Open in new tab" icon is more frequently used as such, see [this ddg search for reference](https://duckduckgo.com/?q=open+in+new+tab+icon&iar=images&iax=images&ia=images).

**Comment by Miepee** [comment]
From what I can see on the search link, all images have the arrow way more pronounced, with the square just being a solid line. 
I think it's the dotted lines specifically making my brain having the connection to full screen:
![image](https://user-images.githubusercontent.com/38186597/172193154-06b9eed1-175a-435a-9e85-6e3c84895154.png)
