### ISSUE TITLE
Support avatars with webp

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#615]
### Describe the problem

Currently a "blank image" is used for people whose profile pictures are in webp format:
![image](https://user-images.githubusercontent.com/38186597/172187901-93e37c3b-9233-4991-9866-1511c34ec230.png)

### Describe the solution you'd like
Support webp for profile pictures.

**Comment by kfiven** [comment]
The broken image show when the server doesn't send the profile pic of the user, so a broken image means something is not working. For users who don't have any image, the first letter of their username is shown.

**Comment by Miepee** [comment]
Double checked; very likely. All of the affected users are discord bridge puppets. I'll try and investigate for this, to check if the bridge is failing to create proper profile pictures.

**Comment by Miepee** [comment]
Issue found: the avatars are webp images.
I'll edit the title and bug description to more accurately reflect the issue

**Comment by Miepee** [comment]
I jumped the gun here: This wasn't an issue with webp support, the thumbnails for the avatars really just were broken.

**Comment by kfiven** [comment]
So just to confirm, webp profile pics from discord are working fine?

**Comment by Miepee** [comment]
Yeah, it was just that _some_ avatars had broken thumbnails. The ones that didn't displayed fine.
