### ISSUE TITLE
Opening Emojiboard does not focus on the input field

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#62]
#### Describe the bug
When clicking on the reaction button/emojiboard icon, the focus does note move to the input field of the selector.

#### Expected behavior
When clicking on the selector, the text input focus should immediately move to the input field of the selector and when the selector is closed (by cancelling or selecting a reaction) the focus should move back to the main input field on the bottom. This ensures seamless experience when reacting to any message during a conversation even while you're writing a message.

**Comment by ajbura** [comment]
Misunderstood this with another bug! :D 

So it's not fixed yet.

**Comment by jasikpark** [comment]
I'd love to help make this happen!

**Comment by jasikpark** [comment]
wooo 🎉
