### ISSUE TITLE
Dragging a folder into Cinny (should not be possible)

### ISSUE THREAD

**Issue by wj25czxj47bu6q** [ajbura/cinny#621]
### Describe the bug

Dragging a folder into Cinny (from a file manager) _succeeds_ in attaching the 'file'.

Attempting to send the attachment fails (as expected). If there is a typed message, that part will go through as normal.

Attempting to remove the attachment (via the circled-X cancel button) works as normal _before_ attempting to send the attachment. After a send attempt, the attachment cancel button no longer works&nbsp;&mdash; it is unclear if this is merely a UI bug or if Cinny continues attempting to send the attachment. The only way to remove the attachment at this point is to **drag** a new file (or even the same folder) into Cinny and then use the attachment cancel button on the new attachment (pasting an image or file does not work, and the upload button to open the file chooser is hidden).

### Reproduction

1. Drag and drop an arbitrary folder into Cinny. It does not matter if the folder is empty or has contents.
2. Experience undesired behaviors as documented above.

![image](https://user-images.githubusercontent.com/96372288/173170438-15875c30-c9c7-46c6-a5a7-e8d34dcead1a.png)

![image](https://user-images.githubusercontent.com/96372288/173170445-241eba6c-a948-40ac-b134-dc0550c635f9.png)

### Expected behavior

Attempting to drag a folder into Cinny should have no effect and be ignored.

Element does not handle this perfectly either, but at least it promptly gives an error ("The file 'testfolder' failed to upload.") and continues to function normally after that.

### Platform and versions

```
OS: Linux
Browser: Ungoogled Chromium 102 and Cinny Flatpak
Cinny version: 2.0.4
Matrix homeserver: matrix.org and a private one (running Synapse)
```

### Additional context

Cinny appears to create a purely client-side invisible event/message for attachments that fail to send, based on the 'following this conversation' indicator in the bottom-right. Neither that indicator nor anything else changes in other Matrix clients (except of course if there is a text message), including other instances of Cinny, on the same account or a different one looking at the same room.

**Comment by ajbura** [comment]
CInny know shows an error on uploading folder
