### ISSUE TITLE
Managing ignored users

### ISSUE THREAD

**Issue by Sehrail** [ajbura/cinny#630]
We can ignore a user in cinny but we cant  remove user's ignore in cinny, we need other client for remove user's ignore. Please add managing ignored users feature

**Comment by kfiven** [comment]
You can unignore from the same popup where there is a button to ignore people. If this is about the user setting option where all ignores are displayed and can be managed from then this is duplicate of #24

**Comment by kfiven** [comment]
Also please search for existing issues before opening new ones. And if there is already an issue, it's better to give it thumbs-up to show your support.
