### ISSUE TITLE
/myroomnick and /myroomavatar feature

### ISSUE THREAD

**Issue by Sehrail** [ajbura/cinny#631]
We can change room nick and room avatar with /myroomnick and /myroomavatar command, cinny doesn't support this commands. Please add this commands

**Comment by williamkray** [comment]
since cinny seems more focused on interface than commands, perhaps an alternative to this would be a tab in the room-settings dialog for a "room-specific profile", where users can upload an avatar and change their room nick, which would send the appropriate state event to the room.

**Comment by ginnyTheCat** [comment]
i agree with william on this one as i don't think it's that great of an experience in element to upload an image to an unencrypted room, copy the mxc url from the message source code and paste it into a command. it just feels hostile towards newer users who don't know what all that is.
i feel like element just put those settings in commands as a quick fix to avoid designing a whole seperate ui for them while all the other commands are often used settings meant to be quickly accessed (`/join`, `/leave`, `/ban`) or change the appearance of a message (`/spoiler`, `/me`).
