### ISSUE TITLE
Cinny suddenly goes blank after leaving room

### ISSUE THREAD

**Issue by wj25czxj47bu6q** [ajbura/cinny#634]
## Describe the bug

Upon leaving a room, everything disappeared from Cinny except for the background.

![Cinny post-bug screenshot](https://user-images.githubusercontent.com/96372288/174443327-5d2f1d96-e368-4f54-bf7e-cd5e705a1b06.png)

### Here is what remains of the `<body>` element after experiencing the bug:

```html
<body id="appBody" class="dark-theme">
  <div id="root"></div>
  <audio id="notificationSound"><source src="f916f0cde218d8a3941f.ogg" type="audio/ogg"></audio>
  <audio id="inviteSound"><source src="3339e9de776abcaf9dca.ogg" type="audio/ogg"></audio>
</body>
```

### Console messages appear normal before and after the bug, but two errors were logged:

![Console screenshot](https://user-images.githubusercontent.com/96372288/174443623-1d36187a-2d2b-48d7-91ea-62345d5c7690.png)
[Text version](https://github.com/cinnyapp/cinny/files/8933817/log.txt)

### For ease of debugging (human-readable line numbers), I pretty-printed the JavaScript:

![Console screenshot (after pretty-printing)](https://user-images.githubusercontent.com/96372288/174444136-77b0b6b8-7f81-451f-b7b3-6dae353a102a.png)
[Text version](https://github.com/cinnyapp/cinny/files/8933836/log-prettyprinted.txt)
[Pretty-printed JavaScript source (`main.4386bc28ce56e2e2403f.bundle.js:formatted`)](https://github.com/cinnyapp/cinny/files/8933840/main.4386bc28ce56e2e2403f.bundle.js.formatted.txt)

## Reproduction

I am honestly not sure how to reproduce this. Even after rejoining and leaving the exact same room, I did not encounter this bug again. I have encountered this bug exactly once in all my usage of Cinny.

However, @jameskitt616 said it happens sometimes when changing channels, so I am tagging him here in case he can contribute some more information.

## Platform and versions

```shell
OS: Linux
Browser: Ungoogled Chromium 102
Cinny version: 2.0.4
Matrix homeserver: private HS running Synapse
```

**Comment by wj25czxj47bu6q** [comment]
Same issue as #532 it turns out. Was not solved by c11328a.

**Comment by Pokefan5** [comment]
It seems to be related to latency between the user and the matrix/cinny instance

I myself have yet to run into this issue on my EU hosted instance, however US based users have been reporting this happening relatively frequently.

**Comment by jameskitt616** [comment]
Kinda doubt it, i host cinny and matrix myself in the same network, latency couldn't be better :P
