### ISSUE TITLE
"Mark as read" for entire space

### ISSUE THREAD

**Issue by luphoria** [ajbura/cinny#645]
### Describe the problem

I'm the kind of person who prefers to get a notification for _everything_ - even if it isn't really something that I am planning on checking on. Because of this, I get quite a lot of notifications in most of the spaces I join and they all have "99+".

Generally, unless i've been @mentioned in the discussion, I simply want to mark it as read. This works perfectly fine for individual rooms. But, I can't simply right-click a space to mark each room in the space as read all at once. This is a feature found in most chat applications with "subrooms," "channels," etc. but throughout the Matrix client area it has seemed to be randomly missing!

### Describe the solution you'd like

A simple "mark as read" in the context menu of spaces would do numbers!
![image](https://user-images.githubusercontent.com/60309933/175115961-7e31aec5-147d-460c-93dd-e48e58476385.png)
As you can see, it is already present within rooms.

**Comment by exodrifter** [comment]
I'm interested in working on this.

**Comment by ajbura** [comment]
Welcome! If you need any help feel free to react out.
