### ISSUE TITLE
👎 Cinny is deceiving users. There is no channel classification function

### ISSUE THREAD

**Issue by Pantyhose-X** [ajbura/cinny#647]
### Describe the problem

cinny is tricking the user, there is no channel classification function at all. They just put the symbol # in front of the group name
👎 -100

### Describe the solution you'd like

cinny is tricking the user, there is no channel classification function at all. They just put the symbol # in front of the group name

**Comment by ajbura** [comment]
duplicate of #44

**Comment by tezlm** [comment]
its official `type` in `m.room.create` no longer exists
