### ISSUE TITLE
[Desktop] Open in new tab does nothing

### ISSUE THREAD

**Issue by mahdi1234** [ajbura/cinny#657]
### Describe the bug

With desktop version click on "Open in new tab" icon for any image --> nothing happens.

### Platform and versions

```shell
cinny_2.0.4_amd64.AppImage on Gentoo linux
```

**Comment by kdormer** [comment]
Can confirm, I'm getting the same issue on Arch Linux with the desktop version.

**Comment by kfiven** [comment]
duplicate of #534
