### ISSUE TITLE
Mentions don't tag user

### ISSUE THREAD

**Issue by ashfame** [ajbura/cinny#659]
### Describe the bug

Mention/Tagging users seem broken! Selecting a username from suggestions that are shown only ends up writing their name in input field, that's it.

![Screenshot 2022-06-29 at 4 02 03 PM](https://user-images.githubusercontent.com/858906/176431693-5338f5fa-2f68-4441-9981-e4d6400bc86a.png)

![Screenshot 2022-06-29 at 4 02 12 PM](https://user-images.githubusercontent.com/858906/176431749-9313a50c-4671-4a83-a54b-577061473d09.png)

![Screenshot 2022-06-29 at 4 02 19 PM](https://user-images.githubusercontent.com/858906/176431768-7fb24566-c36e-491b-9093-540d39251392.png)

### Reproduction

- Type `@Ash` to trigger suggestions for users you want to select
- Choose one of them (either via Tab or mouse click)
- The text input simply displays their name now: `Ashish` and it not a mention pill, hence the user doesn't get notified.

### Expected behavior

It should tag the user and notify them.

### Platform and versions

```shell
MacOS 12.4
Safari browser + Firefox browser
Cinny - running app.cinny.in
```

**Comment by kfiven** [comment]
User does get notified even if it's not a pill and for the pill there's #19
