### ISSUE TITLE
Separation of read/unread messages in the room

### ISSUE THREAD

**Issue by weissbier** [ajbura/cinny#67]
#### Is your feature request related to a problem? Please describe.
In the room view there's no way to tell, which messages have been arrived since the last time the room has been viewed.

#### Describe the solution you'd like
Element separates already read and new messages with a horizontal green bar. Something similar would be nice for Cinny.

**Comment by N-R-K** [comment]
In dev.cinny the unread marker sticks around for me. In other words, a room always stays unread even when you've scrolled to the bottom of it.

**Comment by kfiven** [comment]
@N-R-K That part of sending read receipts is still in progress and that's why it stays unread, not an issue with unread indicator.
