### ISSUE TITLE
Unable to open or download images in the Flatpak version.

### ISSUE THREAD

**Issue by ForeverNooob** [ajbura/cinny#670]
### Describe the bug

In the Flatpak version (`in.cinny.Cinny`) it's currently not possible to open an image (in a new tab) or download an image.

Viewing images might not be possible since Tauri is not able to open new tabs. There's a FR for this though: https://github.com/cinnyapp/cinny/issues/5

### Reproduction

0. `flatpak install in.cinny.Cinny`
1. `flatpak run in.cinny.Cinny`
2. Login
3. Go to a room that has images.
4. View or download an image.

### Expected behavior

Images are being shown or downloaded (as it is possible in the web version)

### Platform and versions

```shell
1. OS: Ubuntu 18.04
2. Cinny version: v2.0.4
3. Homeserver: matrix.org
```

**Comment by deanveloper** [comment]
This seems more likely to be a bug in [cinny-desktop](https://github.com/cinnyapp/cinny-desktop), as this works fine on windows (albiet "open in a new tab" button opens the image in a new window)

**Comment by camelCaseNick** [comment]
cinny in cinny-desktop currently silently places those into your XDG download directory, most likely it is ~/Downloads. It might have to do with tauri-apps/wry#349 resulting in the WebKitGTK default instead of tauri using their own save dailog automatically.

**Comment by kfiven** [comment]
Downloading works as camelCaseNick pointed out, in case of opening seems dup of #534 or #5.
