### ISSUE TITLE
Homeserver placed wrongly in the ~/register call

### ISSUE THREAD

**Issue by thepra** [ajbura/cinny#682]
### Describe the bug

As in the image the client can't connect to the endpoint `https://chat.zigzag.academy/zigzag.academy/_matrix/client/r0/register` because the `zigzag.academy` part is out of place:
![immagine](https://user-images.githubusercontent.com/7032509/178964211-6f68629a-3c01-425a-a246-8fdb535b2aa5.png)

### Reproduction

1. Visit https://chat.zigzag.academy

### Expected behavior

Have the call made to `https://chat.zigzag.academy/_matrix/client/r0/register` given that the server is behind the root domain `zigzag.academy` meanwhile the client is on `chat.zigzag.academy`.

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Firefox 103
3. Cinny version: 2.0.4
4. Matrix homeserver: zigzag.academy
```

**Comment by ajbura** [comment]
@thepra , Your `.well_known` is mis-configured.

**Comment by ajbura** [comment]
the `base_url` part specifically [[1](https://zigzag.academy/.well-known/matrix/client)]

**Comment by thepra** [comment]
what it should be then? `chat.zigzag.academy`?

**Comment by thepra** [comment]
ok, I did look [here](https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi) and understood how to correctly configure it.

**Comment by thepra** [comment]
Nevermind, still getting method not allowed 
![immagine](https://user-images.githubusercontent.com/7032509/178975823-05a87981-5f47-4c99-b7ee-5f01a57acbd6.png)
