### ISSUE TITLE
Update to stable APIs

### ISSUE THREAD

**Issue by thepra** [ajbura/cinny#683]
### Describe the problem

As in this [issue ](https://github.com/matrix-org/dendrite/issues/2570) I figured that cinny is using and old endpoint:
`_matrix/client/unstable/org.matrix.msc2432/rooms/:room_id/aliases`

meanwhile the stable endpoints are:
`/_matrix/client/r0/rooms/{roomId}/aliases` or ` /_matrix/client/v3/rooms/{roomId}/aliases`

### Describe the solution you'd like

Could Cinny update this endpoints? (which make newer matrix server like dendrite to fail the calls given that it doesn't have no more that deprecated endpoint)

**Comment by ajbura** [comment]
@thepra This needs to be done in matrix-js-sdk as we are using that.

**Comment by aaronraimist** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/2402

**Comment by kfiven** [comment]
@aaronraimist @thepra https://github.com/cinnyapp/cinny/pull/624 we also use the stable function but this is still in the dev branch and hasn't been released.

**Comment by kfiven** [comment]
plus it's not just one unstable API call in js-sdk, there are more https://github.com/vector-im/element-web/issues/22839

**Comment by thepra** [comment]
damn!

**Comment by kfiven** [comment]
The specific case of room alias API call has now stable API and landed in Cinny 2.1.0, others are not cinny issue but js-sdk's.
