### ISSUE TITLE
"Unable to connect. Please check your input."

### ISSUE THREAD

**Issue by DC7IA** [ajbura/cinny#693]
### Describe the bug

Getting "Unable to connect. Please check your input." for every homeserver I tried using, except matrix.org and they all work with Element.

### Reproduction

1. Open Cinny.
2. Type in the TLD of a homeserver (darc.de for example does not work)
3. "Unable to connect. Please check your input."

### Expected behavior

Cinny allows me to log in instead of saying that it is unable to connect.

### Platform and versions

```shell
1. OS: Debian GNU/Linux
2. Cinny: v2.0.4 (AppImage)
```

**Comment by ajbura** [comment]
@DC7IA It looks like you are facing https://github.com/tauri-apps/tauri/issues/4472 Try reinstalling ca-certificates.

**Comment by DC7IA** [comment]
> Try reinstalling ca-certificates.

This had no effect.

EDIT: Result is still the same.

**Comment by ajbura** [comment]
@DC7IA Any error in apps's console?

**Comment by DC7IA** [comment]
> @DC7IA Any error in apps's console?

No output at all.

**Comment by kfiven** [comment]
@DC7IA Hi, there should be an error. My best is that Cinny is not able to send network requests on your system. Please check for anything unusual by Opening app > RIght click > Inspect. then see any blocked request in Network tab or Console.

**Comment by DC7IA** [comment]
> then see any blocked request in Network tab or Console.

![image](https://user-images.githubusercontent.com/26351852/180000840-43231f8f-0ff1-4469-aae4-71cd7a0094d0.png)

Which is strange since it is definitely a valid Let's Encrypt certificate.

**Comment by DC7IA** [comment]
The lookup for the `.well-known` delegation works, so it is failing at connecting to the actual server.

No server at all works except for matrix.org, I've entered around 10 different servers now.

**Comment by kfiven** [comment]
hmm, it's surely some bug with Tauri and the above-linked issue is about the same issue. 

Btw have you tried?
> updating app-misc/ca-certificates

**Comment by DC7IA** [comment]
> Btw have you tried?
> 
> > updating app-misc/ca-certificates

As I said, the result is still the same,

**Comment by kfiven** [comment]
Should be fixed with cinny-desktop 2.2.0

**Comment by blockisec** [comment]
still an issue for me in 2.2.2 (Fedora)

**Comment by kfiven** [comment]
@blockomat2100 what's the error in app console?
