### ISSUE TITLE
Can't log in on a server without delegation

### ISSUE THREAD

**Issue by caldwell** [ajbura/cinny#7]
I'm trying to use https://app.cinny.in/ to  login to my self hosted matrix-synapse server (v 1.38). For the sake of this lets say it's hosted at `https://matrix.example.com`. On the Cinny login screen I put in my username and password, and replace `matrix.org` with `matrix.example.com`. 

When I click "Login", Cinny says "Error: Homeserver not found".

In my browser's network inspector I see that when I click the login button, Cinny tries to load this:

`https://matrix.example.com/.well-known/matrix/client`

This file doesn't exist on my server and so it returns a 404. Cinny appears to consider that fatal and no other endpoints are attempted.

Reading [this](https://matrix-org.github.io/synapse/v1.38/delegate.html) it seems to be an optional way to delegate servers.

I am able to login fine with Element and Fluffy Chat, so I don't  _think_ my homeserver is configured incorrectly. But I am not a matrix expert…

**Comment by leesalminen** [comment]
I’m also experiencing the same issue. Wanted to try this client out! Will keep an eye out for a fix to try it later. Looks great so far.

**Comment by ajbura** [comment]
Should be fixed after https://github.com/ajbura/cinny/commit/8cf030585f8de9def779af47bbd127455e453799 Can you please check it out?

**Comment by leesalminen** [comment]
@ajbura Can confirm that I am now able to log in to Cinny. Looks beautiful. Thanks!
