### ISSUE TITLE
Anonymize file names while downloading (and?) uploading

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#700]
### Describe the problem

I keep downloading image.png files and having to rename them every single time to download them is very tiring and time consuming.

### Describe the solution you'd like

I think the best way to do this would be to randomly add some text at the end of every file uploaded (or interpreted - since not all files are uploaded by cinny)- example: image.png -> image [23nfn3k36j].png -- It would also be very useful to have a separate *option* to anonymize file names completely when downloading - example: image.png -> 32ybn4lkj65k4.png

**Comment by kfiven** [comment]
I don't think this out of scope of cinny and even some people wouldn't want their file names to be random.
