### ISSUE TITLE
add service to Ferdium (multi messenger)

### ISSUE THREAD

**Issue by heylix** [ajbura/cinny#718]
### Describe the problem

https://ferdium.org/ is the continuation of the Ferdi multi messenger. Cinny maybe can be used as a service there, as Element is already in there.

### Describe the solution you'd like

ideally there'd be a self contained local Cinny inside of the container.

### Alternatives considered

custom service, which I set up with my self hosted Cinny server.

### Additional context

https://github.com/ferdium/ferdium-recipes

**Comment by kfiven** [comment]
https://github.com/ferdium/ferdium-recipes/pull/193 Someone added it to Ferdium.
