### ISSUE TITLE
Reorganize rooms in spaces

### ISSUE THREAD

**Issue by Figurant16** [ajbura/cinny#722]
### Describe the problem

 In spaces, we can’t move rooms on top of each other (that’s not very clear so I attach a video of what I mean) or create category like on discord servers.

https://user-images.githubusercontent.com/26358854/183269564-ed81e7a1-933c-4d32-a434-a0cdc1b41697.MOV

### Describe the solution you'd like

I would like to be able to organize the rooms in category or move them.

**Comment by kfiven** [comment]
For the category part, you could create a subspace and add rooms to it. And if you click `categorized subspace` then subspace will appear as a category.

In case of reorganize, just to clarify, do you want to reorder them as a space admin or as an end user?

**Comment by Figurant16** [comment]
Oh ok for the category.

I want to reorder them as a space admin.

**Comment by kfiven** [comment]
per comment on #903
