### ISSUE TITLE
Impossible to start a new line on mobile

### ISSUE THREAD

**Issue by q234rty** [ajbura/cinny#736]
### Describe the bug

It's impossible to start a new line on mobile.

Pressing Enter or Shift+Enter will just send the message.  

### Reproduction

1. Open cinny on mobile
2. Try to start a new line in the text field to input messages.

### Platform and versions

```shell
1. OS: LineageOS 12.1
2. Browser: Chrome 104.0.5112.63
3. Cinny version: 2.1.1
```

**Comment by kfiven** [comment]
I tried this on my android phone's chrome 105.0.5195.79 and I can enter a new line by the keyboard's enter button.

**Comment by q234rty** [comment]
> I tried this on my android phone's chrome 105.0.5195.79 and I can enter a new line by the keyboard's enter button.

What keyboard are you using? The enter button sends a message on both Gboard and LineageOS's aosp keyboard.

**Comment by kfiven** [comment]
Gboard.

**Comment by q234rty** [comment]
No idea, then.
Would still be great to add a toggle to disable "send by enter".

**Comment by kfiven** [comment]
on focusing msg input does it show you [send key](https://i.stack.imgur.com/0D0pb.png) or [enter key](https://i.stack.imgur.com/g7LiV.png)?

**Comment by q234rty** [comment]
After a bit more testing I found that if you type in English w/ Gboard and press enter after entering some characters but before selecting a word, it will indeed enter a new line, however if you press enter after selecting a word it will send the message. 
I haven't found any way to do that w/ LineageOS's aosp keyboard.
In all cases the enter key is shown, unlike e.g. Fluffychat which makes Gboard show the send key when "send by enter" is enabled.
