### ISSUE TITLE
Message author doesn't change after sending message with no content

### ISSUE THREAD

**Issue by Roki100** [ajbura/cinny#737]
### Describe the bug

When chatting e.g. in DMs with `user` you can send message with no content and pretty much "chat as him"

### Reproduction

1. open element
2. /devtools
3. send custom event
4. do not edit the json at all but just set the type to `m.room.message`
5. send the event
6. check cinny, the message should not be visble at all and if last message was from `user`, sending a message will make it appear like he sent it (spoiler: he didn't)

### Expected behavior

The message should appear and be empty

### Platform and versions

```shell
Cinny version: 2.1.1
Matrix Homeserver: matrix.org
```

### Additional context

idk testing and this turns out to be a cinny bug
(sending such event should be possible in DMs if it fails in other rooms)

**Comment by kfiven** [comment]
As per [spec](https://spec.matrix.org/v1.3/client-server-api/#mtext) body is required, and no client sends an empty message. Using devtools you can break just everything.

**Comment by Roki100** [comment]
> As per [spec](https://spec.matrix.org/v1.3/client-server-api/#mtext) body is required, and no client sends an empty message. Using devtools you can break just everything. 

well yeah, but that should still be clasified as a bug as the client should handle unsupported messages/events and such
