### ISSUE TITLE
Extend "Pin" feature to include rooms or DMs

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#739]
### Describe the problem

I frequent some rooms that happen to be at the very bottom of a long list of rooms, due to the fact that they do not belong to any specific spaces. Similarly, there may be contacts that I DM infrequently, but that I want to be able to find easily.

### Describe the solution you'd like

I would like to be able to "pin" DMs or individual rooms the same way that I can pin spaces to the left-hand navigation bar.

### Alternatives considered

Creating private spaces with "favorite" rooms in them would be a way to access rooms more quickly, but this doesn't effect DMs/people due to the way that Cinny separates DMs from rooms globally.

Using the quick-switcher is effective for keyboard-driven navigation, but is more clumsy on touchscreen or mouse based navigation flows.

**Comment by williamkray** [comment]
this _might_ be considered a duplicate of https://github.com/cinnyapp/cinny/issues/44 ... however, i'll leave that to others to decide, as my issue explicitly discusses some desired implementation details and extends it to users/DMs and not just channels/rooms.

**Comment by kfiven** [comment]
#44 is about using the element's favorite feature and showing them at top of room list. #106 was exactly like this.

**Comment by williamkray** [comment]
ah, in that case i'll close this for the same reason as #106 "unlikely to be added"

**Comment by ginnyTheCat** [comment]
>but this doesn't effect DMs/people due to the way that Cinny separates DMs from rooms globally

i'm not sure whether i understood that sentence right but i'm using a favorites space for some time and i have rooms and people added in there.
