### ISSUE TITLE
Option to float rooms with unread messages to the top of the room list

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#740]
### Describe the problem

I have some spaces with lots of rooms in them, and if the room is very active but starts with a letter at the end of the alphabet, it automatically gets placed at the bottom of the room list. Jumping to this room requires using the quick-switcher or scrolling to the bottom of the room list every time.

### Describe the solution you'd like

It would be nice if there was an option to have all rooms with unread messages in them float to a section at the top of the room list so that they are easily accessible and visually present when browsing the Cinny interface.

### Alternatives considered

Using the quick switcher - not as useful on touch-screen devices or with a mouse

Creating a private space with "favorite" rooms in it

**Comment by vale981** [comment]
One further point: It is really annoying to hunt for all the rooms with unread messages to get rid of the unread indicator in the spaces list.

**Comment by ajbura** [comment]
Now you can close the rooms category to filter by unread and sort by activity.
