### ISSUE TITLE
New mid-sync encrypted messages will not update

### ISSUE THREAD

**Issue by luphoria** [ajbura/cinny#742]
### Describe the bug

If you use multiple Matrix clients, and speak often in e2ee conversations, you will find that if you happen to resync Cinny and click on an e2ee room with new messages before the sync is complete, you will see the `** Unable to decrypt: The sender's device has not sent us the keys for this message. **` text (on an unrelated note - this text should really be specially formatted and less screamy). 
Obviously this is normal behavior, but the bug occurs because the text does not update on its own once the keys *have* been received - you have to refresh that room to see the new message content.

### Reproduction

1. Close Cinny
2. Receive/send an encrypted message via another client
3. Open Cinny
4. Click that room before sync is complete
5. You will see the `** Unable to decrypt: The sender's device has not sent us the keys for this message. **` text even after the keys have been received and synced

### Expected behavior

The moment the corresponding keys were received, the text in the room should update for the decrypted content.

### Platform and versions

```shell
1. OS: Arch Linux x86_64
2. Browser: Ungoogled Chromium v104.0.5112.79 (official build)
3. Cinny version: v2.1.2 (app.cinny.in)
4. Matrix homeserver: gra.im (Synapse)
```

**Comment by ghost** [comment]
I think this is what I'm having problems with as well. I've logged into Cinny multiple times, but I can't read any of my DMs as Cinny won't decrypt the messages.

**Comment by ajbura** [comment]
@DerpyBubblez have you verified login and downloaded encryption keys?

**Comment by ghost** [comment]
I verified login, but there seemed to be no option to download encryption keys. As a workaround for the issue, I exported keys from my Element session.

**Comment by kfiven** [comment]
that download icon btn

![image](https://user-images.githubusercontent.com/33421343/187464608-f8477a80-339c-4b84-9991-e8084f8c3cc8.png)

**Comment by ghost** [comment]
That's a much more convenient option. If you're logging in on a new session, it should ask you to verify, and once completed, automatically restore the keys.

**Comment by kfiven** [comment]
#792 on automatically fetching keys.

**Comment by luphoria** [comment]
> I think this is what I'm having problems with as well. I've logged into Cinny multiple times, but I can't read any of my DMs as Cinny won't decrypt the messages.

To clarify - I can view my messages after the keys sync; however, if I am currently viewing a room with encryption enabled _before_ the keys have synced, then the "decryption failed" messages persist until I refresh that particular room.

**Comment by eNkKVS4HxHc9jaq** [comment]
> That's a much more convenient option. If you're logging in on a new session, it should ask you to verify, and once completed, automatically restore the keys.

Yes please! Add this function to Cinny to automatically download the encrypted message backup after a security key has been used to verify the session.
