### ISSUE TITLE
Placeholder when no display name is set

### ISSUE THREAD

**Issue by HarHarLinks** [ajbura/cinny#748]
### Describe the bug

I have no display name set on my account.
In cinny this looks like this:
![image](https://user-images.githubusercontent.com/2803622/184416565-b79d0af0-c9d8-458e-8ac8-c4ca5e0cf0f9.png)

### Expected behavior

It could look better to the left of the :pencil2: 

In element, any place where the display name would usually appear, it puts my mxid instead, e.g.
![image](https://user-images.githubusercontent.com/2803622/184416888-1f839450-1638-4994-a0b3-f9ab7c3cd0f9.png)

### Platform and versions

```shell
OS: Arch
Browser: 5.4.2763.3 (Official Build) snapshot (64-bit) 
Cinnyv2.1.2
```

**Comment by ajbura** [comment]
Fixed in 4a35aa72722d7b2d0182dc65cbea89ab13fa316c
