### ISSUE TITLE
Breadcrumbs in ctrl+k

### ISSUE THREAD

**Issue by D4ndellion** [ajbura/cinny#760]
### Describe the problem

Switching back and forth between rooms can be a hassle and requires using a mouse

### Describe the solution you'd like

When hitting CTRL+K a list of rooms last accessed should pop up, allowing you to just do CTRL+K enter to quickly switch between them.

### Additional context

This is how it is in element as well

**Comment by ajbura** [comment]
@dali99 It does show up last accessed rooms when you do Ctrl+k.

**Comment by D4ndellion** [comment]
Oh, you're right. for some reason it didnt show up earlier.
