### ISSUE TITLE
`TypeError: null is not an object (evaluating 'r.displayName')` when attempting to switch to a room

### ISSUE THREAD

**Issue by anoadragon453** [ajbura/cinny#772]
### Describe the bug

Attempting to click on rooms in my instance of Cinny will seemingly do nothing. The same behaviour occurs if I use the Ctrl-K switcher, tab a few and press enter to try and open a room, and likewise if I try to open a room from the "Spaces room management" modal. The following error appears in the JS Console:

```
TypeError: null is not an object (evaluating 'r.displayName')
```

Video of the behaviour:

https://user-images.githubusercontent.com/1342360/185753938-14189da3-00fc-4439-bf68-797c4387b448.mp4

### Reproduction

1. Open Cinny
2. Click on a room in the room sidebar. **Opening the first room works.**
3. Click on another room in the room sidebar.
4. Nothing happens

### Platform and versions

```shell
1. Arch Linux
2. Cinny Desktop
3. Cinny version v2.1.2. Also occurs on v2.1.1.
4. Homeserver: amorgan.xyz
```

### Additional context

This bug appears to be account/collection of room dependent. On the same computer, with the same Cinny install, my other (work) Matrix account does not experience this issue. This I imagine this either relates to this account's profile data, or perhaps event(s) in a room with invalid schema.

**Comment by kfiven** [comment]
Looks like this is happening because of invalid custom emoji account data. Try solutions at #750 and #747

**Comment by kfiven** [comment]
or just try https://dev.cinny.in with the same account. (Since there is a fix now).

**Comment by anoadragon453** [comment]
Indeed, it seems to be fixed on `dev`. Thank you!

**Comment by selfisekai** [comment]
when is there gonna be a release with this fix?

**Comment by kfiven** [comment]
@selfisekai We are gonna push it with the next release.
