### ISSUE TITLE
hide pinned spaces from home

### ISSUE THREAD

**Issue by ashkitten** [ajbura/cinny#775]
### Describe the problem

currently, all top-level spaces are shown in home regardless of whether or not they are pinned to the sidebar. because pinned spaces do not affect unread count in home, it can be confusing to keep track of which spaces are pinned in order to figure out where an unread room in home is

### Describe the solution you'd like

hide spaces from home if they are pinned to the sidebar

**Comment by kfiven** [comment]
1ec73228300b30eddf91a6875bb2cdf3fec4c0e8 Already done. Can be tested on https://dev.cinny.in

**Comment by ashkitten** [comment]
oh, didn't realize that was the case. thank you!
