### ISSUE TITLE
Hide Left Bar (rooms)

### ISSUE THREAD

**Issue by duarm** [ajbura/cinny#803]
### Describe the problem

I would like to hide the left bar/rooms bar/navigation bar.

### Describe the solution you'd like

I would like to have an option to hide the left bar forever. I nagivate through each space/room with ctrl+k, I don't even use that bar.

**Comment by nonl4331** [comment]
@ajbura

I was wondering if there is anything blocking the merge of this pull request and if there is anything I (or anyone else) could do to speed things up?

Thanks!

**Comment by duarm** [comment]
I've been using the PR's branch for months, I've updated the branch to the latest dev, you can build it yourself for the time being, the maintainers might be busy, there's nothing going on for months

**Comment by kfiven** [comment]
I don't understand why it's needed. Cinny adapt itself to various device widths already. 

If sidebar is hidden like this then app doesn't respond to change in screen widths which looks broken.

**Comment by duarm** [comment]
> I don't understand why it's needed.

Cinny becomes more space efficient. I could argue the opposite: This feature is needed and the side bar is not needed because we have ctrl+k.

> Cinny adapt itself to various device widths already.

Not the same as "I want to hide my side bar".

> If sidebar is hidden like this then app doesn't respond to change in screen widths which looks broken.

What do you mean by this? cinny behaves the same when changing the window width.

EDIT: edited the PR with some screenshots illustrating how much more space efficient cinny becomes with it.

**Comment by kfiven** [comment]
Closing as we have no plans to support this feature.
