### ISSUE TITLE
Showing Room Information in the right sidebar

### ISSUE THREAD

**Issue by Freeplayg** [ajbura/cinny#809]
### Describe the problem

Sometimes hard to find what a room may be about

### Describe the solution you'd like

Something like this (made quickly in inspect element), easier to find at a glance
![image](https://user-images.githubusercontent.com/40742947/188282129-55930090-339c-4ebc-8e28-59ae794b6b2c.png)

**Comment by ajbura** [comment]
v4 now shows room topic in room header.
