### ISSUE TITLE
Defer typing notifications until it can't be a command

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#81]
#### Is your feature request related to a problem? Please describe.
When you are purely going to use a command to switch between rooms it's a bit annoying typing notifications are sent out immediately when you start typing.

#### Describe the solution you'd like
Defer sending typing notifications after enough characters (3 or 4?) have been input from the beginning of the input field that it cannot enter emoji completion or a go-to command. That will also prevent sending useless notifications if people accidentally hit a key or two and then backspace it out.

**Comment by LordRishav** [comment]
Or better, if a message starts with a slash (for example `/join`), don't send a typing notification for it.

**Comment by ajbura** [comment]
> Or better, if a message starts with a slash (for example `/join`), don't send a typing notification for it.

it doesn't send typing notification with commands except go-to commands (>) (which will be fixed too).

**Comment by vwkd** [comment]
This would be solved by not overloading the chat input field for commands, see #129
