### ISSUE TITLE
Cinny Desktop client crashes after installing on windows

### ISSUE THREAD

**Issue by soulspark666** [ajbura/cinny#816]
### Describe the bug

After a fresh install, I tried to run the application, both as a normal user and as an administrator, but the app seemed to crash.

I will be happy to share any logs or any other info required to reproduce the bug at anyone end.

### Reproduction

1. Click on the Cinny Desktop app
2. It crashes as can be seen from task manager

### Expected behavior

App should run

### Platform and versions

```shell
1. Windows 11
2. Cinny Version: Cinny desktop v2.1.3
```

### Additional context
![image](https://user-images.githubusercontent.com/37495396/188366558-9f172391-010e-4b88-b24e-da5442368996.png)

**Comment by kfiven** [comment]
@soulspark666 what's the version of your Microsoft Edge WebView2 Runtime?

**Comment by soulspark666** [comment]
@kfiven I don't have any.....
Was it a dependency that is required???
Since the edge is bloat for me, I have removed it from my windows installation.

**Comment by kfiven** [comment]
@soulspark666 Did you installed cinny from .msi (from cinny-desktop releases)?

**Comment by kfiven** [comment]
Yes it's a dependency. But it should've installed it automatically.

**Comment by soulspark666** [comment]
@kfiven yes it was from the package:
`Cinny_desktop-x86_64.msi`

**Comment by kfiven** [comment]
Alright, I will look why it hasn't automatically installed WebView2 but without WebView2 it won't work. So if you want to use it, install WebView2. Closing this issue.
