### ISSUE TITLE
Drag-and-drop file upload & message field autofocus

### ISSUE THREAD

**Issue by jasikpark** [ajbura/cinny#85]
#### Is your feature request related to a problem? Please describe.
I always want to drag an image onto the message field, to attach it to my message, but instead my browser opens the file as a `file://` link.

I also wish that the message field was focused after uploading a file so that you don't need to tab to it after upload.

#### Describe the solution you'd like
I would hope that dragging a file on top of the message field attached the file + after attaching a file, the message `<input/>` was focused.

#### Additional context

Thanks for this awesome project! I'd be interested in implementing at least part of this, but I haven't actually looked too much at the structure of the app... it looks quite nicely laid out though

**Comment by menturion** [comment]
+1
Every modern app supports file upload via drag and drop these days.

**Comment by Litom** [comment]
+1

**Comment by BachoSeven** [comment]
@ajbura was the autofocus for input fields also implemented? I don't see it in the PR

**Comment by ajbura** [comment]
@BachoSeven Typing automatically focus on input.

**Comment by BachoSeven** [comment]
@ajbura Thanks, hadn't noticed it was working.
