### ISSUE TITLE
room list is not shown when after pressing back or home on small viewports

### ISSUE THREAD

**Issue by 2-www** [ajbura/cinny#854]
### Describe the bug

recenlty cinny started switching to the last used room in the space when switching spaces. there is a bug: it hides the room list in the process.

### Reproduction

1. click on a space
2. expect to see a list of rooms, only see the last used room.
3. click back
4. click home in the pathbar
5. expect to see the list of top-level rooms, only see the last used non-spaced room.

### Expected behavior

room list visible

### Platform and versions

```shell
debian gnu/linux
```

### Additional context

none

**Comment by kfiven** [comment]
seems to be fixed now.
