### ISSUE TITLE
Cinny blanks out on opening a space

### ISSUE THREAD

**Issue by kubo6472** [ajbura/cinny#855]
### Describe the bug

* Might be related to #634
* Cinny just blanks out since latest update
![image](https://user-images.githubusercontent.com/26146502/190877967-f26f2f64-e746-407e-b2aa-b6f4a2faa3e8.png)

### Reproduction

1. I open a space on Cinny startup or being a lot in the background
2. I see a blank screen

### Platform and versions

```shell
1. OS: Win 11 Pro
2. https://github.com/cinnyapp/cinny-desktop
3. Cinny-Desktop 2.2.0
4. Conduit based tjm.sk
```

### Additional context

If it is an issue of the app I cannot confirm. It does not happen in browser on app.cinny.in, that is apparently 2.2.0. I also don't experience it in an app I built with capacitor.js in #848 from the 2.1.3 release of Cinny. If it is an issue of the desktop app, please be so kind and move this :) Thanks

**Comment by kubo6472** [comment]
I managed to get some logs: https://paste.hexus.eu/ixeqasabol.properties

**Comment by kfiven** [comment]
@kubo6472 what's the version of your Microsoft Edge WebView2 Runtime?

**Comment by kubo6472** [comment]
> @kubo6472 what's the version of your Microsoft Edge WebView2 Runtime?

Microsoft Edge WebView2 Runtime 105.0.1343.42
