### ISSUE TITLE
Allow uploading pasted images

### ISSUE THREAD

**Issue by kreatoo** [ajbura/cinny#87]
#### Is your feature request related to a problem? Please describe.
Yes, when i try to copy paste a image it pastes random letters instead of uploading the image.

#### Describe the solution you'd like
A dialog when a image is pasted and the ability to upload the image through that dialog.

#### Describe alternatives you've considered
None.

#### Additional context
Theres none.

**Comment by farribeiro** [comment]
wdym: Paste from clipboard ?

**Comment by BBaoVanC** [comment]
> wdym: Paste from clipboard ?

Like if you have an image copied and then you do ctrl-v, currently Cinny just tries to type the raw binary data into the chat box.
