### ISSUE TITLE
Add a way to (client side) replace older profile picture by the new one on old message

### ISSUE THREAD

**Issue by ghost** [ajbura/cinny#885]
### Describe the problem

Actually if i change my profile picture (or other do it), the old profile picture appear on the old message.

### Describe the solution you'd like

Have a settings switch like in element, to replace client side the older profile picture by new one on older message (i insist on client side).

**Comment by kfiven** [comment]
IMO we should just show the latest Profile Picture and Nick in all messages. A setting would be bloat for functionality like this.

**Comment by ghost** [comment]
> IMO we should just show the latest Profile Picture and Nick in all messages. A setting would be bloat for functionality like this.

i have asked a settings because it's how element do it, but it's up to you how you implement it :+1:
