### ISSUE TITLE
Infinite loading icon when clicking "Join"

### ISSUE THREAD

**Issue by Chirunos** [ajbura/cinny#886]
### Describe the bug

Happens only on the public rooms explorer

### Reproduction

1. Go to public rooms explorer
2. Join rooms
3. Wait for ~1 minute
4. See that you didn't join the room

### Expected behavior

Room joined

### Platform and versions

```shell
1. OS: Windows 7 SP1 Build 7601
2. Browser: Firefox 103.2 ESR
3. Cinny version: 2.2.2
4. mozilla.org
```

**Comment by kfiven** [comment]
Which room you have tried to join and were there any errors in browser's console?

**Comment by Chirunos** [comment]
> Which room you have tried to join and were there any errors in browser's console?

My environments changed and I can't reproduce the issue anymore since my environment changed significantly (now on openSUSE Leap and Firefox Nightly), but I it happened on apparently random rooms on `mozilla.org` server, didn't test on other servers though.
