### ISSUE TITLE
Codeblock and Blockquote require newline

### ISSUE THREAD

**Issue by kfiven** [ajbura/cinny#890]
### Describe the bug

Sending Codeblock (with >) and Blockquote (```) require new-lines otherwise they don't render.

### Reproduction

1. Go to any room
2. Send 
```
hello
> This is a block quote
```
or 
```
hello
\```
this is a codeblock
\```
```
(remove the \ before sending)
3. Notice they are not parsed as markdown.

### Expected behavior

These shouldn't require newlines.

### Platform and versions

```shell
On Cinny v2.2.2
```

**Comment by mobergmann** [comment]
I agree. In fact, I didn't even knew what exactly caused the code to not be rendered as a code block, until I found your issue describing the issue and a "workaround".

**Comment by mobergmann** [comment]
As it seems, it is best practice to include newlines before and after Blockquotes according to [markdownguide.org](https://www.markdownguide.org/basic-syntax#blockquotes-best-practices). But there is no mention of newlines before [Fenced Code Blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)

**Comment by ajbura** [comment]
this has been fixed in v3
