### ISSUE TITLE
Search for text

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [ajbura/cinny#90]
#### Is your feature request related to a problem? Please describe.
Searching for text in a room, all rooms, or all rooms in a space.

#### Describe the solution you'd like
A search bar in the upper right corner where you can search for text. Preferrably with the abilty to search by user as well with a "from: @abc:user.com"
Pretty much whan discord already has

**Comment by BBaoVanC** [comment]
Currently the search api only supports searching words, and that's about it (and only in unencrypted rooms obviously, Element does its own indexing for encrypted rooms)

See https://matrix.org/docs/spec/client_server/r0.6.1#id104 for more info

**Comment by ajbura** [comment]
dcef08009dddacb1c44cd096feff1f33bd0a61d2 done for unencrypted rooms.
