### ISSUE TITLE
[FR] Hide registration button instead of throwing an error

### ISSUE THREAD

**Issue by kubo6472** [ajbura/cinny#900]
### Describe the problem

If you try to register on a server with disabled registration, this is what you see in cinny:
`M_FORBIDDEN: Registration has been disabled.`

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/26146502/194063099-be935c1b-99c8-4b7b-bfaf-c08e0756381a.png)
Can this whole box be hidden instead?

**Comment by kfiven** [comment]
See https://github.com/cinnyapp/cinny/issues/146#issuecomment-1019775560
