### ISSUE TITLE
N is not a function

### ISSUE THREAD

**Issue by kubo6472** [ajbura/cinny#915]
### Describe the bug

Forked and synced repo, hosted on netlify by the most standard means possible gives this error
![image](https://user-images.githubusercontent.com/26146502/195291624-9d049fee-2e00-4ce0-b061-b1de3e0ad773.png)

### Reproduction

1. Open group/chat details.
2. Experience blank screen and this error in the console.

### Expected behavior

See the details of the chat/group

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Firefox 105.0.3 (64-bit)
3. Cinny Version: v2.2.2 (c.tjm.sk)
4. Matrix HS: Conduit v0.4.0 (tjm.sk)
```

**Comment by kfiven** [comment]
Run it locally and try opening Group chat details then. 

`N is not a function` is minified error, we don't know what `N` could be.

**Comment by kfiven** [comment]
And it possibly only happen on Conduit because on Synapse I can't reproduce.

**Comment by kubo6472** [comment]
Local working even with conduit HS. I'm turning to netlify, as the possible cause of trouble.

**Comment by kubo6472** [comment]
I managed to deploy it on cf pages instead. It works now :)
