### ISSUE TITLE
 "almost there" displayed when server is down

### ISSUE THREAD

**Issue by 2-www** [ajbura/cinny#917]
### Describe the bug

"heating up", "almost there", "looks like you have a lot to heat up" are displayed when the homeserver is down

### Reproduction

1. log in
2. wait for the server to go down

### Expected behavior

"almost there" should not be displayed when no connection can be made at all

### Platform and versions

```shell
1. Debian
2. Epiphany
3. dev.cinny.in
4. matrix.pub.solar
```

**Comment by ajbura** [comment]
this has been improved in v4.0.0
