### ISSUE TITLE
Full UIAA implementation

### ISSUE THREAD

**Issue by yusdacra** [ajbura/cinny#93]
#### Is your feature request related to a problem? Please describe.
Not being able to login with homeservers that do not support registration (email & password) but instead using SSO / OAuth such.

#### Describe the solution you'd like
Proper UIAA support needs to be implemented in Cinny.

#### Describe alternatives you've considered
There is none.

#### Additional context
Nothing.

**Comment by ShadowJonathan** [comment]
For the record, this is part of the spec; https://spec.matrix.org/unstable/client-server-api/#user-interactive-authentication-api

**Comment by kfiven** [comment]
related: #9
