### ISSUE TITLE
"Jump to Mention" instead of "Jump to unread" when mentioned

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#935]
### Describe the problem

When I get mentioned in a large room, I just want to see where i was mentioned, not thousands of messages. A button to jump to the mention would be tremendously useful.

### Describe the solution you'd like

A "Jump to Mention" button near or replacing the "Jump to Unread" button

### Alternatives considered

scrolling though lots of text

**Comment by kfiven** [comment]
Duplicate of #235
