### ISSUE TITLE
Desktop/Mobile App

### ISSUE THREAD

**Issue by ninoppp** [ajbura/cinny#939]
### Describe the problem

Wow, just found this matrix client after a long time of using element. I'm quite impressed with how good it is. I'd love to introduce it in my organisation, however, for that there'd have to be downloadable applications, for desktop and mobile.

### Describe the solution you'd like

A PWA would probably suffice and I don't think should be too hard to implement. Or maybe even utilize https://capacitorjs.com/ and generate apps for every plattform quite easily? Would be willing to help.

**Comment by kfiven** [comment]
We already have Desktop app, see https://github.com/cinnyapp/cinny-desktop

Mobile app is out of the scope of this repo as we've found out that running the web app with tech like capacitorjs on mobile devices is not great experience and the sdk we are using don't really work well too. 

The best we can provide is a PWA on mobile which is tracked at #172
