### ISSUE TITLE
Pinning chats?

### ISSUE THREAD

**Issue by IngwiePhoenix** [ajbura/cinny#941]
### Describe the problem

I just got to know Cinny and I like it's UI a lot more than Element - feels very refreshing to have a very minimal UI!

However, I have a lot of chats I need pinned - mainly bridged chats - and would like to pin them to the top for quicker access.

Because the problem is, with a lot of chats, there is a chance of losing track of one of them.

### Describe the solution you'd like

A context menu entry to just pin specific rooms to the top of the list - or a button... but yeah, basically that.

### Alternatives considered

A side-menu entry to see pinned rooms.

### Additional context

None I could think of really! Thank you so much for this awesome client, it looks beautiful and is very well designed.

**Comment by kfiven** [comment]
Seems duplicate of #44
