### ISSUE TITLE
Flickering nickname when hovering over it.

### ISSUE THREAD

**Issue by BlitDev** [ajbura/cinny#951]
### Describe the bug

[Bug video](https://peervideo.ru/w/w9t497Q6k57rvi3RqL5h6Z)

### Reproduction

1. Open any chat or room.
2. Hover over nickname.
3. Move cursor.

### Platform and versions

```shell
1. OS: Arch Linux (latest ver.)
2. Cinny version: 2.2.2-1 (from AUR)
3. Matrix homerserver: inex.rocks (matrix.inex.rocks)
```

**Comment by ajbura** [comment]
Not a bug, this is a feature to find out MXID of someone. In terms of improvement of the feature, seems dup of #212

**Comment by BlitDev** [comment]
> Not a bug, this is a feature to find out MXID of someone. In terms of improvement of the feature, seems dup of #212

Being able to find out a user's federated address by hovering over a nickname is useful, but that's not the problem. The problem is very fast blinking, when going beyond the length of the address.

**Comment by ajbura** [comment]
Unfortunately that’s how hover detection works. If Display name is longer than MXID it’s going to happen.
