### ISSUE TITLE
Edits of message containing invalid emoji code seems to break something

### ISSUE THREAD

**Issue by Chreutz** [ajbura/cinny#955]
If you edit a message containing text between two colons that isn't a valid emoji code, like `:test:`, something breaks and the entire UI disappears and requires a reload.

**Comment by Porkepix** [comment]
It seems the issue happens even when it's not about emojis: I don't use emojis but tried to edit a message with more than one colon in it (actually there were 3), and it produced the same problem. One of those colons was tied to an url (with a missing space that I wanted to edit to add).
I did the edit on another client, and after that edit was working on the very same message. So it looks like colons tied to something else right after can lead to strange issues.
