### ISSUE TITLE
size is shown in kibibytes/mebibytes

### ISSUE THREAD

**Issue by 2-www** [ajbura/cinny#986]
### Describe the bug

size is shown in multiples of 1024^n bytes

### Reproduction

for example, send a file of size 99 KB

### Expected behavior

in cinny, the size is displayed lower than in files

for this example, it's 96,7 KB

### Platform and versions

```shell
GNU/Linux, Epiphany, dev.cinny.in (20/11/2022)
```

**Comment by 2-www** [comment]
Screenshot:
![99kB in nautlius, 96,7 kB in cinny](https://user-images.githubusercontent.com/112013524/202917742-931c6458-4aa1-4dc9-bed3-544a90acb9d5.png)

**Comment by kfiven** [comment]
Well it's not bug right? It's now shown in Kibibytes and you're asking it to shown in Kilobytes?
