### ISSUE TITLE
Add Cinny to 'open in client' selection 

### ISSUE THREAD

**Issue by ShalokShalom** [ajbura/cinny#991]
### Describe the problem

I am currently not able to connect to Cinny, clicking on any Matrix address.

[#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org)

### Describe the solution you'd like

Adding Cinny to this directory. 

https://github.com/matrix-org/matrix.to/tree/main/src/open/clients

**Comment by kfiven** [comment]
It's there now.
